-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity reconstruction_accel_reconstruction_accel_Pipeline_CONV2_Y_CONV2_X_CONV2_OC_CONV2_KY_CONV2_KX_p_ZLfYi is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 72
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);
 
          address2        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce2             : in std_logic; 
          q2              : out std_logic_vector(DataWidth-1 downto 0);
 
          address3        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce3             : in std_logic; 
          q3              : out std_logic_vector(DataWidth-1 downto 0);
 
          address4        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce4             : in std_logic; 
          q4              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of reconstruction_accel_reconstruction_accel_Pipeline_CONV2_Y_CONV2_X_CONV2_OC_CONV2_KY_CONV2_KX_p_ZLfYi is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address2_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address3_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address4_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11011110", 1 => "00100011", 2 => "11101001", 3 => "11011110", 
    4 => "10101110", 5 => "11111110", 6 => "11111101", 7 => "11011100", 
    8 => "00001100", 9 => "11101101", 10 => "00001111", 11 => "11110110", 
    12 => "00001101", 13 => "00110100", 14 => "00110001", 15 => "10010110", 
    16 => "00000111", 17 => "00000001", 18 => "00101111", 19 => "00101010", 
    20 => "11110000", 21 => "00011100", 22 => "11100000", 23 => "00011110", 
    24 => "00101000", 25 => "00000101", 26 => "00001110", 27 => "00010011", 
    28 => "00101111", 29 => "00010001", 30 => "11110111", 31 => "01010001", 
    32 => "00010111", 33 => "11010101", 34 => "00010010", 35 => "11111010", 
    36 => "00000010", 37 => "01001001", 38 => "01110111", 39 => "01000001", 
    40 => "01011010", 41 => "00101000", 42 => "00110010", 43 => "00010110", 
    44 => "01001100", 45 => "00011110", 46 => "11101100", 47 => "01000101", 
    48 => "11100111", 49 => "11011010", 50 => "00000010", 51 => "00100100", 
    52 => "01010011", 53 => "00011011", 54 => "11110101", 55 => "00101001", 
    56 => "11111000", 57 => "00000010", 58 => "10000001", 59 => "00001110", 
    60 => "11000001", 61 => "11001101", 62 => "11101101", 63 => "00001001", 
    64 => "00001011", 65 => "00101110", 66 => "00101111", 67 => "10010010", 
    68 => "11010111", 69 => "00011100", 70 => "11010101", 71 => "10110110");

signal mem1 : mem_array := (
    0 => "11011110", 1 => "00100011", 2 => "11101001", 3 => "11011110", 
    4 => "10101110", 5 => "11111110", 6 => "11111101", 7 => "11011100", 
    8 => "00001100", 9 => "11101101", 10 => "00001111", 11 => "11110110", 
    12 => "00001101", 13 => "00110100", 14 => "00110001", 15 => "10010110", 
    16 => "00000111", 17 => "00000001", 18 => "00101111", 19 => "00101010", 
    20 => "11110000", 21 => "00011100", 22 => "11100000", 23 => "00011110", 
    24 => "00101000", 25 => "00000101", 26 => "00001110", 27 => "00010011", 
    28 => "00101111", 29 => "00010001", 30 => "11110111", 31 => "01010001", 
    32 => "00010111", 33 => "11010101", 34 => "00010010", 35 => "11111010", 
    36 => "00000010", 37 => "01001001", 38 => "01110111", 39 => "01000001", 
    40 => "01011010", 41 => "00101000", 42 => "00110010", 43 => "00010110", 
    44 => "01001100", 45 => "00011110", 46 => "11101100", 47 => "01000101", 
    48 => "11100111", 49 => "11011010", 50 => "00000010", 51 => "00100100", 
    52 => "01010011", 53 => "00011011", 54 => "11110101", 55 => "00101001", 
    56 => "11111000", 57 => "00000010", 58 => "10000001", 59 => "00001110", 
    60 => "11000001", 61 => "11001101", 62 => "11101101", 63 => "00001001", 
    64 => "00001011", 65 => "00101110", 66 => "00101111", 67 => "10010010", 
    68 => "11010111", 69 => "00011100", 70 => "11010101", 71 => "10110110");

signal mem2 : mem_array := (
    0 => "11011110", 1 => "00100011", 2 => "11101001", 3 => "11011110", 
    4 => "10101110", 5 => "11111110", 6 => "11111101", 7 => "11011100", 
    8 => "00001100", 9 => "11101101", 10 => "00001111", 11 => "11110110", 
    12 => "00001101", 13 => "00110100", 14 => "00110001", 15 => "10010110", 
    16 => "00000111", 17 => "00000001", 18 => "00101111", 19 => "00101010", 
    20 => "11110000", 21 => "00011100", 22 => "11100000", 23 => "00011110", 
    24 => "00101000", 25 => "00000101", 26 => "00001110", 27 => "00010011", 
    28 => "00101111", 29 => "00010001", 30 => "11110111", 31 => "01010001", 
    32 => "00010111", 33 => "11010101", 34 => "00010010", 35 => "11111010", 
    36 => "00000010", 37 => "01001001", 38 => "01110111", 39 => "01000001", 
    40 => "01011010", 41 => "00101000", 42 => "00110010", 43 => "00010110", 
    44 => "01001100", 45 => "00011110", 46 => "11101100", 47 => "01000101", 
    48 => "11100111", 49 => "11011010", 50 => "00000010", 51 => "00100100", 
    52 => "01010011", 53 => "00011011", 54 => "11110101", 55 => "00101001", 
    56 => "11111000", 57 => "00000010", 58 => "10000001", 59 => "00001110", 
    60 => "11000001", 61 => "11001101", 62 => "11101101", 63 => "00001001", 
    64 => "00001011", 65 => "00101110", 66 => "00101111", 67 => "10010010", 
    68 => "11010111", 69 => "00011100", 70 => "11010101", 71 => "10110110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_2: process (address2) 
begin
      address2_tmp <= address2;
--synthesis translate_off
      if (CONV_INTEGER(address2) > AddressRange-1) then
           address2_tmp <= (others => '0');
      else 
           address2_tmp <= address2;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_3: process (address3) 
begin
      address3_tmp <= address3;
--synthesis translate_off
      if (CONV_INTEGER(address3) > AddressRange-1) then
           address3_tmp <= (others => '0');
      else 
           address3_tmp <= address3;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_4: process (address4) 
begin
      address4_tmp <= address4;
--synthesis translate_off
      if (CONV_INTEGER(address4) > AddressRange-1) then
           address4_tmp <= (others => '0');
      else 
           address4_tmp <= address4;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;
 
        if (ce2 = '1') then  
            q2 <= mem1(CONV_INTEGER(address2_tmp)); 
        end if;
 
        if (ce3 = '1') then  
            q3 <= mem1(CONV_INTEGER(address3_tmp)); 
        end if;
 
        if (ce4 = '1') then  
            q4 <= mem2(CONV_INTEGER(address4_tmp)); 
        end if;

end if;
end process;

end rtl;

