-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem1_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_WREADY : IN STD_LOGIC;
    m_axi_gmem1_0_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem1_0_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RVALID : IN STD_LOGIC;
    m_axi_gmem1_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_0_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem1_0_RLAST : IN STD_LOGIC;
    m_axi_gmem1_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RFIFONUM : IN STD_LOGIC_VECTOR (9 downto 0);
    m_axi_gmem1_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_BVALID : IN STD_LOGIC;
    m_axi_gmem1_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln801 : IN STD_LOGIC_VECTOR (62 downto 0);
    conv2_out_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    conv2_out_ce0 : OUT STD_LOGIC;
    conv2_out_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    baseline_ticks_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    baseline_ticks_ce0 : OUT STD_LOGIC;
    baseline_ticks_q0 : IN STD_LOGIC_VECTOR (13 downto 0) );
end;


architecture behav of reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_FFFFFA7D : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111101001111101";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv20_90000 : STD_LOGIC_VECTOR (19 downto 0) := "10010000000000000000";
    constant ap_const_lv20_1 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000001";
    constant ap_const_lv13_900 : STD_LOGIC_VECTOR (12 downto 0) := "0100100000000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv44_80000 : STD_LOGIC_VECTOR (43 downto 0) := "00000000000000000000000010000000000000000000";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv24_FFFF81 : STD_LOGIC_VECTOR (23 downto 0) := "111111111111111110000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv8_81 : STD_LOGIC_VECTOR (7 downto 0) := "10000001";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv32_9023E5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000100100000010001111100101";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_80000 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000010000000000000000000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv14_FF0 : STD_LOGIC_VECTOR (13 downto 0) := "00111111110000";
    constant ap_const_lv12_FF0 : STD_LOGIC_VECTOR (11 downto 0) := "111111110000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln828_1_reg_1414 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_1_reg_1414_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln821_1_reg_1473 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln821_1_reg_1473_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op259_write_state12 : BOOLEAN;
    signal ap_block_state12_io_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln803_fu_417_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal p_ZL13CONV3_WEIGHTS_0_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_ZL13CONV3_WEIGHTS_0_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13CONV3_WEIGHTS_1_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_ZL13CONV3_WEIGHTS_1_q0 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_ZL13CONV3_WEIGHTS_2_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_ZL13CONV3_WEIGHTS_2_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13CONV3_WEIGHTS_3_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_ZL13CONV3_WEIGHTS_3_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13CONV3_WEIGHTS_4_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_ZL13CONV3_WEIGHTS_4_q0 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_ZL13CONV3_WEIGHTS_5_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_ZL13CONV3_WEIGHTS_5_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13CONV3_WEIGHTS_6_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_ZL13CONV3_WEIGHTS_6_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13CONV3_WEIGHTS_7_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_ZL13CONV3_WEIGHTS_7_q0 : STD_LOGIC_VECTOR (6 downto 0);
    signal gmem1_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln810_fu_435_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln810_reg_1386 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_479_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_1391 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_1391_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_1391_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_1391_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_1391_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_mid2121_fu_503_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_mid2121_reg_1397 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln810_fu_509_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln810_reg_1402 : STD_LOGIC_VECTOR (8 downto 0);
    signal kx_mid2_fu_529_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal kx_mid2_reg_1408 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln828_1_fu_543_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_1_reg_1414_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_1_reg_1414_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_1_reg_1414_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_1_reg_1414_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_1_reg_1414_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_1_reg_1414_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_1_reg_1414_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_1_reg_1414_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln1051_fu_660_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1051_reg_1418 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1051_reg_1418_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1051_reg_1418_pp0_iter4_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1051_reg_1418_pp0_iter5_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1051_reg_1418_pp0_iter6_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1051_reg_1418_pp0_iter7_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1051_reg_1418_pp0_iter8_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln843_fu_764_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln843_reg_1428 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln843_reg_1428_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln843_reg_1428_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln843_reg_1428_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln843_reg_1428_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln821_1_fu_788_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln821_1_reg_1473_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln821_1_reg_1473_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln821_1_reg_1473_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln821_1_reg_1473_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln821_1_reg_1473_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln821_1_reg_1473_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln821_1_reg_1473_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal a0_fu_804_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal a0_reg_1477 : STD_LOGIC_VECTOR (7 downto 0);
    signal a2_reg_1482 : STD_LOGIC_VECTOR (7 downto 0);
    signal a2_reg_1482_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal a3_reg_1487 : STD_LOGIC_VECTOR (7 downto 0);
    signal a3_reg_1487_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal a5_reg_1492 : STD_LOGIC_VECTOR (7 downto 0);
    signal a6_reg_1497 : STD_LOGIC_VECTOR (7 downto 0);
    signal a6_reg_1497_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13CONV3_WEIGHTS_0_load_reg_1502 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13CONV3_WEIGHTS_2_load_reg_1517 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13CONV3_WEIGHTS_2_load_reg_1517_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13CONV3_WEIGHTS_3_load_reg_1522 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13CONV3_WEIGHTS_3_load_reg_1522_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13CONV3_WEIGHTS_5_load_reg_1537 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13CONV3_WEIGHTS_6_load_reg_1542 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13CONV3_WEIGHTS_6_load_reg_1542_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1003_4_fu_928_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal acc_11_mid2117_fu_947_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_11_mid2117_reg_1592 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1287_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1003_1_reg_1598 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1295_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1003_3_reg_1603 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1279_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal acc_1_fu_984_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_1_reg_1613 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln1010_fu_1010_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal sub_ln1010_reg_1619 : STD_LOGIC_VECTOR (43 downto 0);
    signal residual_q_raw_fu_1100_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal residual_q_raw_reg_1624 : STD_LOGIC_VECTOR (23 downto 0);
    signal icmp_ln98_fu_1108_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln98_reg_1629 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln102_fu_1124_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln102_reg_1635 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln1032_fu_1160_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln1032_reg_1645 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln1078_fu_1261_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln1078_reg_1652 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln855_fu_743_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln897_fu_776_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1051_1_fu_1130_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal acc_fu_188 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_load : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal kx_fu_192 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal add_ln829_fu_537_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ky_fu_196 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal select_ln821_fu_638_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten107_fu_200 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln821_1_fu_555_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal x_fu_204 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal indvar_flatten122_fu_208 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal select_ln810_1_fu_569_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal y_fu_212 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal select_ln803_fu_614_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal indvar_flatten147_fu_216 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    signal add_ln803_fu_423_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal conv2_out_ce0_local : STD_LOGIC;
    signal p_ZL13CONV3_WEIGHTS_0_ce0_local : STD_LOGIC;
    signal p_ZL13CONV3_WEIGHTS_1_ce0_local : STD_LOGIC;
    signal p_ZL13CONV3_WEIGHTS_2_ce0_local : STD_LOGIC;
    signal p_ZL13CONV3_WEIGHTS_3_ce0_local : STD_LOGIC;
    signal p_ZL13CONV3_WEIGHTS_4_ce0_local : STD_LOGIC;
    signal p_ZL13CONV3_WEIGHTS_5_ce0_local : STD_LOGIC;
    signal p_ZL13CONV3_WEIGHTS_6_ce0_local : STD_LOGIC;
    signal p_ZL13CONV3_WEIGHTS_7_ce0_local : STD_LOGIC;
    signal baseline_ticks_ce0_local : STD_LOGIC;
    signal icmp_ln821_fu_461_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln802_fu_449_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln802_fu_441_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal and_ln802_1_fu_467_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten109_not_fu_485_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_fu_455_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln802_fu_497_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_exitcond_flatten109_mid2146_fu_491_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln811_fu_473_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal empty_47_fu_517_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_48_fu_523_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln821_fu_549_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln810_fu_563_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln804_fu_608_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ky_mid2114_fu_625_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln822_fu_632_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln811_fu_621_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_645_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1051_fu_657_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp112_fu_673_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp112_cast_fu_679_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln803_fu_653_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_49_fu_683_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln855_fu_689_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_shl1_fu_701_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln821_fu_669_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln838_fu_718_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln838_fu_723_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln810_fu_666_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln838_1_fu_727_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_1_fu_693_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln855_fu_733_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln855_fu_737_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln843_fu_748_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_fu_754_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln828_fu_715_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_50_fu_709_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln886_fu_770_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal a1_fu_808_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal a4_fu_832_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal a7_fu_856_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1003_3_fu_918_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1003_3_fu_918_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1003_4_fu_928_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1003_7_fu_934_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1003_7_fu_934_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1003_8_fu_954_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1303_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1312_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1003_10_fu_965_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln1003_9_fu_962_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln1003_6_fu_968_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln1003_11_fu_974_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1003_2_fu_957_p2 : STD_LOGIC_VECTOR (31 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln1003_2_fu_957_p2 : signal is "no";
    signal acc_2_fu_978_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_998_p3 : STD_LOGIC_VECTOR (40 downto 0);
    signal p_shl_fu_990_p3 : STD_LOGIC_VECTOR (43 downto 0);
    signal sext_ln1010_fu_1006_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal tmp_3_fu_1021_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal sext_ln1010_1_fu_1028_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal tmp_4_fu_1037_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal sub_ln1010_1_fu_1032_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal sext_ln1010_2_fu_1044_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal add_ln1010_fu_1048_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal add_ln39_fu_1062_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal sub_ln45_fu_1078_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal trunc_ln46_7_fu_1084_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_5_fu_1054_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln43_fu_1094_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln40_7_fu_1068_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_6_fu_1114_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal or_ln98_fu_1144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln98_fu_1137_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln106_fu_1134_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal residual_q_fu_1148_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1032_fu_1160_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal sub_ln45_1_fu_1178_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln39_1_fu_1173_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln_fu_1183_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_7_fu_1166_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln37_fu_1203_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln1_fu_1193_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln37_fu_1209_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln1051_fu_1217_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln1053_fu_1221_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal final_value_fu_1225_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_8_fu_1235_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1048_fu_1231_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal final_value_1_fu_1243_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln1068_fu_1251_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1078_fu_1257_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_1279_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1287_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1295_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1303_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1303_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1312_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1279_ce : STD_LOGIC;
    signal grp_fu_1287_ce : STD_LOGIC;
    signal grp_fu_1295_ce : STD_LOGIC;
    signal grp_fu_1303_ce : STD_LOGIC;
    signal grp_fu_1312_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_1279_p00 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_1287_p00 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_1295_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_1303_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1312_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1003_3_fu_918_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1003_4_fu_928_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1003_7_fu_934_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component reconstruction_accel_mul_8s_8ns_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component reconstruction_accel_mul_8s_25ns_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (24 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component reconstruction_accel_mac_muladd_8ns_7s_16s_17_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component reconstruction_accel_mac_muladd_8ns_5s_16s_16_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component reconstruction_accel_mac_muladd_8s_8ns_32s_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component reconstruction_accel_mac_muladd_8s_8ns_17s_17_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (16 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_Wncg IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_Wocq IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_WpcA IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_WqcK IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_WrcU IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_Wsc4 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_Wtde IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_Wudo IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component reconstruction_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    p_ZL13CONV3_WEIGHTS_0_U : component reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_Wncg
    generic map (
        DataWidth => 8,
        AddressRange => 9,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL13CONV3_WEIGHTS_0_address0,
        ce0 => p_ZL13CONV3_WEIGHTS_0_ce0_local,
        q0 => p_ZL13CONV3_WEIGHTS_0_q0);

    p_ZL13CONV3_WEIGHTS_1_U : component reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_Wocq
    generic map (
        DataWidth => 7,
        AddressRange => 9,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL13CONV3_WEIGHTS_1_address0,
        ce0 => p_ZL13CONV3_WEIGHTS_1_ce0_local,
        q0 => p_ZL13CONV3_WEIGHTS_1_q0);

    p_ZL13CONV3_WEIGHTS_2_U : component reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_WpcA
    generic map (
        DataWidth => 8,
        AddressRange => 9,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL13CONV3_WEIGHTS_2_address0,
        ce0 => p_ZL13CONV3_WEIGHTS_2_ce0_local,
        q0 => p_ZL13CONV3_WEIGHTS_2_q0);

    p_ZL13CONV3_WEIGHTS_3_U : component reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_WqcK
    generic map (
        DataWidth => 8,
        AddressRange => 9,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL13CONV3_WEIGHTS_3_address0,
        ce0 => p_ZL13CONV3_WEIGHTS_3_ce0_local,
        q0 => p_ZL13CONV3_WEIGHTS_3_q0);

    p_ZL13CONV3_WEIGHTS_4_U : component reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_WrcU
    generic map (
        DataWidth => 5,
        AddressRange => 9,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL13CONV3_WEIGHTS_4_address0,
        ce0 => p_ZL13CONV3_WEIGHTS_4_ce0_local,
        q0 => p_ZL13CONV3_WEIGHTS_4_q0);

    p_ZL13CONV3_WEIGHTS_5_U : component reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_Wsc4
    generic map (
        DataWidth => 8,
        AddressRange => 9,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL13CONV3_WEIGHTS_5_address0,
        ce0 => p_ZL13CONV3_WEIGHTS_5_ce0_local,
        q0 => p_ZL13CONV3_WEIGHTS_5_q0);

    p_ZL13CONV3_WEIGHTS_6_U : component reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_Wtde
    generic map (
        DataWidth => 8,
        AddressRange => 9,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL13CONV3_WEIGHTS_6_address0,
        ce0 => p_ZL13CONV3_WEIGHTS_6_ce0_local,
        q0 => p_ZL13CONV3_WEIGHTS_6_q0);

    p_ZL13CONV3_WEIGHTS_7_U : component reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_Wudo
    generic map (
        DataWidth => 7,
        AddressRange => 9,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL13CONV3_WEIGHTS_7_address0,
        ce0 => p_ZL13CONV3_WEIGHTS_7_ce0_local,
        q0 => p_ZL13CONV3_WEIGHTS_7_q0);

    mul_8s_8ns_16_1_1_U137 : component reconstruction_accel_mul_8s_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => p_ZL13CONV3_WEIGHTS_2_load_reg_1517_pp0_iter4_reg,
        din1 => mul_ln1003_3_fu_918_p1,
        dout => mul_ln1003_3_fu_918_p2);

    mul_8s_8ns_16_1_1_U138 : component reconstruction_accel_mul_8s_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => p_ZL13CONV3_WEIGHTS_3_load_reg_1522_pp0_iter4_reg,
        din1 => mul_ln1003_4_fu_928_p1,
        dout => mul_ln1003_4_fu_928_p2);

    mul_8s_8ns_16_1_1_U139 : component reconstruction_accel_mul_8s_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => p_ZL13CONV3_WEIGHTS_6_load_reg_1542_pp0_iter4_reg,
        din1 => mul_ln1003_7_fu_934_p1,
        dout => mul_ln1003_7_fu_934_p2);

    mul_8s_25ns_32_1_1_U140 : component reconstruction_accel_mul_8s_25ns_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 25,
        dout_WIDTH => 32)
    port map (
        din0 => residual_q_fu_1148_p3,
        din1 => mul_ln1032_fu_1160_p1,
        dout => mul_ln1032_fu_1160_p2);

    mac_muladd_8ns_7s_16s_17_4_1_U141 : component reconstruction_accel_mac_muladd_8ns_7s_16s_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1279_p0,
        din1 => p_ZL13CONV3_WEIGHTS_7_q0,
        din2 => mul_ln1003_7_fu_934_p2,
        ce => grp_fu_1279_ce,
        dout => grp_fu_1279_p3);

    mac_muladd_8ns_7s_16s_17_4_1_U142 : component reconstruction_accel_mac_muladd_8ns_7s_16s_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1287_p0,
        din1 => p_ZL13CONV3_WEIGHTS_1_q0,
        din2 => mul_ln1003_3_fu_918_p2,
        ce => grp_fu_1287_ce,
        dout => grp_fu_1287_p3);

    mac_muladd_8ns_5s_16s_16_4_1_U143 : component reconstruction_accel_mac_muladd_8ns_5s_16s_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1295_p0,
        din1 => p_ZL13CONV3_WEIGHTS_4_q0,
        din2 => mul_ln1003_4_fu_928_p2,
        ce => grp_fu_1295_ce,
        dout => grp_fu_1295_p3);

    mac_muladd_8s_8ns_32s_32_4_1_U144 : component reconstruction_accel_mac_muladd_8s_8ns_32s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_ZL13CONV3_WEIGHTS_0_load_reg_1502,
        din1 => grp_fu_1303_p1,
        din2 => grp_fu_1303_p2,
        ce => grp_fu_1303_ce,
        dout => grp_fu_1303_p3);

    mac_muladd_8s_8ns_17s_17_4_1_U145 : component reconstruction_accel_mac_muladd_8s_8ns_17s_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 17,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_ZL13CONV3_WEIGHTS_5_load_reg_1537,
        din1 => grp_fu_1312_p1,
        din2 => grp_fu_1279_p3,
        ce => grp_fu_1312_ce,
        dout => grp_fu_1312_p3);

    flow_control_loop_pipe_sequential_init_U : component reconstruction_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    acc_fu_188_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_fu_188 <= ap_const_lv32_FFFFFA7D;
                elsif ((ap_enable_reg_pp0_iter7 = ap_const_logic_1)) then 
                    acc_fu_188 <= acc_1_fu_984_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten107_fu_200_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten107_fu_200 <= ap_const_lv4_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln803_fu_417_p2 = ap_const_lv1_0))) then 
                    indvar_flatten107_fu_200 <= select_ln821_1_fu_555_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten122_fu_208_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten122_fu_208 <= ap_const_lv13_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln803_fu_417_p2 = ap_const_lv1_0))) then 
                    indvar_flatten122_fu_208 <= select_ln810_1_fu_569_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten147_fu_216_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten147_fu_216 <= ap_const_lv20_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln803_fu_417_p2 = ap_const_lv1_0))) then 
                    indvar_flatten147_fu_216 <= add_ln803_fu_423_p2;
                end if;
            end if; 
        end if;
    end process;

    kx_fu_192_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    kx_fu_192 <= ap_const_lv2_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln803_fu_417_p2 = ap_const_lv1_0))) then 
                    kx_fu_192 <= add_ln829_fu_537_p2;
                end if;
            end if; 
        end if;
    end process;

    ky_fu_196_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ky_fu_196 <= ap_const_lv2_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    ky_fu_196 <= select_ln821_fu_638_p3;
                end if;
            end if; 
        end if;
    end process;

    x_fu_204_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_204 <= ap_const_lv9_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln803_fu_417_p2 = ap_const_lv1_0))) then 
                    x_fu_204 <= select_ln810_fu_509_p3;
                end if;
            end if; 
        end if;
    end process;

    y_fu_212_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    y_fu_212 <= ap_const_lv9_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    y_fu_212 <= select_ln803_fu_614_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                a0_reg_1477 <= a0_fu_804_p1;
                a2_reg_1482 <= conv2_out_q0(23 downto 16);
                a2_reg_1482_pp0_iter4_reg <= a2_reg_1482;
                a3_reg_1487 <= conv2_out_q0(31 downto 24);
                a3_reg_1487_pp0_iter4_reg <= a3_reg_1487;
                a5_reg_1492 <= conv2_out_q0(47 downto 40);
                a6_reg_1497 <= conv2_out_q0(55 downto 48);
                a6_reg_1497_pp0_iter4_reg <= a6_reg_1497;
                acc_11_mid2117_reg_1592 <= acc_11_mid2117_fu_947_p3;
                acc_1_reg_1613 <= acc_1_fu_984_p3;
                add_ln1051_reg_1418 <= add_ln1051_fu_660_p2;
                add_ln1051_reg_1418_pp0_iter3_reg <= add_ln1051_reg_1418;
                add_ln1051_reg_1418_pp0_iter4_reg <= add_ln1051_reg_1418_pp0_iter3_reg;
                add_ln1051_reg_1418_pp0_iter5_reg <= add_ln1051_reg_1418_pp0_iter4_reg;
                add_ln1051_reg_1418_pp0_iter6_reg <= add_ln1051_reg_1418_pp0_iter5_reg;
                add_ln1051_reg_1418_pp0_iter7_reg <= add_ln1051_reg_1418_pp0_iter6_reg;
                add_ln1051_reg_1418_pp0_iter8_reg <= add_ln1051_reg_1418_pp0_iter7_reg;
                icmp_ln102_reg_1635 <= icmp_ln102_fu_1124_p2;
                icmp_ln821_1_reg_1473 <= icmp_ln821_1_fu_788_p2;
                icmp_ln821_1_reg_1473_pp0_iter10_reg <= icmp_ln821_1_reg_1473_pp0_iter9_reg;
                icmp_ln821_1_reg_1473_pp0_iter3_reg <= icmp_ln821_1_reg_1473;
                icmp_ln821_1_reg_1473_pp0_iter4_reg <= icmp_ln821_1_reg_1473_pp0_iter3_reg;
                icmp_ln821_1_reg_1473_pp0_iter5_reg <= icmp_ln821_1_reg_1473_pp0_iter4_reg;
                icmp_ln821_1_reg_1473_pp0_iter6_reg <= icmp_ln821_1_reg_1473_pp0_iter5_reg;
                icmp_ln821_1_reg_1473_pp0_iter7_reg <= icmp_ln821_1_reg_1473_pp0_iter6_reg;
                icmp_ln821_1_reg_1473_pp0_iter8_reg <= icmp_ln821_1_reg_1473_pp0_iter7_reg;
                icmp_ln821_1_reg_1473_pp0_iter9_reg <= icmp_ln821_1_reg_1473_pp0_iter8_reg;
                icmp_ln843_reg_1428 <= icmp_ln843_fu_764_p2;
                icmp_ln843_reg_1428_pp0_iter3_reg <= icmp_ln843_reg_1428;
                icmp_ln843_reg_1428_pp0_iter4_reg <= icmp_ln843_reg_1428_pp0_iter3_reg;
                icmp_ln843_reg_1428_pp0_iter5_reg <= icmp_ln843_reg_1428_pp0_iter4_reg;
                icmp_ln843_reg_1428_pp0_iter6_reg <= icmp_ln843_reg_1428_pp0_iter5_reg;
                icmp_ln98_reg_1629 <= icmp_ln98_fu_1108_p2;
                mul_ln1032_reg_1645 <= mul_ln1032_fu_1160_p2;
                p_ZL13CONV3_WEIGHTS_0_load_reg_1502 <= p_ZL13CONV3_WEIGHTS_0_q0;
                p_ZL13CONV3_WEIGHTS_2_load_reg_1517 <= p_ZL13CONV3_WEIGHTS_2_q0;
                p_ZL13CONV3_WEIGHTS_2_load_reg_1517_pp0_iter4_reg <= p_ZL13CONV3_WEIGHTS_2_load_reg_1517;
                p_ZL13CONV3_WEIGHTS_3_load_reg_1522 <= p_ZL13CONV3_WEIGHTS_3_q0;
                p_ZL13CONV3_WEIGHTS_3_load_reg_1522_pp0_iter4_reg <= p_ZL13CONV3_WEIGHTS_3_load_reg_1522;
                p_ZL13CONV3_WEIGHTS_5_load_reg_1537 <= p_ZL13CONV3_WEIGHTS_5_q0;
                p_ZL13CONV3_WEIGHTS_6_load_reg_1542 <= p_ZL13CONV3_WEIGHTS_6_q0;
                p_ZL13CONV3_WEIGHTS_6_load_reg_1542_pp0_iter4_reg <= p_ZL13CONV3_WEIGHTS_6_load_reg_1542;
                residual_q_raw_reg_1624 <= residual_q_raw_fu_1100_p3;
                select_ln1078_reg_1652 <= select_ln1078_fu_1261_p3;
                    sub_ln1010_reg_1619(43 downto 9) <= sub_ln1010_fu_1010_p2(43 downto 9);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                add_ln1003_1_reg_1598 <= grp_fu_1287_p3;
                add_ln1003_3_reg_1603 <= grp_fu_1295_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                empty_reg_1391_pp0_iter2_reg <= empty_reg_1391;
                empty_reg_1391_pp0_iter3_reg <= empty_reg_1391_pp0_iter2_reg;
                empty_reg_1391_pp0_iter4_reg <= empty_reg_1391_pp0_iter3_reg;
                empty_reg_1391_pp0_iter5_reg <= empty_reg_1391_pp0_iter4_reg;
                icmp_ln828_1_reg_1414_pp0_iter10_reg <= icmp_ln828_1_reg_1414_pp0_iter9_reg;
                icmp_ln828_1_reg_1414_pp0_iter2_reg <= icmp_ln828_1_reg_1414;
                icmp_ln828_1_reg_1414_pp0_iter3_reg <= icmp_ln828_1_reg_1414_pp0_iter2_reg;
                icmp_ln828_1_reg_1414_pp0_iter4_reg <= icmp_ln828_1_reg_1414_pp0_iter3_reg;
                icmp_ln828_1_reg_1414_pp0_iter5_reg <= icmp_ln828_1_reg_1414_pp0_iter4_reg;
                icmp_ln828_1_reg_1414_pp0_iter6_reg <= icmp_ln828_1_reg_1414_pp0_iter5_reg;
                icmp_ln828_1_reg_1414_pp0_iter7_reg <= icmp_ln828_1_reg_1414_pp0_iter6_reg;
                icmp_ln828_1_reg_1414_pp0_iter8_reg <= icmp_ln828_1_reg_1414_pp0_iter7_reg;
                icmp_ln828_1_reg_1414_pp0_iter9_reg <= icmp_ln828_1_reg_1414_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                empty_reg_1391 <= empty_fu_479_p2;
                icmp_ln810_reg_1386 <= icmp_ln810_fu_435_p2;
                icmp_ln828_1_reg_1414 <= icmp_ln828_1_fu_543_p2;
                icmp_ln828_mid2121_reg_1397 <= icmp_ln828_mid2121_fu_503_p2;
                kx_mid2_reg_1408 <= kx_mid2_fu_529_p3;
                select_ln810_reg_1402 <= select_ln810_fu_509_p3;
            end if;
        end if;
    end process;
    sub_ln1010_reg_1619(8 downto 0) <= "000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    a0_fu_804_p1 <= conv2_out_q0(8 - 1 downto 0);
    a1_fu_808_p3 <= conv2_out_q0(15 downto 8);
    a4_fu_832_p3 <= conv2_out_q0(39 downto 32);
    a7_fu_856_p3 <= conv2_out_q0(63 downto 56);
    acc_11_mid2117_fu_947_p3 <= 
        ap_const_lv32_FFFFFA7D when (empty_reg_1391_pp0_iter5_reg(0) = '1') else 
        ap_sig_allocacmp_acc_load;
    acc_1_fu_984_p3 <= 
        acc_2_fu_978_p2 when (icmp_ln843_reg_1428_pp0_iter6_reg(0) = '1') else 
        acc_11_mid2117_reg_1592;
    acc_2_fu_978_p2 <= std_logic_vector(signed(sext_ln1003_11_fu_974_p1) + signed(add_ln1003_2_fu_957_p2));
    add_ln1003_2_fu_957_p2 <= std_logic_vector(signed(sext_ln1003_8_fu_954_p1) + signed(grp_fu_1303_p3));
    add_ln1003_6_fu_968_p2 <= std_logic_vector(signed(sext_ln1003_10_fu_965_p1) + signed(sext_ln1003_9_fu_962_p1));
    add_ln1010_fu_1048_p2 <= std_logic_vector(unsigned(sub_ln1010_1_fu_1032_p2) + unsigned(sext_ln1010_2_fu_1044_p1));
    add_ln1051_fu_660_p2 <= std_logic_vector(unsigned(tmp_s_fu_645_p3) + unsigned(zext_ln1051_fu_657_p1));
    add_ln39_1_fu_1173_p2 <= std_logic_vector(unsigned(mul_ln1032_reg_1645) + unsigned(ap_const_lv32_80000));
    add_ln39_fu_1062_p2 <= std_logic_vector(unsigned(add_ln1010_fu_1048_p2) + unsigned(ap_const_lv44_80000));
    add_ln803_fu_423_p2 <= std_logic_vector(unsigned(indvar_flatten147_fu_216) + unsigned(ap_const_lv20_1));
    add_ln804_fu_608_p2 <= std_logic_vector(unsigned(y_fu_212) + unsigned(ap_const_lv9_1));
    add_ln810_fu_563_p2 <= std_logic_vector(unsigned(indvar_flatten122_fu_208) + unsigned(ap_const_lv13_1));
    add_ln811_fu_473_p2 <= std_logic_vector(unsigned(select_ln802_fu_441_p3) + unsigned(ap_const_lv9_1));
    add_ln821_fu_549_p2 <= std_logic_vector(unsigned(indvar_flatten107_fu_200) + unsigned(ap_const_lv4_1));
    add_ln822_fu_632_p2 <= std_logic_vector(unsigned(ky_mid2114_fu_625_p3) + unsigned(ap_const_lv2_1));
    add_ln829_fu_537_p2 <= std_logic_vector(unsigned(kx_mid2_fu_529_p3) + unsigned(ap_const_lv2_1));
    add_ln838_1_fu_727_p2 <= std_logic_vector(signed(sext_ln838_fu_723_p1) + signed(zext_ln810_fu_666_p1));
    add_ln838_fu_718_p2 <= std_logic_vector(unsigned(kx_mid2_reg_1408) + unsigned(ap_const_lv2_3));
    add_ln855_fu_737_p2 <= std_logic_vector(unsigned(tmp_1_fu_693_p3) + unsigned(sext_ln855_fu_733_p1));
    add_ln886_fu_770_p2 <= std_logic_vector(unsigned(zext_ln828_fu_715_p1) + unsigned(empty_50_fu_709_p2));
    and_ln802_1_fu_467_p2 <= (xor_ln802_fu_449_p2 and icmp_ln821_fu_461_p2);
    and_ln802_fu_497_p2 <= (xor_ln802_fu_449_p2 and icmp_ln828_fu_455_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_state12_io_grp1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state12_io_grp1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_state12_io_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state12_io_grp1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_state12_io_grp1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state12_io_grp1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state12_io_grp1_assign_proc : process(m_axi_gmem1_0_WREADY, ap_predicate_op259_write_state12)
    begin
                ap_block_state12_io_grp1 <= ((m_axi_gmem1_0_WREADY = ap_const_logic_0) and (ap_predicate_op259_write_state12 = ap_const_boolean_1));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln803_fu_417_p2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln803_fu_417_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter10_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_predicate_op259_write_state12_assign_proc : process(icmp_ln828_1_reg_1414_pp0_iter10_reg, icmp_ln821_1_reg_1473_pp0_iter10_reg)
    begin
                ap_predicate_op259_write_state12 <= ((icmp_ln821_1_reg_1473_pp0_iter10_reg = ap_const_lv1_1) and (icmp_ln828_1_reg_1414_pp0_iter10_reg = ap_const_lv1_1));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_acc_load_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_grp1, acc_1_fu_984_p3, acc_fu_188)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            ap_sig_allocacmp_acc_load <= acc_1_fu_984_p3;
        else 
            ap_sig_allocacmp_acc_load <= acc_fu_188;
        end if; 
    end process;

    baseline_ticks_address0 <= zext_ln1051_1_fu_1130_p1(16 - 1 downto 0);
    baseline_ticks_ce0 <= baseline_ticks_ce0_local;

    baseline_ticks_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            baseline_ticks_ce0_local <= ap_const_logic_1;
        else 
            baseline_ticks_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv2_out_address0 <= zext_ln855_fu_743_p1(16 - 1 downto 0);
    conv2_out_ce0 <= conv2_out_ce0_local;

    conv2_out_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            conv2_out_ce0_local <= ap_const_logic_1;
        else 
            conv2_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    empty_47_fu_517_p2 <= (icmp_ln828_mid2121_fu_503_p2 or and_ln802_1_fu_467_p2);
    empty_48_fu_523_p2 <= (icmp_ln810_fu_435_p2 or empty_47_fu_517_p2);
    empty_49_fu_683_p2 <= std_logic_vector(signed(tmp112_cast_fu_679_p1) + signed(zext_ln803_fu_653_p1));
    empty_50_fu_709_p2 <= std_logic_vector(unsigned(p_shl1_fu_701_p3) - unsigned(zext_ln821_fu_669_p1));
    empty_fu_479_p2 <= (icmp_ln810_fu_435_p2 or and_ln802_1_fu_467_p2);
    exitcond_flatten109_not_fu_485_p2 <= (icmp_ln821_fu_461_p2 xor ap_const_lv1_1);
    final_value_1_fu_1243_p3 <= 
        ap_const_lv14_0 when (tmp_8_fu_1235_p3(0) = '1') else 
        trunc_ln1048_fu_1231_p1;
    final_value_fu_1225_p2 <= std_logic_vector(signed(sext_ln1051_fu_1217_p1) + signed(zext_ln1053_fu_1221_p1));

    gmem1_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter11, m_axi_gmem1_0_WREADY, ap_predicate_op259_write_state12, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_predicate_op259_write_state12 = ap_const_boolean_1))) then 
            gmem1_blk_n_W <= m_axi_gmem1_0_WREADY;
        else 
            gmem1_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_1279_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_1279_ce <= ap_const_logic_1;
        else 
            grp_fu_1279_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_1279_p0 <= grp_fu_1279_p00(8 - 1 downto 0);
    grp_fu_1279_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a7_fu_856_p3),15));

    grp_fu_1287_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_1287_ce <= ap_const_logic_1;
        else 
            grp_fu_1287_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_1287_p0 <= grp_fu_1287_p00(8 - 1 downto 0);
    grp_fu_1287_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a1_fu_808_p3),15));

    grp_fu_1295_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_1295_ce <= ap_const_logic_1;
        else 
            grp_fu_1295_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_1295_p0 <= grp_fu_1295_p00(8 - 1 downto 0);
    grp_fu_1295_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a4_fu_832_p3),13));

    grp_fu_1303_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_1303_ce <= ap_const_logic_1;
        else 
            grp_fu_1303_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_1303_p1 <= grp_fu_1303_p10(8 - 1 downto 0);
    grp_fu_1303_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a0_reg_1477),16));
    grp_fu_1303_p2 <= 
        ap_const_lv32_FFFFFA7D when (empty_reg_1391_pp0_iter5_reg(0) = '1') else 
        ap_sig_allocacmp_acc_load;

    grp_fu_1312_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_1312_ce <= ap_const_logic_1;
        else 
            grp_fu_1312_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_1312_p1 <= grp_fu_1312_p10(8 - 1 downto 0);
    grp_fu_1312_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a5_reg_1492),16));
    icmp_ln102_fu_1124_p2 <= "1" when (signed(tmp_6_fu_1114_p4) > signed(ap_const_lv17_0)) else "0";
    icmp_ln1068_fu_1251_p2 <= "1" when (unsigned(final_value_1_fu_1243_p3) > unsigned(ap_const_lv14_FF0)) else "0";
    icmp_ln803_fu_417_p2 <= "1" when (indvar_flatten147_fu_216 = ap_const_lv20_90000) else "0";
    icmp_ln810_fu_435_p2 <= "1" when (indvar_flatten122_fu_208 = ap_const_lv13_900) else "0";
    icmp_ln821_1_fu_788_p2 <= "1" when (select_ln821_fu_638_p3 = ap_const_lv2_2) else "0";
    icmp_ln821_fu_461_p2 <= "1" when (indvar_flatten107_fu_200 = ap_const_lv4_9) else "0";
    icmp_ln828_1_fu_543_p2 <= "1" when (add_ln829_fu_537_p2 = ap_const_lv2_3) else "0";
    icmp_ln828_fu_455_p2 <= "1" when (kx_fu_192 = ap_const_lv2_3) else "0";
    icmp_ln828_mid2121_fu_503_p2 <= (not_exitcond_flatten109_mid2146_fu_491_p2 and and_ln802_fu_497_p2);
    icmp_ln843_fu_764_p2 <= "1" when (tmp_fu_754_p4 = ap_const_lv2_0) else "0";
    icmp_ln98_fu_1108_p2 <= "1" when (signed(residual_q_raw_fu_1100_p3) < signed(ap_const_lv24_FFFF81)) else "0";
    kx_mid2_fu_529_p3 <= 
        ap_const_lv2_0 when (empty_48_fu_523_p2(0) = '1') else 
        kx_fu_192;
    ky_mid2114_fu_625_p3 <= 
        ap_const_lv2_0 when (empty_reg_1391(0) = '1') else 
        ky_fu_196;
    m_axi_gmem1_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem1_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem1_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem1_0_ARID <= ap_const_lv1_0;
    m_axi_gmem1_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem1_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem1_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem1_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem1_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem1_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem1_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem1_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem1_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem1_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem1_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem1_0_AWID <= ap_const_lv1_0;
    m_axi_gmem1_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem1_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem1_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem1_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem1_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem1_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem1_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem1_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem1_0_BREADY <= ap_const_logic_0;
    m_axi_gmem1_0_RREADY <= ap_const_logic_0;
    m_axi_gmem1_0_WDATA <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln1078_reg_1652),16));
    m_axi_gmem1_0_WID <= ap_const_lv1_0;
    m_axi_gmem1_0_WLAST <= ap_const_logic_0;
    m_axi_gmem1_0_WSTRB <= ap_const_lv2_3;
    m_axi_gmem1_0_WUSER <= ap_const_lv1_0;

    m_axi_gmem1_0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter11, ap_predicate_op259_write_state12, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_predicate_op259_write_state12 = ap_const_boolean_1))) then 
            m_axi_gmem1_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem1_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln1003_3_fu_918_p1 <= mul_ln1003_3_fu_918_p10(8 - 1 downto 0);
    mul_ln1003_3_fu_918_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a2_reg_1482_pp0_iter4_reg),16));
    mul_ln1003_4_fu_928_p1 <= mul_ln1003_4_fu_928_p10(8 - 1 downto 0);
    mul_ln1003_4_fu_928_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a3_reg_1487_pp0_iter4_reg),16));
    mul_ln1003_7_fu_934_p1 <= mul_ln1003_7_fu_934_p10(8 - 1 downto 0);
    mul_ln1003_7_fu_934_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a6_reg_1497_pp0_iter4_reg),16));
    mul_ln1032_fu_1160_p1 <= ap_const_lv32_9023E5(25 - 1 downto 0);
    not_exitcond_flatten109_mid2146_fu_491_p2 <= (icmp_ln810_fu_435_p2 or exitcond_flatten109_not_fu_485_p2);
    or_ln843_fu_748_p2 <= (empty_49_fu_683_p2 or add_ln838_1_fu_727_p2);
    or_ln98_fu_1144_p2 <= (icmp_ln98_reg_1629 or icmp_ln102_reg_1635);
    p_ZL13CONV3_WEIGHTS_0_address0 <= zext_ln897_fu_776_p1(4 - 1 downto 0);

    p_ZL13CONV3_WEIGHTS_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            p_ZL13CONV3_WEIGHTS_0_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13CONV3_WEIGHTS_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13CONV3_WEIGHTS_1_address0 <= zext_ln897_fu_776_p1(4 - 1 downto 0);

    p_ZL13CONV3_WEIGHTS_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            p_ZL13CONV3_WEIGHTS_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13CONV3_WEIGHTS_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13CONV3_WEIGHTS_2_address0 <= zext_ln897_fu_776_p1(4 - 1 downto 0);

    p_ZL13CONV3_WEIGHTS_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            p_ZL13CONV3_WEIGHTS_2_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13CONV3_WEIGHTS_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13CONV3_WEIGHTS_3_address0 <= zext_ln897_fu_776_p1(4 - 1 downto 0);

    p_ZL13CONV3_WEIGHTS_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            p_ZL13CONV3_WEIGHTS_3_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13CONV3_WEIGHTS_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13CONV3_WEIGHTS_4_address0 <= zext_ln897_fu_776_p1(4 - 1 downto 0);

    p_ZL13CONV3_WEIGHTS_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            p_ZL13CONV3_WEIGHTS_4_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13CONV3_WEIGHTS_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13CONV3_WEIGHTS_5_address0 <= zext_ln897_fu_776_p1(4 - 1 downto 0);

    p_ZL13CONV3_WEIGHTS_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            p_ZL13CONV3_WEIGHTS_5_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13CONV3_WEIGHTS_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13CONV3_WEIGHTS_6_address0 <= zext_ln897_fu_776_p1(4 - 1 downto 0);

    p_ZL13CONV3_WEIGHTS_6_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            p_ZL13CONV3_WEIGHTS_6_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13CONV3_WEIGHTS_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13CONV3_WEIGHTS_7_address0 <= zext_ln897_fu_776_p1(4 - 1 downto 0);

    p_ZL13CONV3_WEIGHTS_7_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            p_ZL13CONV3_WEIGHTS_7_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13CONV3_WEIGHTS_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_shl1_fu_701_p3 <= (select_ln821_fu_638_p3 & ap_const_lv2_0);
    p_shl_fu_990_p3 <= (acc_1_fu_984_p3 & ap_const_lv12_0);
    residual_q_fu_1148_p3 <= 
        select_ln98_fu_1137_p3 when (or_ln98_fu_1144_p2(0) = '1') else 
        trunc_ln106_fu_1134_p1;
    residual_q_raw_fu_1100_p3 <= 
        sub_ln43_fu_1094_p2 when (tmp_5_fu_1054_p3(0) = '1') else 
        trunc_ln40_7_fu_1068_p4;
    select_ln1078_fu_1261_p3 <= 
        ap_const_lv12_FF0 when (icmp_ln1068_fu_1251_p2(0) = '1') else 
        trunc_ln1078_fu_1257_p1;
    select_ln37_fu_1209_p3 <= 
        sub_ln37_fu_1203_p2 when (tmp_7_fu_1166_p3(0) = '1') else 
        trunc_ln1_fu_1193_p4;
    select_ln802_fu_441_p3 <= 
        ap_const_lv9_0 when (icmp_ln810_fu_435_p2(0) = '1') else 
        x_fu_204;
    select_ln803_fu_614_p3 <= 
        add_ln804_fu_608_p2 when (icmp_ln810_reg_1386(0) = '1') else 
        y_fu_212;
    select_ln810_1_fu_569_p3 <= 
        ap_const_lv13_1 when (icmp_ln810_fu_435_p2(0) = '1') else 
        add_ln810_fu_563_p2;
    select_ln810_fu_509_p3 <= 
        add_ln811_fu_473_p2 when (and_ln802_1_fu_467_p2(0) = '1') else 
        select_ln802_fu_441_p3;
    select_ln821_1_fu_555_p3 <= 
        ap_const_lv4_1 when (empty_fu_479_p2(0) = '1') else 
        add_ln821_fu_549_p2;
    select_ln821_fu_638_p3 <= 
        add_ln822_fu_632_p2 when (icmp_ln828_mid2121_reg_1397(0) = '1') else 
        ky_mid2114_fu_625_p3;
    select_ln98_fu_1137_p3 <= 
        ap_const_lv8_81 when (icmp_ln98_reg_1629(0) = '1') else 
        ap_const_lv8_7F;
        sext_ln1003_10_fu_965_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_1312_p3),18));

        sext_ln1003_11_fu_974_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln1003_6_fu_968_p2),32));

        sext_ln1003_8_fu_954_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln1003_1_reg_1598),32));

        sext_ln1003_9_fu_962_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln1003_3_reg_1603),18));

        sext_ln1010_1_fu_1028_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_3_fu_1021_p3),44));

        sext_ln1010_2_fu_1044_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_4_fu_1037_p3),44));

        sext_ln1010_fu_1006_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_998_p3),44));

        sext_ln1051_fu_1217_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln37_fu_1209_p3),15));

        sext_ln838_fu_723_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln838_fu_718_p2),10));

        sext_ln855_fu_733_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln838_1_fu_727_p2),16));

    sub_ln1010_1_fu_1032_p2 <= std_logic_vector(unsigned(sub_ln1010_reg_1619) - unsigned(sext_ln1010_1_fu_1028_p1));
    sub_ln1010_fu_1010_p2 <= std_logic_vector(unsigned(p_shl_fu_990_p3) - unsigned(sext_ln1010_fu_1006_p1));
    sub_ln37_fu_1203_p2 <= std_logic_vector(unsigned(ap_const_lv12_0) - unsigned(trunc_ln_fu_1183_p4));
    sub_ln43_fu_1094_p2 <= std_logic_vector(unsigned(ap_const_lv24_0) - unsigned(trunc_ln46_7_fu_1084_p4));
    sub_ln45_1_fu_1178_p2 <= std_logic_vector(unsigned(ap_const_lv32_80000) - unsigned(mul_ln1032_reg_1645));
    sub_ln45_fu_1078_p2 <= std_logic_vector(unsigned(ap_const_lv44_80000) - unsigned(add_ln1010_fu_1048_p2));
        tmp112_cast_fu_679_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp112_fu_673_p2),10));

    tmp112_fu_673_p2 <= std_logic_vector(unsigned(select_ln821_fu_638_p3) + unsigned(ap_const_lv2_3));
    tmp_1_fu_693_p3 <= (trunc_ln855_fu_689_p1 & ap_const_lv8_0);
    tmp_2_fu_998_p3 <= (acc_1_fu_984_p3 & ap_const_lv9_0);
    tmp_3_fu_1021_p3 <= (acc_1_reg_1613 & ap_const_lv6_0);
    tmp_4_fu_1037_p3 <= (acc_1_reg_1613 & ap_const_lv1_0);
    tmp_5_fu_1054_p3 <= add_ln1010_fu_1048_p2(43 downto 43);
    tmp_6_fu_1114_p4 <= residual_q_raw_fu_1100_p3(23 downto 7);
    tmp_7_fu_1166_p3 <= mul_ln1032_reg_1645(31 downto 31);
    tmp_8_fu_1235_p3 <= final_value_fu_1225_p2(14 downto 14);
    tmp_fu_754_p4 <= or_ln843_fu_748_p2(9 downto 8);
    tmp_s_fu_645_p3 <= (trunc_ln811_fu_621_p1 & ap_const_lv8_0);
    trunc_ln1048_fu_1231_p1 <= final_value_fu_1225_p2(14 - 1 downto 0);
    trunc_ln106_fu_1134_p1 <= residual_q_raw_reg_1624(8 - 1 downto 0);
    trunc_ln1078_fu_1257_p1 <= final_value_1_fu_1243_p3(12 - 1 downto 0);
    trunc_ln1_fu_1193_p4 <= add_ln39_1_fu_1173_p2(31 downto 20);
    trunc_ln40_7_fu_1068_p4 <= add_ln39_fu_1062_p2(43 downto 20);
    trunc_ln46_7_fu_1084_p4 <= sub_ln45_fu_1078_p2(43 downto 20);
    trunc_ln811_fu_621_p1 <= select_ln803_fu_614_p3(8 - 1 downto 0);
    trunc_ln855_fu_689_p1 <= empty_49_fu_683_p2(8 - 1 downto 0);
    trunc_ln_fu_1183_p4 <= sub_ln45_1_fu_1178_p2(31 downto 20);
    xor_ln802_fu_449_p2 <= (icmp_ln810_fu_435_p2 xor ap_const_lv1_1);
    zext_ln1051_1_fu_1130_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1051_reg_1418_pp0_iter8_reg),64));
    zext_ln1051_fu_657_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln810_reg_1402),16));
    zext_ln1053_fu_1221_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(baseline_ticks_q0),15));
    zext_ln803_fu_653_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln803_fu_614_p3),10));
    zext_ln810_fu_666_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln810_reg_1402),10));
    zext_ln821_fu_669_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln821_fu_638_p3),4));
    zext_ln828_fu_715_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kx_mid2_reg_1408),4));
    zext_ln855_fu_743_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln855_fu_737_p2),64));
    zext_ln897_fu_776_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln886_fu_770_p2),64));
end behav;
