-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity reconstruction_accel_reconstruction_accel_Pipeline_CONV2_Y_CONV2_X_CONV2_OC_CONV2_KY_CONV2_KX_p_ZLjbC is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 72
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);
 
          address2        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce2             : in std_logic; 
          q2              : out std_logic_vector(DataWidth-1 downto 0);
 
          address3        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce3             : in std_logic; 
          q3              : out std_logic_vector(DataWidth-1 downto 0);
 
          address4        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce4             : in std_logic; 
          q4              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of reconstruction_accel_reconstruction_accel_Pipeline_CONV2_Y_CONV2_X_CONV2_OC_CONV2_KY_CONV2_KX_p_ZLjbC is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address2_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address3_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address4_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00000100", 1 => "00110110", 2 => "00001100", 3 => "11110000", 
    4 => "11011110", 5 => "10011000", 6 => "00110110", 7 => "00100111", 
    8 => "10101000", 9 => "00010001", 10 => "00110001", 11 => "11110111", 
    12 => "11111110", 13 => "00010111", 14 => "01101101", 15 => "00011110", 
    16 => "00001100", 17 => "11001110", 18 => "11011111", 19 => "11110010", 
    20 => "11100000", 21 => "10011011", 22 => "11100110", 23 => "11000000", 
    24 => "11110010", 25 => "11010010", 26 => "11001010", 27 => "00001111", 
    28 => "00010110", 29 => "00101011", 30 => "10000001", 31 => "11101000", 
    32 => "01000000", 33 => "00111100", 34 => "11011101", 35 => "00110101", 
    36 => "11101110", 37 => "10100000", 38 => "11100011", 39 => "00001110", 
    40 => "10000110", 41 => "00101110", 42 => "11010000", 43 => "00100010", 
    44 => "00000010", 45 => "11100110", 46 => "00100111", 47 => "00001100", 
    48 => "11011011", 49 => "11101000", 50 => "11110101", 51 => "11001111", 
    52 => "11101011", 53 => "11110011", 54 => "11001010", 55 => "11110001", 
    56 => "00100111", 57 => "10100000", 58 => "00010100", 59 => "00000011", 
    60 => "11011010", 61 => "01010001", 62 => "11001110", 63 => "00000010", 
    64 => "11000000", 65 => "11010111", 66 => "01111111", 67 => "11101011", 
    68 => "00100011", 69 => "11010000", 70 => "11001110", 71 => "11000000");

signal mem1 : mem_array := (
    0 => "00000100", 1 => "00110110", 2 => "00001100", 3 => "11110000", 
    4 => "11011110", 5 => "10011000", 6 => "00110110", 7 => "00100111", 
    8 => "10101000", 9 => "00010001", 10 => "00110001", 11 => "11110111", 
    12 => "11111110", 13 => "00010111", 14 => "01101101", 15 => "00011110", 
    16 => "00001100", 17 => "11001110", 18 => "11011111", 19 => "11110010", 
    20 => "11100000", 21 => "10011011", 22 => "11100110", 23 => "11000000", 
    24 => "11110010", 25 => "11010010", 26 => "11001010", 27 => "00001111", 
    28 => "00010110", 29 => "00101011", 30 => "10000001", 31 => "11101000", 
    32 => "01000000", 33 => "00111100", 34 => "11011101", 35 => "00110101", 
    36 => "11101110", 37 => "10100000", 38 => "11100011", 39 => "00001110", 
    40 => "10000110", 41 => "00101110", 42 => "11010000", 43 => "00100010", 
    44 => "00000010", 45 => "11100110", 46 => "00100111", 47 => "00001100", 
    48 => "11011011", 49 => "11101000", 50 => "11110101", 51 => "11001111", 
    52 => "11101011", 53 => "11110011", 54 => "11001010", 55 => "11110001", 
    56 => "00100111", 57 => "10100000", 58 => "00010100", 59 => "00000011", 
    60 => "11011010", 61 => "01010001", 62 => "11001110", 63 => "00000010", 
    64 => "11000000", 65 => "11010111", 66 => "01111111", 67 => "11101011", 
    68 => "00100011", 69 => "11010000", 70 => "11001110", 71 => "11000000");

signal mem2 : mem_array := (
    0 => "00000100", 1 => "00110110", 2 => "00001100", 3 => "11110000", 
    4 => "11011110", 5 => "10011000", 6 => "00110110", 7 => "00100111", 
    8 => "10101000", 9 => "00010001", 10 => "00110001", 11 => "11110111", 
    12 => "11111110", 13 => "00010111", 14 => "01101101", 15 => "00011110", 
    16 => "00001100", 17 => "11001110", 18 => "11011111", 19 => "11110010", 
    20 => "11100000", 21 => "10011011", 22 => "11100110", 23 => "11000000", 
    24 => "11110010", 25 => "11010010", 26 => "11001010", 27 => "00001111", 
    28 => "00010110", 29 => "00101011", 30 => "10000001", 31 => "11101000", 
    32 => "01000000", 33 => "00111100", 34 => "11011101", 35 => "00110101", 
    36 => "11101110", 37 => "10100000", 38 => "11100011", 39 => "00001110", 
    40 => "10000110", 41 => "00101110", 42 => "11010000", 43 => "00100010", 
    44 => "00000010", 45 => "11100110", 46 => "00100111", 47 => "00001100", 
    48 => "11011011", 49 => "11101000", 50 => "11110101", 51 => "11001111", 
    52 => "11101011", 53 => "11110011", 54 => "11001010", 55 => "11110001", 
    56 => "00100111", 57 => "10100000", 58 => "00010100", 59 => "00000011", 
    60 => "11011010", 61 => "01010001", 62 => "11001110", 63 => "00000010", 
    64 => "11000000", 65 => "11010111", 66 => "01111111", 67 => "11101011", 
    68 => "00100011", 69 => "11010000", 70 => "11001110", 71 => "11000000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_2: process (address2) 
begin
      address2_tmp <= address2;
--synthesis translate_off
      if (CONV_INTEGER(address2) > AddressRange-1) then
           address2_tmp <= (others => '0');
      else 
           address2_tmp <= address2;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_3: process (address3) 
begin
      address3_tmp <= address3;
--synthesis translate_off
      if (CONV_INTEGER(address3) > AddressRange-1) then
           address3_tmp <= (others => '0');
      else 
           address3_tmp <= address3;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_4: process (address4) 
begin
      address4_tmp <= address4;
--synthesis translate_off
      if (CONV_INTEGER(address4) > AddressRange-1) then
           address4_tmp <= (others => '0');
      else 
           address4_tmp <= address4;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;
 
        if (ce2 = '1') then  
            q2 <= mem1(CONV_INTEGER(address2_tmp)); 
        end if;
 
        if (ce3 = '1') then  
            q3 <= mem1(CONV_INTEGER(address3_tmp)); 
        end if;
 
        if (ce4 = '1') then  
            q4 <= mem2(CONV_INTEGER(address4_tmp)); 
        end if;

end if;
end process;

end rtl;

