-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity reconstruction_accel_reconstruction_accel_Pipeline_CONV2_Y_CONV2_X_CONV2_OC_CONV2_KY_CONV2_KX_p_ZLibs is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 72
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);
 
          address2        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce2             : in std_logic; 
          q2              : out std_logic_vector(DataWidth-1 downto 0);
 
          address3        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce3             : in std_logic; 
          q3              : out std_logic_vector(DataWidth-1 downto 0);
 
          address4        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce4             : in std_logic; 
          q4              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of reconstruction_accel_reconstruction_accel_Pipeline_CONV2_Y_CONV2_X_CONV2_OC_CONV2_KY_CONV2_KX_p_ZLibs is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address2_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address3_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address4_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00101111", 1 => "00111011", 2 => "11100100", 3 => "11011111", 
    4 => "00001111", 5 => "11010111", 6 => "11110001", 7 => "01000110", 
    8 => "01001101", 9 => "00011111", 10 => "00000000", 11 => "00010100", 
    12 => "11110011", 13 => "00000010", 14 => "11101010", 15 => "11011010", 
    16 => "10111000", 17 => "11111110", 18 => "11110101", 19 => "11110011", 
    20 => "11111000", 21 => "10010111", 22 => "00100010", 23 => "11111001", 
    24 => "11000000", 25 => "11001111", 26 => "11000100", 27 => "00001011", 
    28 => "11101001", 29 => "00011101", 30 => "10110011", 31 => "11100110", 
    32 => "11011100", 33 => "10101111", 34 => "11010011", 35 => "00011001", 
    36 => "10110010", 37 => "01011001", 38 => "01001110", 39 => "10010100", 
    40 => "11011111", 41 => "01111101", 42 => "11111010", 43 => "11001111", 
    44 => "11001101", 45 => "00111101", 46 => "11011110", 47 => "11111101", 
    48 => "00000001", 49 => "11111011", 50 => "11101011", 51 => "11011110", 
    52 => "11101001", 53 => "00101000", 54 => "00110110", 55 => "00110001", 
    56 => "11111011", 57 => "11000101", 58 => "00101110", 59 => "11111111", 
    60 => "11011011", 61 => "00000000", 62 => "11100111", 63 => "00000111", 
    64 => "00011111", 65 => "11110111", 66 => "11110110", 67 => "00010000", 
    68 => "11011110", 69 => "11000001", 70 => "11110000", 71 => "00011010");

signal mem1 : mem_array := (
    0 => "00101111", 1 => "00111011", 2 => "11100100", 3 => "11011111", 
    4 => "00001111", 5 => "11010111", 6 => "11110001", 7 => "01000110", 
    8 => "01001101", 9 => "00011111", 10 => "00000000", 11 => "00010100", 
    12 => "11110011", 13 => "00000010", 14 => "11101010", 15 => "11011010", 
    16 => "10111000", 17 => "11111110", 18 => "11110101", 19 => "11110011", 
    20 => "11111000", 21 => "10010111", 22 => "00100010", 23 => "11111001", 
    24 => "11000000", 25 => "11001111", 26 => "11000100", 27 => "00001011", 
    28 => "11101001", 29 => "00011101", 30 => "10110011", 31 => "11100110", 
    32 => "11011100", 33 => "10101111", 34 => "11010011", 35 => "00011001", 
    36 => "10110010", 37 => "01011001", 38 => "01001110", 39 => "10010100", 
    40 => "11011111", 41 => "01111101", 42 => "11111010", 43 => "11001111", 
    44 => "11001101", 45 => "00111101", 46 => "11011110", 47 => "11111101", 
    48 => "00000001", 49 => "11111011", 50 => "11101011", 51 => "11011110", 
    52 => "11101001", 53 => "00101000", 54 => "00110110", 55 => "00110001", 
    56 => "11111011", 57 => "11000101", 58 => "00101110", 59 => "11111111", 
    60 => "11011011", 61 => "00000000", 62 => "11100111", 63 => "00000111", 
    64 => "00011111", 65 => "11110111", 66 => "11110110", 67 => "00010000", 
    68 => "11011110", 69 => "11000001", 70 => "11110000", 71 => "00011010");

signal mem2 : mem_array := (
    0 => "00101111", 1 => "00111011", 2 => "11100100", 3 => "11011111", 
    4 => "00001111", 5 => "11010111", 6 => "11110001", 7 => "01000110", 
    8 => "01001101", 9 => "00011111", 10 => "00000000", 11 => "00010100", 
    12 => "11110011", 13 => "00000010", 14 => "11101010", 15 => "11011010", 
    16 => "10111000", 17 => "11111110", 18 => "11110101", 19 => "11110011", 
    20 => "11111000", 21 => "10010111", 22 => "00100010", 23 => "11111001", 
    24 => "11000000", 25 => "11001111", 26 => "11000100", 27 => "00001011", 
    28 => "11101001", 29 => "00011101", 30 => "10110011", 31 => "11100110", 
    32 => "11011100", 33 => "10101111", 34 => "11010011", 35 => "00011001", 
    36 => "10110010", 37 => "01011001", 38 => "01001110", 39 => "10010100", 
    40 => "11011111", 41 => "01111101", 42 => "11111010", 43 => "11001111", 
    44 => "11001101", 45 => "00111101", 46 => "11011110", 47 => "11111101", 
    48 => "00000001", 49 => "11111011", 50 => "11101011", 51 => "11011110", 
    52 => "11101001", 53 => "00101000", 54 => "00110110", 55 => "00110001", 
    56 => "11111011", 57 => "11000101", 58 => "00101110", 59 => "11111111", 
    60 => "11011011", 61 => "00000000", 62 => "11100111", 63 => "00000111", 
    64 => "00011111", 65 => "11110111", 66 => "11110110", 67 => "00010000", 
    68 => "11011110", 69 => "11000001", 70 => "11110000", 71 => "00011010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_2: process (address2) 
begin
      address2_tmp <= address2;
--synthesis translate_off
      if (CONV_INTEGER(address2) > AddressRange-1) then
           address2_tmp <= (others => '0');
      else 
           address2_tmp <= address2;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_3: process (address3) 
begin
      address3_tmp <= address3;
--synthesis translate_off
      if (CONV_INTEGER(address3) > AddressRange-1) then
           address3_tmp <= (others => '0');
      else 
           address3_tmp <= address3;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_4: process (address4) 
begin
      address4_tmp <= address4;
--synthesis translate_off
      if (CONV_INTEGER(address4) > AddressRange-1) then
           address4_tmp <= (others => '0');
      else 
           address4_tmp <= address4;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;
 
        if (ce2 = '1') then  
            q2 <= mem1(CONV_INTEGER(address2_tmp)); 
        end if;
 
        if (ce3 = '1') then  
            q3 <= mem1(CONV_INTEGER(address3_tmp)); 
        end if;
 
        if (ce4 = '1') then  
            q4 <= mem2(CONV_INTEGER(address4_tmp)); 
        end if;

end if;
end process;

end rtl;

