-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity reconstruction_accel_reconstruction_accel_Pipeline_CONV2_Y_CONV2_X_CONV2_OC_CONV2_KY_CONV2_KX_p_ZLlbW is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 72
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);
 
          address2        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce2             : in std_logic; 
          q2              : out std_logic_vector(DataWidth-1 downto 0);
 
          address3        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce3             : in std_logic; 
          q3              : out std_logic_vector(DataWidth-1 downto 0);
 
          address4        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce4             : in std_logic; 
          q4              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of reconstruction_accel_reconstruction_accel_Pipeline_CONV2_Y_CONV2_X_CONV2_OC_CONV2_KY_CONV2_KX_p_ZLlbW is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address2_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address3_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address4_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11101001", 1 => "11110011", 2 => "11011100", 3 => "00100000", 
    4 => "11111110", 5 => "10101010", 6 => "10111101", 7 => "11100001", 
    8 => "11111010", 9 => "11110011", 10 => "00000010", 11 => "11110100", 
    12 => "11111101", 13 => "11100011", 14 => "10000001", 15 => "11000010", 
    16 => "01001101", 17 => "00001001", 18 => "00011001", 19 => "10001101", 
    20 => "00001111", 21 => "11010100", 22 => "10101101", 23 => "10110100", 
    24 => "11001010", 25 => "00110101", 26 => "11100010", 27 => "11100001", 
    28 => "00011011", 29 => "00001001", 30 => "10111010", 31 => "11011010", 
    32 => "10010000", 33 => "00010000", 34 => "00011111", 35 => "11011010", 
    36 => "10111111", 37 => "01110001", 38 => "11001000", 39 => "11000010", 
    40 => "11000000", 41 => "11000000", 42 => "01010000", 43 => "11101111", 
    44 => "00010000", 45 => "00101001", 46 => "11110111", 47 => "11011101", 
    48 => "00011000", 49 => "00000101", 50 => "00000010", 51 => "11100011", 
    52 => "00110100", 53 => "11010101", 54 => "00001101", 55 => "00011001", 
    56 => "11111110", 57 => "11111000", 58 => "00011110", 59 => "11011100", 
    60 => "11111000", 61 => "11110110", 62 => "11010111", 63 => "00111100", 
    64 => "00100101", 65 => "11111000", 66 => "11111011", 67 => "00001001", 
    68 => "01001101", 69 => "00110110", 70 => "00001111", 71 => "00111011");

signal mem1 : mem_array := (
    0 => "11101001", 1 => "11110011", 2 => "11011100", 3 => "00100000", 
    4 => "11111110", 5 => "10101010", 6 => "10111101", 7 => "11100001", 
    8 => "11111010", 9 => "11110011", 10 => "00000010", 11 => "11110100", 
    12 => "11111101", 13 => "11100011", 14 => "10000001", 15 => "11000010", 
    16 => "01001101", 17 => "00001001", 18 => "00011001", 19 => "10001101", 
    20 => "00001111", 21 => "11010100", 22 => "10101101", 23 => "10110100", 
    24 => "11001010", 25 => "00110101", 26 => "11100010", 27 => "11100001", 
    28 => "00011011", 29 => "00001001", 30 => "10111010", 31 => "11011010", 
    32 => "10010000", 33 => "00010000", 34 => "00011111", 35 => "11011010", 
    36 => "10111111", 37 => "01110001", 38 => "11001000", 39 => "11000010", 
    40 => "11000000", 41 => "11000000", 42 => "01010000", 43 => "11101111", 
    44 => "00010000", 45 => "00101001", 46 => "11110111", 47 => "11011101", 
    48 => "00011000", 49 => "00000101", 50 => "00000010", 51 => "11100011", 
    52 => "00110100", 53 => "11010101", 54 => "00001101", 55 => "00011001", 
    56 => "11111110", 57 => "11111000", 58 => "00011110", 59 => "11011100", 
    60 => "11111000", 61 => "11110110", 62 => "11010111", 63 => "00111100", 
    64 => "00100101", 65 => "11111000", 66 => "11111011", 67 => "00001001", 
    68 => "01001101", 69 => "00110110", 70 => "00001111", 71 => "00111011");

signal mem2 : mem_array := (
    0 => "11101001", 1 => "11110011", 2 => "11011100", 3 => "00100000", 
    4 => "11111110", 5 => "10101010", 6 => "10111101", 7 => "11100001", 
    8 => "11111010", 9 => "11110011", 10 => "00000010", 11 => "11110100", 
    12 => "11111101", 13 => "11100011", 14 => "10000001", 15 => "11000010", 
    16 => "01001101", 17 => "00001001", 18 => "00011001", 19 => "10001101", 
    20 => "00001111", 21 => "11010100", 22 => "10101101", 23 => "10110100", 
    24 => "11001010", 25 => "00110101", 26 => "11100010", 27 => "11100001", 
    28 => "00011011", 29 => "00001001", 30 => "10111010", 31 => "11011010", 
    32 => "10010000", 33 => "00010000", 34 => "00011111", 35 => "11011010", 
    36 => "10111111", 37 => "01110001", 38 => "11001000", 39 => "11000010", 
    40 => "11000000", 41 => "11000000", 42 => "01010000", 43 => "11101111", 
    44 => "00010000", 45 => "00101001", 46 => "11110111", 47 => "11011101", 
    48 => "00011000", 49 => "00000101", 50 => "00000010", 51 => "11100011", 
    52 => "00110100", 53 => "11010101", 54 => "00001101", 55 => "00011001", 
    56 => "11111110", 57 => "11111000", 58 => "00011110", 59 => "11011100", 
    60 => "11111000", 61 => "11110110", 62 => "11010111", 63 => "00111100", 
    64 => "00100101", 65 => "11111000", 66 => "11111011", 67 => "00001001", 
    68 => "01001101", 69 => "00110110", 70 => "00001111", 71 => "00111011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_2: process (address2) 
begin
      address2_tmp <= address2;
--synthesis translate_off
      if (CONV_INTEGER(address2) > AddressRange-1) then
           address2_tmp <= (others => '0');
      else 
           address2_tmp <= address2;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_3: process (address3) 
begin
      address3_tmp <= address3;
--synthesis translate_off
      if (CONV_INTEGER(address3) > AddressRange-1) then
           address3_tmp <= (others => '0');
      else 
           address3_tmp <= address3;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_4: process (address4) 
begin
      address4_tmp <= address4;
--synthesis translate_off
      if (CONV_INTEGER(address4) > AddressRange-1) then
           address4_tmp <= (others => '0');
      else 
           address4_tmp <= address4;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;
 
        if (ce2 = '1') then  
            q2 <= mem1(CONV_INTEGER(address2_tmp)); 
        end if;
 
        if (ce3 = '1') then  
            q3 <= mem1(CONV_INTEGER(address3_tmp)); 
        end if;
 
        if (ce4 = '1') then  
            q4 <= mem2(CONV_INTEGER(address4_tmp)); 
        end if;

end if;
end process;

end rtl;

