-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity reconstruction_accel_reconstruction_accel_Pipeline_CONV2_Y_CONV2_X_CONV2_OC_CONV2_KY_CONV2_KX_p_ZLeOg is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 72
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);
 
          address2        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce2             : in std_logic; 
          q2              : out std_logic_vector(DataWidth-1 downto 0);
 
          address3        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce3             : in std_logic; 
          q3              : out std_logic_vector(DataWidth-1 downto 0);
 
          address4        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce4             : in std_logic; 
          q4              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of reconstruction_accel_reconstruction_accel_Pipeline_CONV2_Y_CONV2_X_CONV2_OC_CONV2_KY_CONV2_KX_p_ZLeOg is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address2_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address3_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address4_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11110100", 1 => "11110111", 2 => "00110001", 3 => "00000001", 
    4 => "00000011", 5 => "00011111", 6 => "00100101", 7 => "11010100", 
    8 => "11111000", 9 => "00000011", 10 => "01001000", 11 => "00110100", 
    12 => "11100101", 13 => "00001101", 14 => "01000100", 15 => "00111101", 
    16 => "11100001", 17 => "01010101", 18 => "11011100", 19 => "00010001", 
    20 => "00110011", 21 => "11110010", 22 => "10101111", 23 => "00001111", 
    24 => "00011101", 25 => "11101111", 26 => "00110110", 27 => "11101111", 
    28 => "11101111", 29 => "11100110", 30 => "11100010", 31 => "10101010", 
    32 => "11111001", 33 => "00001011", 34 => "11111100", 35 => "00000101", 
    36 => "10000100", 37 => "00010111", 38 => "11111111", 39 => "01011100", 
    40 => "11011011", 41 => "10111011", 42 => "11001010", 43 => "01101100", 
    44 => "11001100", 45 => "11101100", 46 => "00111000", 47 => "00010000", 
    48 => "00010011", 49 => "11111101", 50 => "00111110", 51 => "01111111", 
    52 => "11110111", 53 => "01101000", 54 => "00010010", 55 => "11101000", 
    56 => "00010011", 57 => "11011001", 58 => "00000000", 59 => "00001111", 
    60 => "00001110", 61 => "10111000", 62 => "00011100", 63 => "00010111", 
    64 => "11011100", 65 => "11111100", 66 => "00100101", 67 => "00000100", 
    68 => "00000001", 69 => "00000011", 70 => "01100000", 71 => "11011111");

signal mem1 : mem_array := (
    0 => "11110100", 1 => "11110111", 2 => "00110001", 3 => "00000001", 
    4 => "00000011", 5 => "00011111", 6 => "00100101", 7 => "11010100", 
    8 => "11111000", 9 => "00000011", 10 => "01001000", 11 => "00110100", 
    12 => "11100101", 13 => "00001101", 14 => "01000100", 15 => "00111101", 
    16 => "11100001", 17 => "01010101", 18 => "11011100", 19 => "00010001", 
    20 => "00110011", 21 => "11110010", 22 => "10101111", 23 => "00001111", 
    24 => "00011101", 25 => "11101111", 26 => "00110110", 27 => "11101111", 
    28 => "11101111", 29 => "11100110", 30 => "11100010", 31 => "10101010", 
    32 => "11111001", 33 => "00001011", 34 => "11111100", 35 => "00000101", 
    36 => "10000100", 37 => "00010111", 38 => "11111111", 39 => "01011100", 
    40 => "11011011", 41 => "10111011", 42 => "11001010", 43 => "01101100", 
    44 => "11001100", 45 => "11101100", 46 => "00111000", 47 => "00010000", 
    48 => "00010011", 49 => "11111101", 50 => "00111110", 51 => "01111111", 
    52 => "11110111", 53 => "01101000", 54 => "00010010", 55 => "11101000", 
    56 => "00010011", 57 => "11011001", 58 => "00000000", 59 => "00001111", 
    60 => "00001110", 61 => "10111000", 62 => "00011100", 63 => "00010111", 
    64 => "11011100", 65 => "11111100", 66 => "00100101", 67 => "00000100", 
    68 => "00000001", 69 => "00000011", 70 => "01100000", 71 => "11011111");

signal mem2 : mem_array := (
    0 => "11110100", 1 => "11110111", 2 => "00110001", 3 => "00000001", 
    4 => "00000011", 5 => "00011111", 6 => "00100101", 7 => "11010100", 
    8 => "11111000", 9 => "00000011", 10 => "01001000", 11 => "00110100", 
    12 => "11100101", 13 => "00001101", 14 => "01000100", 15 => "00111101", 
    16 => "11100001", 17 => "01010101", 18 => "11011100", 19 => "00010001", 
    20 => "00110011", 21 => "11110010", 22 => "10101111", 23 => "00001111", 
    24 => "00011101", 25 => "11101111", 26 => "00110110", 27 => "11101111", 
    28 => "11101111", 29 => "11100110", 30 => "11100010", 31 => "10101010", 
    32 => "11111001", 33 => "00001011", 34 => "11111100", 35 => "00000101", 
    36 => "10000100", 37 => "00010111", 38 => "11111111", 39 => "01011100", 
    40 => "11011011", 41 => "10111011", 42 => "11001010", 43 => "01101100", 
    44 => "11001100", 45 => "11101100", 46 => "00111000", 47 => "00010000", 
    48 => "00010011", 49 => "11111101", 50 => "00111110", 51 => "01111111", 
    52 => "11110111", 53 => "01101000", 54 => "00010010", 55 => "11101000", 
    56 => "00010011", 57 => "11011001", 58 => "00000000", 59 => "00001111", 
    60 => "00001110", 61 => "10111000", 62 => "00011100", 63 => "00010111", 
    64 => "11011100", 65 => "11111100", 66 => "00100101", 67 => "00000100", 
    68 => "00000001", 69 => "00000011", 70 => "01100000", 71 => "11011111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_2: process (address2) 
begin
      address2_tmp <= address2;
--synthesis translate_off
      if (CONV_INTEGER(address2) > AddressRange-1) then
           address2_tmp <= (others => '0');
      else 
           address2_tmp <= address2;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_3: process (address3) 
begin
      address3_tmp <= address3;
--synthesis translate_off
      if (CONV_INTEGER(address3) > AddressRange-1) then
           address3_tmp <= (others => '0');
      else 
           address3_tmp <= address3;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_4: process (address4) 
begin
      address4_tmp <= address4;
--synthesis translate_off
      if (CONV_INTEGER(address4) > AddressRange-1) then
           address4_tmp <= (others => '0');
      else 
           address4_tmp <= address4;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;
 
        if (ce2 = '1') then  
            q2 <= mem1(CONV_INTEGER(address2_tmp)); 
        end if;
 
        if (ce3 = '1') then  
            q3 <= mem1(CONV_INTEGER(address3_tmp)); 
        end if;
 
        if (ce4 = '1') then  
            q4 <= mem2(CONV_INTEGER(address4_tmp)); 
        end if;

end if;
end process;

end rtl;

