-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity reconstruction_accel_reconstruction_accel_Pipeline_CONV2_Y_CONV2_X_CONV2_OC_CONV2_KY_CONV2_KX_p_ZLkbM is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 72
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);
 
          address2        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce2             : in std_logic; 
          q2              : out std_logic_vector(DataWidth-1 downto 0);
 
          address3        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce3             : in std_logic; 
          q3              : out std_logic_vector(DataWidth-1 downto 0);
 
          address4        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce4             : in std_logic; 
          q4              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of reconstruction_accel_reconstruction_accel_Pipeline_CONV2_Y_CONV2_X_CONV2_OC_CONV2_KY_CONV2_KX_p_ZLkbM is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address2_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address3_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address4_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00100001", 1 => "11011110", 2 => "11111001", 3 => "00101110", 
    4 => "11101110", 5 => "10000001", 6 => "11001101", 7 => "01010010", 
    8 => "11110101", 9 => "11111001", 10 => "00000000", 11 => "11101100", 
    12 => "00000001", 13 => "11111000", 14 => "00111101", 15 => "00001111", 
    16 => "01010111", 17 => "10000111", 18 => "10111101", 19 => "11010100", 
    20 => "11100010", 21 => "11110010", 22 => "00011001", 23 => "11111101", 
    24 => "00001001", 25 => "11000101", 26 => "11111010", 27 => "11111000", 
    28 => "00111000", 29 => "11111001", 30 => "11011010", 31 => "00001110", 
    32 => "00001100", 33 => "01000011", 34 => "00100001", 35 => "11110011", 
    36 => "10011110", 37 => "00101111", 38 => "11100101", 39 => "00100111", 
    40 => "10000001", 41 => "01100000", 42 => "10011100", 43 => "00111111", 
    44 => "11100101", 45 => "11001100", 46 => "00010110", 47 => "00010001", 
    48 => "00010100", 49 => "11011100", 50 => "00110110", 51 => "11111000", 
    52 => "00101000", 53 => "11010011", 54 => "00101000", 55 => "00001100", 
    56 => "00011100", 57 => "11110111", 58 => "11110111", 59 => "10110010", 
    60 => "10110011", 61 => "00111010", 62 => "00010000", 63 => "00011110", 
    64 => "00011000", 65 => "11100001", 66 => "11110101", 67 => "11011010", 
    68 => "00101101", 69 => "11101100", 70 => "11010010", 71 => "00001111");

signal mem1 : mem_array := (
    0 => "00100001", 1 => "11011110", 2 => "11111001", 3 => "00101110", 
    4 => "11101110", 5 => "10000001", 6 => "11001101", 7 => "01010010", 
    8 => "11110101", 9 => "11111001", 10 => "00000000", 11 => "11101100", 
    12 => "00000001", 13 => "11111000", 14 => "00111101", 15 => "00001111", 
    16 => "01010111", 17 => "10000111", 18 => "10111101", 19 => "11010100", 
    20 => "11100010", 21 => "11110010", 22 => "00011001", 23 => "11111101", 
    24 => "00001001", 25 => "11000101", 26 => "11111010", 27 => "11111000", 
    28 => "00111000", 29 => "11111001", 30 => "11011010", 31 => "00001110", 
    32 => "00001100", 33 => "01000011", 34 => "00100001", 35 => "11110011", 
    36 => "10011110", 37 => "00101111", 38 => "11100101", 39 => "00100111", 
    40 => "10000001", 41 => "01100000", 42 => "10011100", 43 => "00111111", 
    44 => "11100101", 45 => "11001100", 46 => "00010110", 47 => "00010001", 
    48 => "00010100", 49 => "11011100", 50 => "00110110", 51 => "11111000", 
    52 => "00101000", 53 => "11010011", 54 => "00101000", 55 => "00001100", 
    56 => "00011100", 57 => "11110111", 58 => "11110111", 59 => "10110010", 
    60 => "10110011", 61 => "00111010", 62 => "00010000", 63 => "00011110", 
    64 => "00011000", 65 => "11100001", 66 => "11110101", 67 => "11011010", 
    68 => "00101101", 69 => "11101100", 70 => "11010010", 71 => "00001111");

signal mem2 : mem_array := (
    0 => "00100001", 1 => "11011110", 2 => "11111001", 3 => "00101110", 
    4 => "11101110", 5 => "10000001", 6 => "11001101", 7 => "01010010", 
    8 => "11110101", 9 => "11111001", 10 => "00000000", 11 => "11101100", 
    12 => "00000001", 13 => "11111000", 14 => "00111101", 15 => "00001111", 
    16 => "01010111", 17 => "10000111", 18 => "10111101", 19 => "11010100", 
    20 => "11100010", 21 => "11110010", 22 => "00011001", 23 => "11111101", 
    24 => "00001001", 25 => "11000101", 26 => "11111010", 27 => "11111000", 
    28 => "00111000", 29 => "11111001", 30 => "11011010", 31 => "00001110", 
    32 => "00001100", 33 => "01000011", 34 => "00100001", 35 => "11110011", 
    36 => "10011110", 37 => "00101111", 38 => "11100101", 39 => "00100111", 
    40 => "10000001", 41 => "01100000", 42 => "10011100", 43 => "00111111", 
    44 => "11100101", 45 => "11001100", 46 => "00010110", 47 => "00010001", 
    48 => "00010100", 49 => "11011100", 50 => "00110110", 51 => "11111000", 
    52 => "00101000", 53 => "11010011", 54 => "00101000", 55 => "00001100", 
    56 => "00011100", 57 => "11110111", 58 => "11110111", 59 => "10110010", 
    60 => "10110011", 61 => "00111010", 62 => "00010000", 63 => "00011110", 
    64 => "00011000", 65 => "11100001", 66 => "11110101", 67 => "11011010", 
    68 => "00101101", 69 => "11101100", 70 => "11010010", 71 => "00001111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_2: process (address2) 
begin
      address2_tmp <= address2;
--synthesis translate_off
      if (CONV_INTEGER(address2) > AddressRange-1) then
           address2_tmp <= (others => '0');
      else 
           address2_tmp <= address2;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_3: process (address3) 
begin
      address3_tmp <= address3;
--synthesis translate_off
      if (CONV_INTEGER(address3) > AddressRange-1) then
           address3_tmp <= (others => '0');
      else 
           address3_tmp <= address3;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_4: process (address4) 
begin
      address4_tmp <= address4;
--synthesis translate_off
      if (CONV_INTEGER(address4) > AddressRange-1) then
           address4_tmp <= (others => '0');
      else 
           address4_tmp <= address4;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;
 
        if (ce2 = '1') then  
            q2 <= mem1(CONV_INTEGER(address2_tmp)); 
        end if;
 
        if (ce3 = '1') then  
            q3 <= mem1(CONV_INTEGER(address3_tmp)); 
        end if;
 
        if (ce4 = '1') then  
            q4 <= mem2(CONV_INTEGER(address4_tmp)); 
        end if;

end if;
end process;

end rtl;

