-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity reconstruction_accel_reconstruction_accel_Pipeline_CONV2_Y_CONV2_X_CONV2_OC_CONV2_KY_CONV2_KX_p_ZLhbi is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 72
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);
 
          address2        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce2             : in std_logic; 
          q2              : out std_logic_vector(DataWidth-1 downto 0);
 
          address3        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce3             : in std_logic; 
          q3              : out std_logic_vector(DataWidth-1 downto 0);
 
          address4        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce4             : in std_logic; 
          q4              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of reconstruction_accel_reconstruction_accel_Pipeline_CONV2_Y_CONV2_X_CONV2_OC_CONV2_KY_CONV2_KX_p_ZLhbi is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address2_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address3_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address4_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11111011", 1 => "11111111", 2 => "11010000", 3 => "11000010", 
    4 => "11011100", 5 => "11010111", 6 => "11111011", 7 => "00101010", 
    8 => "00110011", 9 => "11110000", 10 => "11010111", 11 => "11111110", 
    12 => "11111101", 13 => "00010010", 14 => "11100000", 15 => "00000001", 
    16 => "00001000", 17 => "11110011", 18 => "00011100", 19 => "00001011", 
    20 => "11100110", 21 => "10000001", 22 => "11010000", 23 => "00011110", 
    24 => "11011110", 25 => "11111001", 26 => "11000011", 27 => "11111110", 
    28 => "00001001", 29 => "00001011", 30 => "00111011", 31 => "11011010", 
    32 => "11100111", 33 => "10100110", 34 => "00001100", 35 => "11110110", 
    36 => "01001101", 37 => "10000011", 38 => "11001101", 39 => "10110101", 
    40 => "00000101", 41 => "11001001", 42 => "10101001", 43 => "10000100", 
    44 => "01010101", 45 => "00100110", 46 => "10111010", 47 => "11100011", 
    48 => "00100011", 49 => "01001110", 50 => "00001011", 51 => "00010011", 
    52 => "10101101", 53 => "00001001", 54 => "11100011", 55 => "00010110", 
    56 => "11101100", 57 => "00101011", 58 => "11011001", 59 => "11110100", 
    60 => "00001111", 61 => "11001010", 62 => "00000001", 63 => "00011010", 
    64 => "11011110", 65 => "11101101", 66 => "11010010", 67 => "00111101", 
    68 => "00101000", 69 => "00000111", 70 => "00001101", 71 => "00000100");

signal mem1 : mem_array := (
    0 => "11111011", 1 => "11111111", 2 => "11010000", 3 => "11000010", 
    4 => "11011100", 5 => "11010111", 6 => "11111011", 7 => "00101010", 
    8 => "00110011", 9 => "11110000", 10 => "11010111", 11 => "11111110", 
    12 => "11111101", 13 => "00010010", 14 => "11100000", 15 => "00000001", 
    16 => "00001000", 17 => "11110011", 18 => "00011100", 19 => "00001011", 
    20 => "11100110", 21 => "10000001", 22 => "11010000", 23 => "00011110", 
    24 => "11011110", 25 => "11111001", 26 => "11000011", 27 => "11111110", 
    28 => "00001001", 29 => "00001011", 30 => "00111011", 31 => "11011010", 
    32 => "11100111", 33 => "10100110", 34 => "00001100", 35 => "11110110", 
    36 => "01001101", 37 => "10000011", 38 => "11001101", 39 => "10110101", 
    40 => "00000101", 41 => "11001001", 42 => "10101001", 43 => "10000100", 
    44 => "01010101", 45 => "00100110", 46 => "10111010", 47 => "11100011", 
    48 => "00100011", 49 => "01001110", 50 => "00001011", 51 => "00010011", 
    52 => "10101101", 53 => "00001001", 54 => "11100011", 55 => "00010110", 
    56 => "11101100", 57 => "00101011", 58 => "11011001", 59 => "11110100", 
    60 => "00001111", 61 => "11001010", 62 => "00000001", 63 => "00011010", 
    64 => "11011110", 65 => "11101101", 66 => "11010010", 67 => "00111101", 
    68 => "00101000", 69 => "00000111", 70 => "00001101", 71 => "00000100");

signal mem2 : mem_array := (
    0 => "11111011", 1 => "11111111", 2 => "11010000", 3 => "11000010", 
    4 => "11011100", 5 => "11010111", 6 => "11111011", 7 => "00101010", 
    8 => "00110011", 9 => "11110000", 10 => "11010111", 11 => "11111110", 
    12 => "11111101", 13 => "00010010", 14 => "11100000", 15 => "00000001", 
    16 => "00001000", 17 => "11110011", 18 => "00011100", 19 => "00001011", 
    20 => "11100110", 21 => "10000001", 22 => "11010000", 23 => "00011110", 
    24 => "11011110", 25 => "11111001", 26 => "11000011", 27 => "11111110", 
    28 => "00001001", 29 => "00001011", 30 => "00111011", 31 => "11011010", 
    32 => "11100111", 33 => "10100110", 34 => "00001100", 35 => "11110110", 
    36 => "01001101", 37 => "10000011", 38 => "11001101", 39 => "10110101", 
    40 => "00000101", 41 => "11001001", 42 => "10101001", 43 => "10000100", 
    44 => "01010101", 45 => "00100110", 46 => "10111010", 47 => "11100011", 
    48 => "00100011", 49 => "01001110", 50 => "00001011", 51 => "00010011", 
    52 => "10101101", 53 => "00001001", 54 => "11100011", 55 => "00010110", 
    56 => "11101100", 57 => "00101011", 58 => "11011001", 59 => "11110100", 
    60 => "00001111", 61 => "11001010", 62 => "00000001", 63 => "00011010", 
    64 => "11011110", 65 => "11101101", 66 => "11010010", 67 => "00111101", 
    68 => "00101000", 69 => "00000111", 70 => "00001101", 71 => "00000100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_2: process (address2) 
begin
      address2_tmp <= address2;
--synthesis translate_off
      if (CONV_INTEGER(address2) > AddressRange-1) then
           address2_tmp <= (others => '0');
      else 
           address2_tmp <= address2;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_3: process (address3) 
begin
      address3_tmp <= address3;
--synthesis translate_off
      if (CONV_INTEGER(address3) > AddressRange-1) then
           address3_tmp <= (others => '0');
      else 
           address3_tmp <= address3;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_4: process (address4) 
begin
      address4_tmp <= address4;
--synthesis translate_off
      if (CONV_INTEGER(address4) > AddressRange-1) then
           address4_tmp <= (others => '0');
      else 
           address4_tmp <= address4;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;
 
        if (ce2 = '1') then  
            q2 <= mem1(CONV_INTEGER(address2_tmp)); 
        end if;
 
        if (ce3 = '1') then  
            q3 <= mem1(CONV_INTEGER(address3_tmp)); 
        end if;
 
        if (ce4 = '1') then  
            q4 <= mem2(CONV_INTEGER(address4_tmp)); 
        end if;

end if;
end process;

end rtl;

