-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity reconstruction_accel_partset_64ns_64ns_8ns_6ns_64_1_1 is
generic (
    ADDRWIDTH : INTEGER := 6;
    DATAWIDTH : INTEGER := 64;
    DATA1WIDTH : INTEGER := 8
);
port (

    sel   : in std_logic_vector (ADDRWIDTH-1 downto 0);
    din   : in std_logic_vector (DATAWIDTH-1 downto 0);
    value : in std_logic_vector (DATA1WIDTH-1 downto 0);
    dout  : out std_logic_vector (DATAWIDTH-1 downto 0)
);
end entity;

architecture behav of reconstruction_accel_partset_64ns_64ns_8ns_6ns_64_1_1 is
    signal concatenate : std_logic_vector (DATA1WIDTH-1 downto 0);
    signal din_tmp : std_logic_vector(DATAWIDTH+DATA1WIDTH-1 downto 0);
    signal dout_tmp : std_logic_vector (DATAWIDTH-1 downto 0);



begin
    concatenate <= (others => '0');
    dout_tmp <= din_tmp(DATAWIDTH-1 downto 0);

    process(din,sel,value) is
    begin
        din_tmp <= concatenate & din;
        if to_integer(unsigned(sel)) >= din'low and to_integer(unsigned(sel)) <= din'high then
            din_tmp(to_integer(unsigned(sel))+DATA1WIDTH-1 downto to_integer(unsigned(sel))) <= value;
        end if;
    end process;


    dout <= dout_tmp;






end architecture;
