-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity reconstruction_accel_reconstruction_accel_Pipeline_CONV2_Y_CONV2_X_CONV2_OC_CONV2_KY_CONV2_KX_p_ZLg8j is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 72
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);
 
          address2        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce2             : in std_logic; 
          q2              : out std_logic_vector(DataWidth-1 downto 0);
 
          address3        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce3             : in std_logic; 
          q3              : out std_logic_vector(DataWidth-1 downto 0);
 
          address4        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce4             : in std_logic; 
          q4              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of reconstruction_accel_reconstruction_accel_Pipeline_CONV2_Y_CONV2_X_CONV2_OC_CONV2_KY_CONV2_KX_p_ZLg8j is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address2_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address3_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address4_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00011001", 1 => "00011100", 2 => "11101110", 3 => "11010110", 
    4 => "11010110", 5 => "11110010", 6 => "01010011", 7 => "00111011", 
    8 => "00010010", 9 => "00010100", 10 => "00000100", 11 => "11101110", 
    12 => "00011100", 13 => "00110100", 14 => "10111101", 15 => "10010100", 
    16 => "11010111", 17 => "00001000", 18 => "00101011", 19 => "00101011", 
    20 => "11110111", 21 => "11110001", 22 => "00010110", 23 => "11001011", 
    24 => "00101001", 25 => "00010011", 26 => "11001000", 27 => "00000001", 
    28 => "11111010", 29 => "00101001", 30 => "00100000", 31 => "11111111", 
    32 => "11111001", 33 => "11111011", 34 => "10110000", 35 => "11111111", 
    36 => "01111010", 37 => "01101101", 38 => "10001110", 39 => "00101011", 
    40 => "00001011", 41 => "11011001", 42 => "10100111", 43 => "11101001", 
    44 => "10010110", 45 => "11101000", 46 => "11110100", 47 => "00000111", 
    48 => "11010111", 49 => "11111111", 50 => "11000101", 51 => "10111001", 
    52 => "11001110", 53 => "11001001", 54 => "11010111", 55 => "00010001", 
    56 => "00001011", 57 => "11100100", 58 => "10100111", 59 => "11111110", 
    60 => "10100111", 61 => "00001110", 62 => "11100100", 63 => "11101011", 
    64 => "11001100", 65 => "11010010", 66 => "00011111", 67 => "00010101", 
    68 => "00000011", 69 => "00010101", 70 => "00010001", 71 => "00101011");

signal mem1 : mem_array := (
    0 => "00011001", 1 => "00011100", 2 => "11101110", 3 => "11010110", 
    4 => "11010110", 5 => "11110010", 6 => "01010011", 7 => "00111011", 
    8 => "00010010", 9 => "00010100", 10 => "00000100", 11 => "11101110", 
    12 => "00011100", 13 => "00110100", 14 => "10111101", 15 => "10010100", 
    16 => "11010111", 17 => "00001000", 18 => "00101011", 19 => "00101011", 
    20 => "11110111", 21 => "11110001", 22 => "00010110", 23 => "11001011", 
    24 => "00101001", 25 => "00010011", 26 => "11001000", 27 => "00000001", 
    28 => "11111010", 29 => "00101001", 30 => "00100000", 31 => "11111111", 
    32 => "11111001", 33 => "11111011", 34 => "10110000", 35 => "11111111", 
    36 => "01111010", 37 => "01101101", 38 => "10001110", 39 => "00101011", 
    40 => "00001011", 41 => "11011001", 42 => "10100111", 43 => "11101001", 
    44 => "10010110", 45 => "11101000", 46 => "11110100", 47 => "00000111", 
    48 => "11010111", 49 => "11111111", 50 => "11000101", 51 => "10111001", 
    52 => "11001110", 53 => "11001001", 54 => "11010111", 55 => "00010001", 
    56 => "00001011", 57 => "11100100", 58 => "10100111", 59 => "11111110", 
    60 => "10100111", 61 => "00001110", 62 => "11100100", 63 => "11101011", 
    64 => "11001100", 65 => "11010010", 66 => "00011111", 67 => "00010101", 
    68 => "00000011", 69 => "00010101", 70 => "00010001", 71 => "00101011");

signal mem2 : mem_array := (
    0 => "00011001", 1 => "00011100", 2 => "11101110", 3 => "11010110", 
    4 => "11010110", 5 => "11110010", 6 => "01010011", 7 => "00111011", 
    8 => "00010010", 9 => "00010100", 10 => "00000100", 11 => "11101110", 
    12 => "00011100", 13 => "00110100", 14 => "10111101", 15 => "10010100", 
    16 => "11010111", 17 => "00001000", 18 => "00101011", 19 => "00101011", 
    20 => "11110111", 21 => "11110001", 22 => "00010110", 23 => "11001011", 
    24 => "00101001", 25 => "00010011", 26 => "11001000", 27 => "00000001", 
    28 => "11111010", 29 => "00101001", 30 => "00100000", 31 => "11111111", 
    32 => "11111001", 33 => "11111011", 34 => "10110000", 35 => "11111111", 
    36 => "01111010", 37 => "01101101", 38 => "10001110", 39 => "00101011", 
    40 => "00001011", 41 => "11011001", 42 => "10100111", 43 => "11101001", 
    44 => "10010110", 45 => "11101000", 46 => "11110100", 47 => "00000111", 
    48 => "11010111", 49 => "11111111", 50 => "11000101", 51 => "10111001", 
    52 => "11001110", 53 => "11001001", 54 => "11010111", 55 => "00010001", 
    56 => "00001011", 57 => "11100100", 58 => "10100111", 59 => "11111110", 
    60 => "10100111", 61 => "00001110", 62 => "11100100", 63 => "11101011", 
    64 => "11001100", 65 => "11010010", 66 => "00011111", 67 => "00010101", 
    68 => "00000011", 69 => "00010101", 70 => "00010001", 71 => "00101011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_2: process (address2) 
begin
      address2_tmp <= address2;
--synthesis translate_off
      if (CONV_INTEGER(address2) > AddressRange-1) then
           address2_tmp <= (others => '0');
      else 
           address2_tmp <= address2;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_3: process (address3) 
begin
      address3_tmp <= address3;
--synthesis translate_off
      if (CONV_INTEGER(address3) > AddressRange-1) then
           address3_tmp <= (others => '0');
      else 
           address3_tmp <= address3;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_4: process (address4) 
begin
      address4_tmp <= address4;
--synthesis translate_off
      if (CONV_INTEGER(address4) > AddressRange-1) then
           address4_tmp <= (others => '0');
      else 
           address4_tmp <= address4;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;
 
        if (ce2 = '1') then  
            q2 <= mem1(CONV_INTEGER(address2_tmp)); 
        end if;
 
        if (ce3 = '1') then  
            q3 <= mem1(CONV_INTEGER(address3_tmp)); 
        end if;
 
        if (ce4 = '1') then  
            q4 <= mem2(CONV_INTEGER(address4_tmp)); 
        end if;

end if;
end process;

end rtl;

