// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module reconstruction_accel_reconstruction_accel_Pipeline_CONV1_Y_PAD_CONV1_X_PAD (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        branch_input_address0,
        branch_input_ce0,
        branch_input_q0,
        conv1_out_address0,
        conv1_out_ce0,
        conv1_out_we0,
        conv1_out_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] branch_input_address0;
output   branch_input_ce0;
input  [7:0] branch_input_q0;
output  [15:0] conv1_out_address0;
output   conv1_out_ce0;
output   conv1_out_we0;
output  [63:0] conv1_out_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln361_fu_390_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [7:0] conv1_line0_q0;
wire   [8:0] conv1_line1_address0;
wire   [7:0] conv1_line1_q0;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln363_fu_405_p2;
reg   [0:0] icmp_ln363_reg_2792;
wire   [8:0] select_ln361_fu_411_p3;
reg   [8:0] select_ln361_reg_2797;
reg   [8:0] conv1_line0_addr_reg_2806;
reg   [8:0] conv1_line1_addr_reg_2812;
reg   [8:0] conv1_line1_addr_reg_2812_pp0_iter1_reg;
wire   [0:0] icmp_ln424_fu_435_p2;
reg   [0:0] icmp_ln424_reg_2818;
wire   [0:0] and_ln370_1_fu_564_p2;
reg   [0:0] and_ln370_1_reg_2823;
reg   [7:0] win12_3_reg_2833;
reg   [7:0] win12_3_reg_2833_pp0_iter2_reg;
reg   [7:0] win12_3_reg_2833_pp0_iter3_reg;
reg   [7:0] win12_3_reg_2833_pp0_iter4_reg;
wire   [0:0] icmp_ln397_fu_591_p2;
reg   [0:0] icmp_ln397_reg_2844;
wire   [7:0] win11_fu_596_p3;
reg   [7:0] win11_reg_2852;
reg   [7:0] win11_reg_2852_pp0_iter2_reg;
reg   [7:0] win11_reg_2852_pp0_iter3_reg;
wire   [7:0] win11_2_fu_604_p3;
reg   [7:0] win11_2_reg_2861;
reg   [7:0] win11_2_reg_2861_pp0_iter2_reg;
reg   [7:0] win11_2_reg_2861_pp0_iter3_reg;
reg   [7:0] win11_2_reg_2861_pp0_iter4_reg;
wire   [0:0] and_ln423_fu_612_p2;
reg   [0:0] and_ln423_reg_2872;
reg   [0:0] and_ln423_reg_2872_pp0_iter2_reg;
reg   [0:0] and_ln423_reg_2872_pp0_iter3_reg;
reg   [0:0] and_ln423_reg_2872_pp0_iter4_reg;
reg   [0:0] and_ln423_reg_2872_pp0_iter5_reg;
reg   [0:0] and_ln423_reg_2872_pp0_iter6_reg;
reg   [0:0] and_ln423_reg_2872_pp0_iter7_reg;
reg   [0:0] and_ln423_reg_2872_pp0_iter8_reg;
wire   [15:0] add_ln479_fu_648_p2;
reg   [15:0] add_ln479_reg_2886;
reg   [15:0] add_ln479_reg_2886_pp0_iter2_reg;
reg   [15:0] add_ln479_reg_2886_pp0_iter3_reg;
reg   [15:0] add_ln479_reg_2886_pp0_iter4_reg;
reg   [15:0] add_ln479_reg_2886_pp0_iter5_reg;
reg   [15:0] add_ln479_reg_2886_pp0_iter6_reg;
reg   [15:0] add_ln479_reg_2886_pp0_iter7_reg;
reg   [15:0] add_ln479_reg_2886_pp0_iter8_reg;
wire   [7:0] win22_3_fu_681_p3;
reg   [7:0] win22_3_reg_2891;
reg   [7:0] win22_3_reg_2891_pp0_iter3_reg;
reg   [7:0] win22_3_reg_2891_pp0_iter4_reg;
reg   [7:0] win02_3_reg_2900;
reg   [7:0] win02_3_reg_2900_pp0_iter3_reg;
reg   [7:0] win02_3_reg_2900_pp0_iter4_reg;
wire   [7:0] win21_fu_689_p3;
reg   [7:0] win21_reg_2908;
reg   [7:0] win21_reg_2908_pp0_iter3_reg;
reg   [7:0] win21_reg_2908_pp0_iter4_reg;
wire   [7:0] win21_2_fu_696_p3;
reg   [7:0] win21_2_reg_2918;
reg   [7:0] win21_2_reg_2918_pp0_iter3_reg;
wire   [7:0] win01_fu_703_p3;
reg   [7:0] win01_reg_2928;
reg   [7:0] win01_reg_2928_pp0_iter3_reg;
wire   [7:0] win01_2_fu_710_p3;
reg   [7:0] win01_2_reg_2935;
reg   [7:0] win01_2_reg_2935_pp0_iter3_reg;
wire   [13:0] win01_4_cast139_fu_717_p1;
reg   [13:0] win01_4_cast139_reg_2942;
reg   [13:0] win01_4_cast139_reg_2942_pp0_iter3_reg;
wire   [14:0] win01_4_cast_fu_721_p1;
reg   [14:0] win01_4_cast_reg_2949;
reg   [14:0] win01_4_cast_reg_2949_pp0_iter3_reg;
wire   [14:0] win02_3_cast_fu_729_p1;
reg   [14:0] win02_3_cast_reg_2961;
reg   [14:0] win02_3_cast_reg_2961_pp0_iter3_reg;
wire   [14:0] row_m2_cast150_fu_733_p1;
wire   [15:0] win12_3_cast142_fu_741_p1;
reg   [15:0] win12_3_cast142_reg_2980;
reg   [15:0] win12_3_cast142_reg_2980_pp0_iter3_reg;
wire   [13:0] win12_3_cast_fu_747_p1;
wire   [13:0] win21_4_cast133_fu_757_p1;
wire   [15:0] win22_3_cast140_fu_761_p1;
reg   [15:0] win22_3_cast140_reg_3013;
reg   [15:0] win22_3_cast140_reg_3013_pp0_iter3_reg;
wire   [14:0] zext_ln445_1_fu_769_p1;
reg   [14:0] zext_ln445_1_reg_3024;
reg   [14:0] zext_ln445_1_reg_3024_pp0_iter3_reg;
wire   [15:0] zext_ln447_fu_820_p1;
wire   [15:0] mul_ln452_1_fu_824_p2;
wire   [8:0] tmp_20_fu_841_p3;
reg   [8:0] tmp_20_reg_3043;
wire   [15:0] add_ln452_18_fu_1002_p2;
reg   [15:0] add_ln452_18_reg_3073;
wire   [15:0] zext_ln452_17_fu_1024_p1;
wire  signed [15:0] mul_ln452_17_fu_1098_p2;
wire   [15:0] add_ln452_49_fu_1155_p2;
reg   [15:0] add_ln452_49_reg_3124;
wire  signed [16:0] grp_fu_2489_p3;
wire   [18:0] acc_fu_1325_p2;
reg  signed [18:0] acc_reg_3144;
wire   [17:0] acc_6_fu_1438_p2;
reg  signed [17:0] acc_6_reg_3149;
wire   [16:0] add_ln452_21_fu_1473_p2;
reg  signed [16:0] add_ln452_21_reg_3154;
(* use_dsp48 = "no" *) wire   [16:0] add_ln452_25_fu_1482_p2;
reg  signed [16:0] add_ln452_25_reg_3159;
wire   [16:0] add_ln452_30_fu_1593_p2;
reg  signed [16:0] add_ln452_30_reg_3164;
wire   [16:0] add_ln452_34_fu_1618_p2;
reg  signed [16:0] add_ln452_34_reg_3169;
wire   [16:0] add_ln452_39_fu_1697_p2;
reg  signed [16:0] add_ln452_39_reg_3174;
wire   [16:0] add_ln452_43_fu_1722_p2;
reg  signed [16:0] add_ln452_43_reg_3179;
wire   [17:0] acc_10_fu_1793_p2;
reg  signed [17:0] acc_10_reg_3184;
wire   [7:0] q8_6_fu_1958_p3;
reg   [7:0] q8_6_reg_3209;
reg   [7:0] q8_6_reg_3209_pp0_iter8_reg;
reg   [0:0] tmp_21_reg_3214;
reg   [9:0] trunc_ln5_reg_3219;
reg   [9:0] trunc_ln6_reg_3224;
wire   [7:0] q8_1_fu_2080_p3;
reg   [7:0] q8_1_reg_3229;
wire   [7:0] q8_2_fu_2156_p3;
reg   [7:0] q8_2_reg_3234;
wire   [7:0] q8_3_fu_2232_p3;
reg   [7:0] q8_3_reg_3239;
wire   [7:0] q8_4_fu_2308_p3;
reg   [7:0] q8_4_reg_3244;
wire   [7:0] q8_5_fu_2386_p3;
reg   [7:0] q8_5_reg_3249;
wire   [63:0] zext_ln363_fu_419_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln378_fu_586_p1;
wire   [63:0] zext_ln479_1_fu_2476_p1;
reg   [7:0] win22_fu_246;
wire    ap_loop_init;
reg   [7:0] win21_1_fu_250;
reg   [7:0] win12_fu_254;
reg   [7:0] win11_1_fu_258;
reg   [7:0] win02_fu_262;
reg   [7:0] win01_1_fu_266;
reg   [8:0] px_fu_270;
wire   [8:0] add_ln363_fu_441_p2;
reg   [8:0] ap_sig_allocacmp_px_load;
reg   [8:0] py_fu_274;
wire   [8:0] select_ln361_1_fu_472_p3;
reg   [16:0] indvar_flatten10_fu_278;
wire   [16:0] add_ln361_1_fu_396_p2;
reg   [16:0] ap_sig_allocacmp_indvar_flatten10_load;
reg    conv1_line1_ce0_local;
reg    conv1_line1_we1_local;
reg    conv1_line1_ce1_local;
reg    branch_input_ce0_local;
reg    conv1_line0_ce0_local;
reg    conv1_line0_we1_local;
reg    conv1_line0_ce1_local;
reg    conv1_out_we0_local;
wire   [63:0] packed_fu_2461_p9;
reg    conv1_out_ce0_local;
wire   [7:0] tmp_15_fu_425_p4;
wire   [8:0] add_ln361_fu_466_p2;
wire   [7:0] tmp_fu_495_p4;
wire   [7:0] trunc_ln361_fu_479_p1;
wire   [7:0] empty_fu_511_p2;
wire   [7:0] empty_59_fu_525_p2;
wire   [0:0] cmp57_fu_483_p2;
wire   [0:0] cmp58_fu_489_p2;
wire   [0:0] icmp_ln373_fu_548_p2;
wire   [0:0] icmp_ln375_fu_553_p2;
wire   [0:0] and_ln370_fu_558_p2;
wire   [0:0] brmerge_not_fu_539_p2;
wire   [9:0] zext_ln363_1_fu_545_p1;
wire   [9:0] add_ln381_fu_570_p2;
wire   [15:0] tmp_8_fu_517_p3;
wire  signed [15:0] sext_ln378_fu_576_p1;
wire   [15:0] add_ln378_fu_580_p2;
wire   [0:0] icmp227_fu_505_p2;
wire   [8:0] win11_4_cast152_fu_617_p1;
wire   [8:0] row_m1_cast153_fu_621_p1;
wire  signed [8:0] tmp3_fu_629_p2;
wire   [8:0] add_ln482_fu_639_p2;
wire   [15:0] tmp_9_fu_531_p3;
wire   [15:0] zext_ln479_fu_644_p1;
wire   [14:0] p_shl4_fu_808_p3;
wire   [14:0] sub_ln445_fu_815_p2;
wire   [7:0] mul_ln452_1_fu_824_p0;
wire  signed [7:0] mul_ln452_1_fu_824_p1;
wire   [10:0] tmp_19_fu_830_p3;
wire   [11:0] zext_ln452_43_fu_848_p1;
wire   [11:0] zext_ln452_42_fu_837_p1;
wire   [11:0] sub_ln452_1_fu_852_p2;
wire  signed [14:0] sext_ln452_fu_858_p1;
wire   [7:0] mul_ln452_6_fu_868_p0;
wire   [14:0] win22_3_cast126_fu_805_p1;
wire   [7:0] mul_ln452_6_fu_868_p1;
wire   [14:0] mul_ln452_6_fu_868_p2;
wire   [13:0] tmp_24_fu_878_p3;
wire   [15:0] zext_ln452_44_fu_885_p1;
wire   [10:0] tmp_25_fu_895_p3;
wire   [15:0] sub_ln452_2_fu_889_p2;
wire   [15:0] zext_ln452_45_fu_902_p1;
wire   [9:0] tmp_31_fu_912_p3;
wire   [10:0] win02_3_cast131_fu_793_p1;
wire   [10:0] zext_ln452_49_fu_919_p1;
wire   [10:0] sub_ln452_6_fu_923_p2;
wire   [13:0] tmp_32_fu_933_p3;
wire   [14:0] zext_ln452_50_fu_940_p1;
wire   [14:0] sub_ln452_7_fu_944_p2;
wire   [11:0] tmp_33_fu_953_p3;
wire   [12:0] win22_3_cast132_fu_802_p1;
wire   [12:0] zext_ln452_51_fu_960_p1;
wire  signed [12:0] sub_ln452_8_fu_964_p2;
wire   [13:0] tmp_34_fu_974_p3;
wire   [8:0] tmp_35_fu_985_p3;
wire   [14:0] zext_ln452_53_fu_992_p1;
wire   [14:0] zext_ln452_52_fu_981_p1;
wire  signed [15:0] sext_ln452_12_fu_949_p1;
wire  signed [15:0] sext_ln452_11_fu_929_p1;
wire  signed [15:0] grp_fu_2480_p3;
wire   [14:0] p_shl8_fu_1011_p3;
wire   [14:0] sub_ln451_fu_1018_p2;
wire   [9:0] shl_ln_fu_1028_p3;
wire   [11:0] p_shl9_fu_1039_p3;
wire   [11:0] win21_4_cast136_fu_796_p1;
wire   [11:0] sub_ln452_11_fu_1046_p2;
wire   [11:0] tmp_44_fu_1056_p3;
wire   [13:0] zext_ln452_59_fu_1063_p1;
wire   [13:0] sub_ln452_17_fu_1067_p2;
wire  signed [13:0] sub_ln452_18_fu_1073_p2;
wire   [14:0] p_shl10_fu_1082_p3;
wire   [14:0] sub_ln452_19_fu_1089_p2;
wire   [7:0] mul_ln452_17_fu_1098_p0;
wire  signed [7:0] mul_ln452_17_fu_1098_p1;
wire   [7:0] mul_ln452_19_fu_1103_p0;
wire   [7:0] mul_ln452_19_fu_1103_p1;
wire   [14:0] mul_ln452_19_fu_1103_p2;
wire   [8:0] tmp_49_fu_1119_p3;
wire   [10:0] p_shl11_fu_1112_p3;
wire   [10:0] zext_ln452_63_fu_1126_p1;
wire   [10:0] sub_ln452_22_fu_1130_p2;
wire   [15:0] zext_ln452_64_fu_1140_p1;
wire   [15:0] sub_ln452_23_fu_1144_p2;
wire   [15:0] zext_ln452_32_fu_1136_p1;
wire   [7:0] mul_ln452_23_fu_1161_p0;
wire  signed [5:0] mul_ln452_23_fu_1161_p1;
wire  signed [13:0] mul_ln452_23_fu_1161_p2;
wire   [13:0] zext_ln452_67_fu_1170_p1;
wire   [9:0] tmp_53_fu_1180_p3;
wire   [13:0] sub_ln452_24_fu_1174_p2;
wire   [13:0] zext_ln452_68_fu_1187_p1;
wire  signed [13:0] sub_ln452_25_fu_1191_p2;
wire   [7:0] mul_ln447_fu_1210_p0;
wire   [14:0] win11_4_cast_fu_1207_p1;
wire   [7:0] mul_ln447_fu_1210_p1;
wire   [14:0] mul_ln447_fu_1210_p2;
wire   [13:0] tmp_16_fu_1224_p3;
wire   [11:0] tmp_17_fu_1235_p3;
wire   [14:0] zext_ln452_39_fu_1231_p1;
wire   [14:0] zext_ln452_40_fu_1242_p1;
wire   [14:0] add_ln452_8_fu_1246_p2;
wire   [9:0] tmp_18_fu_1263_p3;
wire   [13:0] p_shl5_fu_1256_p3;
wire   [13:0] zext_ln452_41_fu_1270_p1;
wire   [13:0] sub_ln452_fu_1274_p2;
wire   [15:0] grp_fu_2497_p3;
wire   [15:0] grp_fu_2506_p3;
wire   [15:0] zext_ln452_1_fu_1220_p1;
(* use_dsp48 = "no" *) wire   [15:0] add_ln452_2_fu_1287_p2;
wire  signed [17:0] sext_ln452_1_fu_1292_p1;
wire   [17:0] zext_ln452_6_fu_1284_p1;
wire   [17:0] add_ln452_3_fu_1296_p2;
wire   [15:0] zext_ln452_4_fu_1280_p1;
wire   [15:0] zext_ln452_3_fu_1252_p1;
wire  signed [14:0] zext_ln452_7_fu_1312_p0;
wire   [14:0] grp_fu_2515_p3;
wire   [15:0] zext_ln452_7_fu_1312_p1;
wire   [15:0] add_ln452_4_fu_1306_p2;
wire   [15:0] add_ln452_7_fu_1315_p2;
wire   [18:0] zext_ln452_8_fu_1321_p1;
wire  signed [18:0] sext_ln452_2_fu_1302_p1;
wire   [10:0] tmp_26_fu_1331_p3;
wire   [8:0] tmp_27_fu_1342_p3;
wire   [11:0] zext_ln452_47_fu_1349_p1;
wire   [11:0] zext_ln452_46_fu_1338_p1;
wire   [11:0] sub_ln452_4_fu_1353_p2;
wire   [12:0] tmp_28_fu_1370_p3;
wire   [14:0] p_shl6_fu_1363_p3;
wire   [14:0] zext_ln452_48_fu_1377_p1;
wire  signed [15:0] grp_fu_2524_p3;
wire   [15:0] sext_ln452_6_fu_1390_p0;
wire  signed [15:0] grp_fu_2542_p3;
wire  signed [16:0] sext_ln452_6_fu_1390_p1;
wire   [16:0] zext_ln452_fu_1216_p1;
wire   [16:0] add_ln452_11_fu_1393_p2;
wire  signed [17:0] sext_ln452_7_fu_1399_p1;
wire  signed [17:0] sext_ln452_5_fu_1387_p1;
wire   [15:0] grp_fu_2533_p3;
wire   [14:0] sub_ln452_5_fu_1381_p2;
wire   [14:0] add_ln452_14_fu_1412_p2;
wire  signed [14:0] sext_ln452_4_fu_1359_p1;
wire   [14:0] add_ln452_15_fu_1418_p2;
wire  signed [16:0] sext_ln452_8_fu_1424_p1;
wire   [16:0] zext_ln452_12_fu_1409_p1;
wire   [16:0] add_ln452_16_fu_1428_p2;
wire  signed [17:0] sext_ln452_9_fu_1434_p1;
wire   [17:0] add_ln452_12_fu_1403_p2;
wire   [14:0] p_shl7_fu_1444_p3;
wire   [14:0] sub_ln452_10_fu_1451_p2;
wire   [14:0] sext_ln452_15_fu_1464_p0;
wire  signed [14:0] grp_fu_2569_p3;
wire  signed [16:0] sext_ln452_15_fu_1464_p1;
wire   [16:0] zext_ln452_16_fu_1457_p1;
wire   [16:0] add_ln452_20_fu_1467_p2;
wire  signed [16:0] sext_ln452_14_fu_1461_p1;
wire  signed [15:0] grp_fu_2560_p3;
wire  signed [16:0] grp_fu_2551_p3;
wire  signed [16:0] sext_ln452_17_fu_1479_p1;
wire   [9:0] tmp_38_fu_1493_p3;
wire   [14:0] sub_ln452_12_fu_1487_p2;
wire   [14:0] zext_ln452_54_fu_1500_p1;
wire   [14:0] sub_ln452_13_fu_1504_p2;
wire   [13:0] tmp_39_fu_1514_p3;
wire   [10:0] tmp_40_fu_1525_p3;
wire   [14:0] zext_ln452_56_fu_1532_p1;
wire   [14:0] zext_ln452_55_fu_1521_p1;
wire   [14:0] sub_ln452_14_fu_1536_p2;
wire   [11:0] tmp_41_fu_1546_p3;
wire   [13:0] zext_ln452_57_fu_1553_p1;
wire   [13:0] sub_ln452_15_fu_1557_p2;
wire   [13:0] zext_ln452_58_fu_1563_p1;
wire   [13:0] sub_ln452_16_fu_1567_p2;
wire   [14:0] grp_fu_2596_p3;
wire   [14:0] grp_fu_2587_p3;
wire   [15:0] zext_ln452_23_fu_1580_p1;
wire  signed [15:0] sext_ln452_21_fu_1542_p1;
wire   [15:0] add_ln452_29_fu_1583_p2;
wire  signed [16:0] sext_ln452_23_fu_1589_p1;
wire   [16:0] zext_ln452_22_fu_1577_p1;
wire   [15:0] grp_fu_2578_p3;
wire  signed [15:0] sext_ln452_20_fu_1510_p1;
wire   [15:0] add_ln452_32_fu_1602_p2;
wire  signed [15:0] sext_ln452_22_fu_1573_p1;
wire   [15:0] add_ln452_33_fu_1608_p2;
wire  signed [16:0] sext_ln452_25_fu_1614_p1;
wire   [16:0] zext_ln452_24_fu_1599_p1;
wire   [7:0] mul_ln446_fu_1624_p0;
wire   [6:0] mul_ln446_fu_1624_p1;
wire   [13:0] mul_ln446_fu_1624_p2;
wire   [13:0] tmp_45_fu_1638_p3;
wire   [14:0] zext_ln452_60_fu_1645_p1;
wire   [14:0] sub_ln452_20_fu_1649_p2;
wire   [14:0] zext_ln452_61_fu_1655_p1;
wire   [12:0] tmp_46_fu_1664_p3;
wire   [13:0] zext_ln452_62_fu_1671_p1;
wire   [13:0] win11_4_cast143_fu_1204_p1;
wire   [13:0] add_ln452_53_fu_1675_p2;
wire  signed [15:0] grp_fu_2623_p3;
wire  signed [15:0] grp_fu_2614_p3;
wire   [15:0] zext_ln452_28_fu_1681_p1;
(* use_dsp48 = "no" *) wire   [15:0] add_ln452_38_fu_1688_p2;
wire  signed [16:0] sext_ln452_30_fu_1693_p1;
wire  signed [16:0] sext_ln452_29_fu_1685_p1;
wire  signed [15:0] grp_fu_2605_p3;
wire   [14:0] sub_ln452_21_fu_1658_p2;
wire   [14:0] add_ln452_41_fu_1706_p2;
wire   [14:0] zext_ln452_26_fu_1634_p1;
wire   [14:0] add_ln452_42_fu_1712_p2;
wire  signed [16:0] sext_ln452_33_fu_1718_p1;
wire  signed [16:0] sext_ln452_32_fu_1703_p1;
wire   [8:0] tmp_50_fu_1732_p3;
wire   [11:0] zext_ln452_65_fu_1728_p1;
wire   [11:0] zext_ln452_66_fu_1739_p1;
wire   [11:0] add_ln452_63_fu_1743_p2;
wire   [14:0] grp_fu_2641_p3;
wire   [14:0] zext_ln452_34_fu_1749_p1;
(* use_dsp48 = "no" *) wire   [14:0] add_ln452_47_fu_1753_p2;
wire   [15:0] zext_ln452_35_fu_1758_p1;
wire   [15:0] grp_fu_2632_p3;
(* use_dsp48 = "no" *) wire   [15:0] add_ln452_48_fu_1762_p2;
wire  signed [15:0] add_ln452_51_fu_1774_p0;
wire   [15:0] grp_fu_2650_p3;
wire   [15:0] zext_ln452_25_fu_1630_p1;
(* use_dsp48 = "no" *) wire   [15:0] add_ln452_51_fu_1774_p2;
wire  signed [16:0] sext_ln452_36_fu_1779_p1;
wire  signed [16:0] sext_ln452_35_fu_1771_p1;
wire   [16:0] add_ln452_52_fu_1783_p2;
wire  signed [17:0] sext_ln452_37_fu_1789_p1;
wire   [17:0] zext_ln452_36_fu_1767_p1;
wire  signed [14:0] grp_fu_2686_p3;
wire  signed [15:0] grp_fu_2668_p3;
wire  signed [16:0] sext_ln452_42_fu_1802_p1;
wire  signed [16:0] sext_ln452_41_fu_1799_p1;
wire   [16:0] add_ln452_56_fu_1805_p2;
wire   [15:0] grp_fu_2659_p3;
wire  signed [16:0] grp_fu_2677_p3;
wire  signed [17:0] sext_ln452_44_fu_1818_p1;
wire   [17:0] zext_ln452_38_fu_1815_p1;
wire   [17:0] add_ln452_60_fu_1821_p2;
wire  signed [17:0] sext_ln452_43_fu_1811_p1;
wire  signed [17:0] acc_11_fu_1827_p2;
wire   [12:0] grp_fu_1837_p1;
wire   [12:0] grp_fu_1846_p1;
wire   [11:0] grp_fu_1855_p1;
wire   [12:0] grp_fu_1882_p1;
wire   [30:0] grp_fu_1837_p2;
wire   [28:0] trunc_ln462_6_fu_1888_p1;
wire   [28:0] add_ln39_6_fu_1900_p2;
wire   [28:0] sub_ln45_6_fu_1916_p2;
wire   [8:0] trunc_ln46_6_fu_1922_p4;
wire   [0:0] tmp_54_fu_1892_p3;
wire   [8:0] sub_ln43_6_fu_1932_p2;
wire   [8:0] trunc_ln40_6_fu_1906_p4;
wire   [8:0] q_6_fu_1938_p3;
wire   [0:0] tmp_55_fu_1946_p3;
wire   [7:0] trunc_ln91_6_fu_1954_p1;
wire   [31:0] grp_fu_1846_p2;
wire   [29:0] trunc_ln462_fu_1966_p1;
wire   [29:0] add_ln39_fu_1978_p2;
wire   [29:0] sub_ln45_fu_1994_p2;
wire   [29:0] grp_fu_1855_p2;
wire   [28:0] trunc_ln462_1_fu_2010_p1;
wire   [28:0] add_ln39_1_fu_2022_p2;
wire   [28:0] sub_ln45_1_fu_2038_p2;
wire   [8:0] trunc_ln46_1_fu_2044_p4;
wire   [0:0] tmp_29_fu_2014_p3;
wire   [8:0] sub_ln43_1_fu_2054_p2;
wire   [8:0] trunc_ln40_1_fu_2028_p4;
wire   [8:0] q_1_fu_2060_p3;
wire   [0:0] tmp_30_fu_2068_p3;
wire   [7:0] trunc_ln91_1_fu_2076_p1;
wire  signed [30:0] grp_fu_2695_p3;
wire   [28:0] trunc_ln462_2_fu_2088_p1;
wire   [28:0] add_ln39_2_fu_2098_p2;
wire   [28:0] sub_ln45_2_fu_2114_p2;
wire   [8:0] trunc_ln46_2_fu_2120_p4;
wire   [0:0] tmp_36_fu_2091_p3;
wire   [8:0] sub_ln43_2_fu_2130_p2;
wire   [8:0] trunc_ln40_2_fu_2104_p4;
wire   [8:0] q_2_fu_2136_p3;
wire   [0:0] tmp_37_fu_2144_p3;
wire   [7:0] trunc_ln91_2_fu_2152_p1;
wire  signed [30:0] grp_fu_2705_p3;
wire   [28:0] trunc_ln462_3_fu_2164_p1;
wire   [28:0] add_ln39_3_fu_2174_p2;
wire   [28:0] sub_ln45_3_fu_2190_p2;
wire   [8:0] trunc_ln46_3_fu_2196_p4;
wire   [0:0] tmp_42_fu_2167_p3;
wire   [8:0] sub_ln43_3_fu_2206_p2;
wire   [8:0] trunc_ln40_3_fu_2180_p4;
wire   [8:0] q_3_fu_2212_p3;
wire   [0:0] tmp_43_fu_2220_p3;
wire   [7:0] trunc_ln91_3_fu_2228_p1;
wire  signed [30:0] grp_fu_2715_p3;
wire   [28:0] trunc_ln462_4_fu_2240_p1;
wire   [28:0] add_ln39_4_fu_2250_p2;
wire   [28:0] sub_ln45_4_fu_2266_p2;
wire   [8:0] trunc_ln46_4_fu_2272_p4;
wire   [0:0] tmp_47_fu_2243_p3;
wire   [8:0] sub_ln43_4_fu_2282_p2;
wire   [8:0] trunc_ln40_4_fu_2256_p4;
wire   [8:0] q_4_fu_2288_p3;
wire   [0:0] tmp_48_fu_2296_p3;
wire   [7:0] trunc_ln91_4_fu_2304_p1;
wire   [30:0] grp_fu_1882_p2;
wire   [28:0] trunc_ln462_5_fu_2316_p1;
wire   [28:0] add_ln39_5_fu_2328_p2;
wire   [28:0] sub_ln45_5_fu_2344_p2;
wire   [8:0] trunc_ln46_5_fu_2350_p4;
wire   [0:0] tmp_51_fu_2320_p3;
wire   [8:0] sub_ln43_5_fu_2360_p2;
wire   [8:0] trunc_ln40_5_fu_2334_p4;
wire   [8:0] q_5_fu_2366_p3;
wire   [0:0] tmp_52_fu_2374_p3;
wire   [7:0] trunc_ln91_5_fu_2382_p1;
wire   [9:0] sub_ln43_fu_2394_p2;
wire   [9:0] q_fu_2399_p3;
wire   [1:0] tmp_23_fu_2413_p4;
wire   [0:0] tmp_22_fu_2405_p3;
wire   [0:0] xor_ln83_fu_2433_p2;
wire   [0:0] icmp_ln87_fu_2423_p2;
wire   [0:0] or_ln83_fu_2447_p2;
wire   [7:0] select_ln83_fu_2439_p3;
wire   [7:0] trunc_ln91_fu_2429_p1;
wire   [7:0] q8_fu_2453_p3;
wire   [7:0] grp_fu_2480_p0;
wire   [6:0] grp_fu_2480_p1;
wire   [6:0] grp_fu_2489_p1;
wire   [13:0] grp_fu_2489_p2;
wire   [7:0] grp_fu_2497_p0;
wire   [6:0] grp_fu_2497_p1;
wire   [14:0] grp_fu_2497_p2;
wire   [7:0] grp_fu_2506_p0;
wire   [5:0] grp_fu_2506_p1;
wire   [7:0] grp_fu_2515_p0;
wire  signed [7:0] grp_fu_2515_p1;
wire  signed [14:0] grp_fu_2515_p2;
wire   [7:0] grp_fu_2524_p0;
wire  signed [6:0] grp_fu_2524_p1;
wire   [14:0] grp_fu_2524_p2;
wire   [7:0] grp_fu_2533_p0;
wire   [5:0] grp_fu_2533_p1;
wire   [14:0] grp_fu_2533_p2;
wire   [7:0] grp_fu_2542_p0;
wire   [6:0] grp_fu_2542_p1;
wire   [15:0] grp_fu_2542_p2;
wire   [7:0] grp_fu_2551_p0;
wire  signed [7:0] grp_fu_2551_p1;
wire   [7:0] grp_fu_2560_p0;
wire   [6:0] grp_fu_2560_p1;
wire   [7:0] grp_fu_2569_p0;
wire   [5:0] grp_fu_2569_p1;
wire   [14:0] grp_fu_2569_p2;
wire   [7:0] grp_fu_2578_p0;
wire   [6:0] grp_fu_2578_p1;
wire   [14:0] grp_fu_2578_p2;
wire   [7:0] grp_fu_2587_p0;
wire   [5:0] grp_fu_2587_p1;
wire   [11:0] grp_fu_2587_p2;
wire   [7:0] grp_fu_2596_p0;
wire   [6:0] grp_fu_2596_p1;
wire   [9:0] grp_fu_2596_p2;
wire   [7:0] grp_fu_2605_p0;
wire  signed [7:0] grp_fu_2605_p1;
wire   [14:0] grp_fu_2605_p2;
wire   [7:0] grp_fu_2614_p0;
wire  signed [5:0] grp_fu_2614_p1;
wire   [7:0] grp_fu_2623_p0;
wire   [6:0] grp_fu_2623_p1;
wire   [7:0] grp_fu_2632_p0;
wire   [5:0] grp_fu_2632_p1;
wire   [14:0] grp_fu_2632_p2;
wire   [7:0] grp_fu_2641_p0;
wire   [4:0] grp_fu_2641_p1;
wire   [14:0] grp_fu_2641_p2;
wire   [7:0] grp_fu_2650_p0;
wire  signed [7:0] grp_fu_2650_p1;
wire   [11:0] grp_fu_2650_p2;
wire   [7:0] grp_fu_2659_p0;
wire   [6:0] grp_fu_2659_p1;
wire   [14:0] grp_fu_2659_p2;
wire   [7:0] grp_fu_2668_p0;
wire  signed [7:0] grp_fu_2668_p1;
wire   [7:0] grp_fu_2677_p0;
wire  signed [6:0] grp_fu_2677_p1;
wire   [7:0] grp_fu_2686_p0;
wire  signed [5:0] grp_fu_2686_p1;
wire   [11:0] grp_fu_2695_p2;
wire   [11:0] grp_fu_2705_p2;
wire   [11:0] grp_fu_2715_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [14:0] grp_fu_2480_p00;
wire   [13:0] grp_fu_2533_p00;
wire   [15:0] grp_fu_2533_p20;
wire   [14:0] grp_fu_2542_p00;
wire   [15:0] grp_fu_2551_p00;
wire   [14:0] grp_fu_2587_p20;
wire   [14:0] grp_fu_2596_p20;
wire   [15:0] grp_fu_2605_p00;
wire   [15:0] grp_fu_2605_p20;
wire   [13:0] grp_fu_2632_p00;
wire   [15:0] grp_fu_2632_p20;
wire   [12:0] grp_fu_2641_p00;
wire   [15:0] grp_fu_2650_p00;
wire   [15:0] grp_fu_2668_p00;
wire   [13:0] grp_fu_2686_p00;
wire   [13:0] mul_ln446_fu_1624_p00;
wire   [15:0] mul_ln452_1_fu_824_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 win22_fu_246 = 8'd0;
#0 win21_1_fu_250 = 8'd0;
#0 win12_fu_254 = 8'd0;
#0 win11_1_fu_258 = 8'd0;
#0 win02_fu_262 = 8'd0;
#0 win01_1_fu_266 = 8'd0;
#0 px_fu_270 = 9'd0;
#0 py_fu_274 = 9'd0;
#0 indvar_flatten10_fu_278 = 17'd0;
#0 ap_done_reg = 1'b0;
end

reconstruction_accel_reconstruction_accel_Pipeline_CONV1_Y_PAD_CONV1_X_PAD_conv1_line0_RAM_S2P_BRAbkb #(
    .DataWidth( 8 ),
    .AddressRange( 258 ),
    .AddressWidth( 9 ))
conv1_line0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv1_line0_addr_reg_2806),
    .ce0(conv1_line0_ce0_local),
    .q0(conv1_line0_q0),
    .address1(conv1_line0_addr_reg_2806),
    .ce1(conv1_line0_ce1_local),
    .we1(conv1_line0_we1_local),
    .d1(conv1_line1_q0)
);

reconstruction_accel_reconstruction_accel_Pipeline_CONV1_Y_PAD_CONV1_X_PAD_conv1_line0_RAM_S2P_BRAbkb #(
    .DataWidth( 8 ),
    .AddressRange( 258 ),
    .AddressWidth( 9 ))
conv1_line1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv1_line1_address0),
    .ce0(conv1_line1_ce0_local),
    .q0(conv1_line1_q0),
    .address1(conv1_line1_addr_reg_2812_pp0_iter1_reg),
    .ce1(conv1_line1_ce1_local),
    .we1(conv1_line1_we1_local),
    .d1(win22_3_fu_681_p3)
);

reconstruction_accel_mul_8ns_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8s_16_1_1_U23(
    .din0(mul_ln452_1_fu_824_p0),
    .din1(mul_ln452_1_fu_824_p1),
    .dout(mul_ln452_1_fu_824_p2)
);

reconstruction_accel_mul_8ns_8ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mul_8ns_8ns_15_1_1_U24(
    .din0(mul_ln452_6_fu_868_p0),
    .din1(mul_ln452_6_fu_868_p1),
    .dout(mul_ln452_6_fu_868_p2)
);

reconstruction_accel_mul_8ns_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8s_16_1_1_U25(
    .din0(mul_ln452_17_fu_1098_p0),
    .din1(mul_ln452_17_fu_1098_p1),
    .dout(mul_ln452_17_fu_1098_p2)
);

reconstruction_accel_mul_8ns_8ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mul_8ns_8ns_15_1_1_U26(
    .din0(mul_ln452_19_fu_1103_p0),
    .din1(mul_ln452_19_fu_1103_p1),
    .dout(mul_ln452_19_fu_1103_p2)
);

reconstruction_accel_mul_8ns_6s_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_8ns_6s_14_1_1_U27(
    .din0(mul_ln452_23_fu_1161_p0),
    .din1(mul_ln452_23_fu_1161_p1),
    .dout(mul_ln452_23_fu_1161_p2)
);

reconstruction_accel_mul_8ns_8ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mul_8ns_8ns_15_1_1_U28(
    .din0(mul_ln447_fu_1210_p0),
    .din1(mul_ln447_fu_1210_p1),
    .dout(mul_ln447_fu_1210_p2)
);

reconstruction_accel_mul_8ns_7ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 14 ))
mul_8ns_7ns_14_1_1_U29(
    .din0(mul_ln446_fu_1624_p0),
    .din1(mul_ln446_fu_1624_p1),
    .dout(mul_ln446_fu_1624_p2)
);

reconstruction_accel_mul_18s_13ns_31_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 31 ))
mul_18s_13ns_31_3_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(acc_11_fu_1827_p2),
    .din1(grp_fu_1837_p1),
    .ce(1'b1),
    .dout(grp_fu_1837_p2)
);

reconstruction_accel_mul_19s_13ns_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 19 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 32 ))
mul_19s_13ns_32_3_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(acc_reg_3144),
    .din1(grp_fu_1846_p1),
    .ce(1'b1),
    .dout(grp_fu_1846_p2)
);

reconstruction_accel_mul_18s_12ns_30_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 30 ))
mul_18s_12ns_30_3_1_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(acc_6_reg_3149),
    .din1(grp_fu_1855_p1),
    .ce(1'b1),
    .dout(grp_fu_1855_p2)
);

reconstruction_accel_mul_18s_13ns_31_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 31 ))
mul_18s_13ns_31_3_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(acc_10_reg_3184),
    .din1(grp_fu_1882_p1),
    .ce(1'b1),
    .dout(grp_fu_1882_p2)
);

reconstruction_accel_mac_muladd_8ns_7ns_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_7ns_16s_16_4_1_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2480_p0),
    .din1(grp_fu_2480_p1),
    .din2(16'd48838),
    .ce(1'b1),
    .dout(grp_fu_2480_p3)
);

reconstruction_accel_mac_muladd_9s_7ns_14ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 17 ))
mac_muladd_9s_7ns_14ns_17_4_1_U35(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp3_fu_629_p2),
    .din1(grp_fu_2489_p1),
    .din2(grp_fu_2489_p2),
    .ce(1'b1),
    .dout(grp_fu_2489_p3)
);

reconstruction_accel_mac_muladd_8ns_7ns_15ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_7ns_15ns_16_4_1_U36(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2497_p0),
    .din1(grp_fu_2497_p1),
    .din2(grp_fu_2497_p2),
    .ce(1'b1),
    .dout(grp_fu_2497_p3)
);

reconstruction_accel_mac_muladd_8ns_6ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_6ns_16ns_16_4_1_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2506_p0),
    .din1(grp_fu_2506_p1),
    .din2(mul_ln452_1_fu_824_p2),
    .ce(1'b1),
    .dout(grp_fu_2506_p3)
);

reconstruction_accel_mac_muladd_8ns_8s_15s_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 15 ))
mac_muladd_8ns_8s_15s_15_4_1_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2515_p0),
    .din1(grp_fu_2515_p1),
    .din2(grp_fu_2515_p2),
    .ce(1'b1),
    .dout(grp_fu_2515_p3)
);

reconstruction_accel_mac_muladd_8ns_7s_15ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_7s_15ns_16_4_1_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2524_p0),
    .din1(grp_fu_2524_p1),
    .din2(grp_fu_2524_p2),
    .ce(1'b1),
    .dout(grp_fu_2524_p3)
);

reconstruction_accel_mac_muladd_8ns_6ns_15ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_6ns_15ns_16_4_1_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2533_p0),
    .din1(grp_fu_2533_p1),
    .din2(grp_fu_2533_p2),
    .ce(1'b1),
    .dout(grp_fu_2533_p3)
);

reconstruction_accel_mac_muladd_8ns_7ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_7ns_16ns_16_4_1_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2542_p0),
    .din1(grp_fu_2542_p1),
    .din2(grp_fu_2542_p2),
    .ce(1'b1),
    .dout(grp_fu_2542_p3)
);

reconstruction_accel_mac_muladd_8ns_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8s_16s_17_4_1_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2551_p0),
    .din1(grp_fu_2551_p1),
    .din2(grp_fu_2480_p3),
    .ce(1'b1),
    .dout(grp_fu_2551_p3)
);

reconstruction_accel_mac_muladd_8ns_7ns_13s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_7ns_13s_16_4_1_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2560_p0),
    .din1(grp_fu_2560_p1),
    .din2(sub_ln452_8_fu_964_p2),
    .ce(1'b1),
    .dout(grp_fu_2560_p3)
);

reconstruction_accel_mac_muladd_8ns_6ns_15ns_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 15 ))
mac_muladd_8ns_6ns_15ns_15_4_1_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2569_p0),
    .din1(grp_fu_2569_p1),
    .din2(grp_fu_2569_p2),
    .ce(1'b1),
    .dout(grp_fu_2569_p3)
);

reconstruction_accel_mac_muladd_8ns_7ns_15ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_7ns_15ns_16_4_1_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2578_p0),
    .din1(grp_fu_2578_p1),
    .din2(grp_fu_2578_p2),
    .ce(1'b1),
    .dout(grp_fu_2578_p3)
);

reconstruction_accel_mac_muladd_8ns_6ns_12ns_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 15 ))
mac_muladd_8ns_6ns_12ns_15_4_1_U46(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2587_p0),
    .din1(grp_fu_2587_p1),
    .din2(grp_fu_2587_p2),
    .ce(1'b1),
    .dout(grp_fu_2587_p3)
);

reconstruction_accel_mac_muladd_8ns_7ns_10ns_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 15 ))
mac_muladd_8ns_7ns_10ns_15_4_1_U47(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2596_p0),
    .din1(grp_fu_2596_p1),
    .din2(grp_fu_2596_p2),
    .ce(1'b1),
    .dout(grp_fu_2596_p3)
);

reconstruction_accel_mac_muladd_8ns_8s_15ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8s_15ns_16_4_1_U48(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2605_p0),
    .din1(grp_fu_2605_p1),
    .din2(grp_fu_2605_p2),
    .ce(1'b1),
    .dout(grp_fu_2605_p3)
);

reconstruction_accel_mac_muladd_8ns_6s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_6s_16s_16_4_1_U49(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2614_p0),
    .din1(grp_fu_2614_p1),
    .din2(mul_ln452_17_fu_1098_p2),
    .ce(1'b1),
    .dout(grp_fu_2614_p3)
);

reconstruction_accel_mac_muladd_8ns_7ns_14s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_7ns_14s_16_4_1_U50(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2623_p0),
    .din1(grp_fu_2623_p1),
    .din2(sub_ln452_18_fu_1073_p2),
    .ce(1'b1),
    .dout(grp_fu_2623_p3)
);

reconstruction_accel_mac_muladd_8ns_6ns_15ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_6ns_15ns_16_4_1_U51(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2632_p0),
    .din1(grp_fu_2632_p1),
    .din2(grp_fu_2632_p2),
    .ce(1'b1),
    .dout(grp_fu_2632_p3)
);

reconstruction_accel_mac_muladd_8ns_5ns_15ns_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 15 ))
mac_muladd_8ns_5ns_15ns_15_4_1_U52(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2641_p0),
    .din1(grp_fu_2641_p1),
    .din2(grp_fu_2641_p2),
    .ce(1'b1),
    .dout(grp_fu_2641_p3)
);

reconstruction_accel_mac_muladd_8ns_8s_12ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8s_12ns_16_4_1_U53(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2650_p0),
    .din1(grp_fu_2650_p1),
    .din2(grp_fu_2650_p2),
    .ce(1'b1),
    .dout(grp_fu_2650_p3)
);

reconstruction_accel_mac_muladd_8ns_7ns_15ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_7ns_15ns_16_4_1_U54(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2659_p0),
    .din1(grp_fu_2659_p1),
    .din2(grp_fu_2659_p2),
    .ce(1'b1),
    .dout(grp_fu_2659_p3)
);

reconstruction_accel_mac_muladd_8ns_8s_14s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8s_14s_16_4_1_U55(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2668_p0),
    .din1(grp_fu_2668_p1),
    .din2(sub_ln452_25_fu_1191_p2),
    .ce(1'b1),
    .dout(grp_fu_2668_p3)
);

reconstruction_accel_mac_muladd_8ns_7s_17s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_7s_17s_17_4_1_U56(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2677_p0),
    .din1(grp_fu_2677_p1),
    .din2(grp_fu_2489_p3),
    .ce(1'b1),
    .dout(grp_fu_2677_p3)
);

reconstruction_accel_mac_muladd_8ns_6s_14s_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 15 ))
mac_muladd_8ns_6s_14s_15_4_1_U57(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2686_p0),
    .din1(grp_fu_2686_p1),
    .din2(mul_ln452_23_fu_1161_p2),
    .ce(1'b1),
    .dout(grp_fu_2686_p3)
);

reconstruction_accel_am_addmul_17s_17s_12ns_31_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 17 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 31 ))
am_addmul_17s_17s_12ns_31_3_1_U58(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln452_25_reg_3159),
    .din1(add_ln452_21_reg_3154),
    .din2(grp_fu_2695_p2),
    .ce(1'b1),
    .dout(grp_fu_2695_p3)
);

reconstruction_accel_am_addmul_17s_17s_12ns_31_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 17 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 31 ))
am_addmul_17s_17s_12ns_31_3_1_U59(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln452_34_reg_3169),
    .din1(add_ln452_30_reg_3164),
    .din2(grp_fu_2705_p2),
    .ce(1'b1),
    .dout(grp_fu_2705_p3)
);

reconstruction_accel_am_addmul_17s_17s_12ns_31_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 17 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 31 ))
am_addmul_17s_17s_12ns_31_3_1_U60(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln452_43_reg_3179),
    .din1(add_ln452_39_reg_3174),
    .din2(grp_fu_2715_p2),
    .ce(1'b1),
    .dout(grp_fu_2715_p3)
);

reconstruction_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln361_fu_390_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten10_fu_278 <= add_ln361_1_fu_396_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten10_fu_278 <= 17'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln361_fu_390_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            px_fu_270 <= add_ln363_fu_441_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            px_fu_270 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            py_fu_274 <= 9'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            py_fu_274 <= select_ln361_1_fu_472_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            win01_1_fu_266 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            win01_1_fu_266 <= win01_fu_703_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            win02_fu_262 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            win02_fu_262 <= conv1_line0_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            win11_1_fu_258 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            win11_1_fu_258 <= win11_fu_596_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            win12_fu_254 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            win12_fu_254 <= conv1_line1_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            win21_1_fu_250 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            win21_1_fu_250 <= win21_fu_689_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            win22_fu_246 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            win22_fu_246 <= win22_3_fu_681_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        acc_10_reg_3184 <= acc_10_fu_1793_p2;
        acc_6_reg_3149 <= acc_6_fu_1438_p2;
        acc_reg_3144 <= acc_fu_1325_p2;
        add_ln452_18_reg_3073 <= add_ln452_18_fu_1002_p2;
        add_ln452_21_reg_3154 <= add_ln452_21_fu_1473_p2;
        add_ln452_25_reg_3159 <= add_ln452_25_fu_1482_p2;
        add_ln452_30_reg_3164 <= add_ln452_30_fu_1593_p2;
        add_ln452_34_reg_3169 <= add_ln452_34_fu_1618_p2;
        add_ln452_39_reg_3174 <= add_ln452_39_fu_1697_p2;
        add_ln452_43_reg_3179 <= add_ln452_43_fu_1722_p2;
        add_ln452_49_reg_3124 <= add_ln452_49_fu_1155_p2;
        add_ln479_reg_2886_pp0_iter2_reg <= add_ln479_reg_2886;
        add_ln479_reg_2886_pp0_iter3_reg <= add_ln479_reg_2886_pp0_iter2_reg;
        add_ln479_reg_2886_pp0_iter4_reg <= add_ln479_reg_2886_pp0_iter3_reg;
        add_ln479_reg_2886_pp0_iter5_reg <= add_ln479_reg_2886_pp0_iter4_reg;
        add_ln479_reg_2886_pp0_iter6_reg <= add_ln479_reg_2886_pp0_iter5_reg;
        add_ln479_reg_2886_pp0_iter7_reg <= add_ln479_reg_2886_pp0_iter6_reg;
        add_ln479_reg_2886_pp0_iter8_reg <= add_ln479_reg_2886_pp0_iter7_reg;
        and_ln423_reg_2872_pp0_iter2_reg <= and_ln423_reg_2872;
        and_ln423_reg_2872_pp0_iter3_reg <= and_ln423_reg_2872_pp0_iter2_reg;
        and_ln423_reg_2872_pp0_iter4_reg <= and_ln423_reg_2872_pp0_iter3_reg;
        and_ln423_reg_2872_pp0_iter5_reg <= and_ln423_reg_2872_pp0_iter4_reg;
        and_ln423_reg_2872_pp0_iter6_reg <= and_ln423_reg_2872_pp0_iter5_reg;
        and_ln423_reg_2872_pp0_iter7_reg <= and_ln423_reg_2872_pp0_iter6_reg;
        and_ln423_reg_2872_pp0_iter8_reg <= and_ln423_reg_2872_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        q8_1_reg_3229 <= q8_1_fu_2080_p3;
        q8_2_reg_3234 <= q8_2_fu_2156_p3;
        q8_3_reg_3239 <= q8_3_fu_2232_p3;
        q8_4_reg_3244 <= q8_4_fu_2308_p3;
        q8_5_reg_3249 <= q8_5_fu_2386_p3;
        q8_6_reg_3209 <= q8_6_fu_1958_p3;
        q8_6_reg_3209_pp0_iter8_reg <= q8_6_reg_3209;
        tmp_20_reg_3043[8 : 1] <= tmp_20_fu_841_p3[8 : 1];
        tmp_21_reg_3214 <= grp_fu_1846_p2[32'd29];
        trunc_ln5_reg_3219 <= {{add_ln39_fu_1978_p2[29:20]}};
        trunc_ln6_reg_3224 <= {{sub_ln45_fu_1994_p2[29:20]}};
        win01_2_reg_2935 <= win01_2_fu_710_p3;
        win01_2_reg_2935_pp0_iter3_reg <= win01_2_reg_2935;
        win01_4_cast139_reg_2942[7 : 0] <= win01_4_cast139_fu_717_p1[7 : 0];
        win01_4_cast139_reg_2942_pp0_iter3_reg[7 : 0] <= win01_4_cast139_reg_2942[7 : 0];
        win01_4_cast_reg_2949[7 : 0] <= win01_4_cast_fu_721_p1[7 : 0];
        win01_4_cast_reg_2949_pp0_iter3_reg[7 : 0] <= win01_4_cast_reg_2949[7 : 0];
        win01_reg_2928 <= win01_fu_703_p3;
        win01_reg_2928_pp0_iter3_reg <= win01_reg_2928;
        win02_3_cast_reg_2961[7 : 0] <= win02_3_cast_fu_729_p1[7 : 0];
        win02_3_cast_reg_2961_pp0_iter3_reg[7 : 0] <= win02_3_cast_reg_2961[7 : 0];
        win02_3_reg_2900_pp0_iter3_reg <= win02_3_reg_2900;
        win02_3_reg_2900_pp0_iter4_reg <= win02_3_reg_2900_pp0_iter3_reg;
        win11_2_reg_2861_pp0_iter2_reg <= win11_2_reg_2861;
        win11_2_reg_2861_pp0_iter3_reg <= win11_2_reg_2861_pp0_iter2_reg;
        win11_2_reg_2861_pp0_iter4_reg <= win11_2_reg_2861_pp0_iter3_reg;
        win11_reg_2852_pp0_iter2_reg <= win11_reg_2852;
        win11_reg_2852_pp0_iter3_reg <= win11_reg_2852_pp0_iter2_reg;
        win12_3_cast142_reg_2980[7 : 0] <= win12_3_cast142_fu_741_p1[7 : 0];
        win12_3_cast142_reg_2980_pp0_iter3_reg[7 : 0] <= win12_3_cast142_reg_2980[7 : 0];
        win12_3_reg_2833_pp0_iter2_reg <= win12_3_reg_2833;
        win12_3_reg_2833_pp0_iter3_reg <= win12_3_reg_2833_pp0_iter2_reg;
        win12_3_reg_2833_pp0_iter4_reg <= win12_3_reg_2833_pp0_iter3_reg;
        win21_2_reg_2918 <= win21_2_fu_696_p3;
        win21_2_reg_2918_pp0_iter3_reg <= win21_2_reg_2918;
        win21_reg_2908 <= win21_fu_689_p3;
        win21_reg_2908_pp0_iter3_reg <= win21_reg_2908;
        win21_reg_2908_pp0_iter4_reg <= win21_reg_2908_pp0_iter3_reg;
        win22_3_cast140_reg_3013[7 : 0] <= win22_3_cast140_fu_761_p1[7 : 0];
        win22_3_cast140_reg_3013_pp0_iter3_reg[7 : 0] <= win22_3_cast140_reg_3013[7 : 0];
        win22_3_reg_2891 <= win22_3_fu_681_p3;
        win22_3_reg_2891_pp0_iter3_reg <= win22_3_reg_2891;
        win22_3_reg_2891_pp0_iter4_reg <= win22_3_reg_2891_pp0_iter3_reg;
        zext_ln445_1_reg_3024[7 : 0] <= zext_ln445_1_fu_769_p1[7 : 0];
        zext_ln445_1_reg_3024_pp0_iter3_reg[7 : 0] <= zext_ln445_1_reg_3024[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln479_reg_2886 <= add_ln479_fu_648_p2;
        and_ln370_1_reg_2823 <= and_ln370_1_fu_564_p2;
        and_ln423_reg_2872 <= and_ln423_fu_612_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        conv1_line0_addr_reg_2806 <= zext_ln363_fu_419_p1;
        conv1_line1_addr_reg_2812 <= zext_ln363_fu_419_p1;
        conv1_line1_addr_reg_2812_pp0_iter1_reg <= conv1_line1_addr_reg_2812;
        icmp_ln363_reg_2792 <= icmp_ln363_fu_405_p2;
        icmp_ln397_reg_2844 <= icmp_ln397_fu_591_p2;
        icmp_ln424_reg_2818 <= icmp_ln424_fu_435_p2;
        select_ln361_reg_2797 <= select_ln361_fu_411_p3;
        win11_2_reg_2861 <= win11_2_fu_604_p3;
        win11_reg_2852 <= win11_fu_596_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        win02_3_reg_2900 <= conv1_line0_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        win12_3_reg_2833 <= conv1_line1_q0;
    end
end

always @ (*) begin
    if (((icmp_ln361_fu_390_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten10_load = 17'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten10_load = indvar_flatten10_fu_278;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_px_load = 9'd0;
    end else begin
        ap_sig_allocacmp_px_load = px_fu_270;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        branch_input_ce0_local = 1'b1;
    end else begin
        branch_input_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_line0_ce0_local = 1'b1;
    end else begin
        conv1_line0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_line0_ce1_local = 1'b1;
    end else begin
        conv1_line0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_line0_we1_local = 1'b1;
    end else begin
        conv1_line0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_line1_ce0_local = 1'b1;
    end else begin
        conv1_line1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        conv1_line1_ce1_local = 1'b1;
    end else begin
        conv1_line1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        conv1_line1_we1_local = 1'b1;
    end else begin
        conv1_line1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        conv1_out_ce0_local = 1'b1;
    end else begin
        conv1_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln423_reg_2872_pp0_iter8_reg) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        conv1_out_we0_local = 1'b1;
    end else begin
        conv1_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_10_fu_1793_p2 = ($signed(sext_ln452_37_fu_1789_p1) + $signed(zext_ln452_36_fu_1767_p1));

assign acc_11_fu_1827_p2 = ($signed(add_ln452_60_fu_1821_p2) + $signed(sext_ln452_43_fu_1811_p1));

assign acc_6_fu_1438_p2 = ($signed(sext_ln452_9_fu_1434_p1) + $signed(add_ln452_12_fu_1403_p2));

assign acc_fu_1325_p2 = ($signed(zext_ln452_8_fu_1321_p1) + $signed(sext_ln452_2_fu_1302_p1));

assign add_ln361_1_fu_396_p2 = (ap_sig_allocacmp_indvar_flatten10_load + 17'd1);

assign add_ln361_fu_466_p2 = (py_fu_274 + 9'd1);

assign add_ln363_fu_441_p2 = (select_ln361_fu_411_p3 + 9'd1);

assign add_ln378_fu_580_p2 = ($signed(tmp_8_fu_517_p3) + $signed(sext_ln378_fu_576_p1));

assign add_ln381_fu_570_p2 = ($signed(zext_ln363_1_fu_545_p1) + $signed(10'd1023));

assign add_ln39_1_fu_2022_p2 = (trunc_ln462_1_fu_2010_p1 + 29'd524288);

assign add_ln39_2_fu_2098_p2 = (trunc_ln462_2_fu_2088_p1 + 29'd524288);

assign add_ln39_3_fu_2174_p2 = (trunc_ln462_3_fu_2164_p1 + 29'd524288);

assign add_ln39_4_fu_2250_p2 = (trunc_ln462_4_fu_2240_p1 + 29'd524288);

assign add_ln39_5_fu_2328_p2 = (trunc_ln462_5_fu_2316_p1 + 29'd524288);

assign add_ln39_6_fu_1900_p2 = (trunc_ln462_6_fu_1888_p1 + 29'd524288);

assign add_ln39_fu_1978_p2 = (trunc_ln462_fu_1966_p1 + 30'd524288);

assign add_ln452_11_fu_1393_p2 = ($signed(sext_ln452_6_fu_1390_p1) + $signed(zext_ln452_fu_1216_p1));

assign add_ln452_12_fu_1403_p2 = ($signed(sext_ln452_7_fu_1399_p1) + $signed(sext_ln452_5_fu_1387_p1));

assign add_ln452_14_fu_1412_p2 = ($signed(sub_ln452_5_fu_1381_p2) + $signed(15'd18190));

assign add_ln452_15_fu_1418_p2 = ($signed(add_ln452_14_fu_1412_p2) + $signed(sext_ln452_4_fu_1359_p1));

assign add_ln452_16_fu_1428_p2 = ($signed(sext_ln452_8_fu_1424_p1) + $signed(zext_ln452_12_fu_1409_p1));

assign add_ln452_18_fu_1002_p2 = ($signed(sext_ln452_12_fu_949_p1) + $signed(sext_ln452_11_fu_929_p1));

assign add_ln452_20_fu_1467_p2 = ($signed(sext_ln452_15_fu_1464_p1) + $signed(zext_ln452_16_fu_1457_p1));

assign add_ln452_21_fu_1473_p2 = ($signed(add_ln452_20_fu_1467_p2) + $signed(sext_ln452_14_fu_1461_p1));

assign add_ln452_25_fu_1482_p2 = ($signed(grp_fu_2551_p3) + $signed(sext_ln452_17_fu_1479_p1));

assign add_ln452_29_fu_1583_p2 = ($signed(zext_ln452_23_fu_1580_p1) + $signed(sext_ln452_21_fu_1542_p1));

assign add_ln452_2_fu_1287_p2 = (grp_fu_2506_p3 + zext_ln452_1_fu_1220_p1);

assign add_ln452_30_fu_1593_p2 = ($signed(sext_ln452_23_fu_1589_p1) + $signed(zext_ln452_22_fu_1577_p1));

assign add_ln452_32_fu_1602_p2 = ($signed(sext_ln452_20_fu_1510_p1) + $signed(16'd49668));

assign add_ln452_33_fu_1608_p2 = ($signed(add_ln452_32_fu_1602_p2) + $signed(sext_ln452_22_fu_1573_p1));

assign add_ln452_34_fu_1618_p2 = ($signed(sext_ln452_25_fu_1614_p1) + $signed(zext_ln452_24_fu_1599_p1));

assign add_ln452_38_fu_1688_p2 = ($signed(grp_fu_2614_p3) + $signed(zext_ln452_28_fu_1681_p1));

assign add_ln452_39_fu_1697_p2 = ($signed(sext_ln452_30_fu_1693_p1) + $signed(sext_ln452_29_fu_1685_p1));

assign add_ln452_3_fu_1296_p2 = ($signed(sext_ln452_1_fu_1292_p1) + $signed(zext_ln452_6_fu_1284_p1));

assign add_ln452_41_fu_1706_p2 = (sub_ln452_21_fu_1658_p2 + 15'd4014);

assign add_ln452_42_fu_1712_p2 = (add_ln452_41_fu_1706_p2 + zext_ln452_26_fu_1634_p1);

assign add_ln452_43_fu_1722_p2 = ($signed(sext_ln452_33_fu_1718_p1) + $signed(sext_ln452_32_fu_1703_p1));

assign add_ln452_47_fu_1753_p2 = (grp_fu_2641_p3 + zext_ln452_34_fu_1749_p1);

assign add_ln452_48_fu_1762_p2 = (zext_ln452_35_fu_1758_p1 + grp_fu_2632_p3);

assign add_ln452_49_fu_1155_p2 = (sub_ln452_23_fu_1144_p2 + zext_ln452_32_fu_1136_p1);

assign add_ln452_4_fu_1306_p2 = (zext_ln452_4_fu_1280_p1 + zext_ln452_3_fu_1252_p1);

assign add_ln452_51_fu_1774_p0 = grp_fu_2650_p3;

assign add_ln452_51_fu_1774_p2 = ($signed(add_ln452_51_fu_1774_p0) + $signed(zext_ln452_25_fu_1630_p1));

assign add_ln452_52_fu_1783_p2 = ($signed(sext_ln452_36_fu_1779_p1) + $signed(sext_ln452_35_fu_1771_p1));

assign add_ln452_53_fu_1675_p2 = (zext_ln452_62_fu_1671_p1 + win11_4_cast143_fu_1204_p1);

assign add_ln452_56_fu_1805_p2 = ($signed(sext_ln452_42_fu_1802_p1) + $signed(sext_ln452_41_fu_1799_p1));

assign add_ln452_60_fu_1821_p2 = ($signed(sext_ln452_44_fu_1818_p1) + $signed(zext_ln452_38_fu_1815_p1));

assign add_ln452_63_fu_1743_p2 = (zext_ln452_65_fu_1728_p1 + zext_ln452_66_fu_1739_p1);

assign add_ln452_7_fu_1315_p2 = (zext_ln452_7_fu_1312_p1 + add_ln452_4_fu_1306_p2);

assign add_ln452_8_fu_1246_p2 = (zext_ln452_39_fu_1231_p1 + zext_ln452_40_fu_1242_p1);

assign add_ln479_fu_648_p2 = (tmp_9_fu_531_p3 + zext_ln479_fu_644_p1);

assign add_ln482_fu_639_p2 = ($signed(select_ln361_reg_2797) + $signed(9'd510));

assign and_ln370_1_fu_564_p2 = (brmerge_not_fu_539_p2 & and_ln370_fu_558_p2);

assign and_ln370_fu_558_p2 = (icmp_ln375_fu_553_p2 & icmp_ln373_fu_548_p2);

assign and_ln423_fu_612_p2 = (icmp_ln424_reg_2818 & icmp227_fu_505_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign branch_input_address0 = zext_ln378_fu_586_p1;

assign branch_input_ce0 = branch_input_ce0_local;

assign brmerge_not_fu_539_p2 = (cmp58_fu_489_p2 ^ cmp57_fu_483_p2);

assign cmp57_fu_483_p2 = ((select_ln361_1_fu_472_p3 == 9'd0) ? 1'b1 : 1'b0);

assign cmp58_fu_489_p2 = ((select_ln361_1_fu_472_p3 < 9'd257) ? 1'b1 : 1'b0);

assign conv1_line1_address0 = zext_ln363_fu_419_p1;

assign conv1_out_address0 = zext_ln479_1_fu_2476_p1;

assign conv1_out_ce0 = conv1_out_ce0_local;

assign conv1_out_d0 = packed_fu_2461_p9;

assign conv1_out_we0 = conv1_out_we0_local;

assign empty_59_fu_525_p2 = ($signed(trunc_ln361_fu_479_p1) + $signed(8'd254));

assign empty_fu_511_p2 = ($signed(trunc_ln361_fu_479_p1) + $signed(8'd255));

assign grp_fu_1837_p1 = 31'd2864;

assign grp_fu_1846_p1 = 32'd2484;

assign grp_fu_1855_p1 = 30'd1996;

assign grp_fu_1882_p1 = 31'd2326;

assign grp_fu_2480_p0 = grp_fu_2480_p00;

assign grp_fu_2480_p00 = conv1_line1_q0;

assign grp_fu_2480_p1 = 15'd100;

assign grp_fu_2489_p1 = 17'd105;

assign grp_fu_2489_p2 = 17'd10964;

assign grp_fu_2497_p0 = win01_4_cast_fu_721_p1;

assign grp_fu_2497_p1 = 15'd94;

assign grp_fu_2497_p2 = zext_ln447_fu_820_p1;

assign grp_fu_2506_p0 = win12_3_cast_fu_747_p1;

assign grp_fu_2506_p1 = 14'd46;

assign grp_fu_2515_p0 = row_m2_cast150_fu_733_p1;

assign grp_fu_2515_p1 = 15'd32697;

assign grp_fu_2515_p2 = ($signed(sext_ln452_fu_858_p1) + $signed(15'd20785));

assign grp_fu_2524_p0 = win01_4_cast_fu_721_p1;

assign grp_fu_2524_p1 = 15'd32707;

assign grp_fu_2524_p2 = zext_ln447_fu_820_p1;

assign grp_fu_2533_p0 = grp_fu_2533_p00;

assign grp_fu_2533_p00 = win22_3_fu_681_p3;

assign grp_fu_2533_p1 = 14'd41;

assign grp_fu_2533_p2 = grp_fu_2533_p20;

assign grp_fu_2533_p20 = mul_ln452_6_fu_868_p2;

assign grp_fu_2542_p0 = grp_fu_2542_p00;

assign grp_fu_2542_p00 = win11_reg_2852;

assign grp_fu_2542_p1 = 15'd106;

assign grp_fu_2542_p2 = (sub_ln452_2_fu_889_p2 - zext_ln452_45_fu_902_p1);

assign grp_fu_2551_p0 = grp_fu_2551_p00;

assign grp_fu_2551_p00 = conv1_line0_q0;

assign grp_fu_2551_p1 = 16'd65426;

assign grp_fu_2560_p0 = zext_ln445_1_fu_769_p1;

assign grp_fu_2560_p1 = 15'd76;

assign grp_fu_2569_p0 = win21_4_cast133_fu_757_p1;

assign grp_fu_2569_p1 = 14'd50;

assign grp_fu_2569_p2 = (zext_ln452_53_fu_992_p1 - zext_ln452_52_fu_981_p1);

assign grp_fu_2578_p0 = zext_ln445_1_fu_769_p1;

assign grp_fu_2578_p1 = 15'd75;

assign grp_fu_2578_p2 = zext_ln452_17_fu_1024_p1;

assign grp_fu_2587_p0 = win12_3_cast_fu_747_p1;

assign grp_fu_2587_p1 = 14'd57;

assign grp_fu_2587_p2 = grp_fu_2587_p20;

assign grp_fu_2587_p20 = sub_ln452_11_fu_1046_p2;

assign grp_fu_2596_p0 = win02_3_cast_fu_729_p1;

assign grp_fu_2596_p1 = 15'd74;

assign grp_fu_2596_p2 = grp_fu_2596_p20;

assign grp_fu_2596_p20 = shl_ln_fu_1028_p3;

assign grp_fu_2605_p0 = grp_fu_2605_p00;

assign grp_fu_2605_p00 = win21_fu_689_p3;

assign grp_fu_2605_p1 = 16'd65432;

assign grp_fu_2605_p2 = grp_fu_2605_p20;

assign grp_fu_2605_p20 = sub_ln452_19_fu_1089_p2;

assign grp_fu_2614_p0 = win21_4_cast133_fu_757_p1;

assign grp_fu_2614_p1 = 14'd16365;

assign grp_fu_2623_p0 = win02_3_cast_fu_729_p1;

assign grp_fu_2623_p1 = 15'd97;

assign grp_fu_2632_p0 = grp_fu_2632_p00;

assign grp_fu_2632_p00 = win01_2_fu_710_p3;

assign grp_fu_2632_p1 = 14'd52;

assign grp_fu_2632_p2 = grp_fu_2632_p20;

assign grp_fu_2632_p20 = mul_ln452_19_fu_1103_p2;

assign grp_fu_2641_p0 = grp_fu_2641_p00;

assign grp_fu_2641_p00 = win21_2_fu_696_p3;

assign grp_fu_2641_p1 = 13'd22;

assign grp_fu_2641_p2 = (zext_ln452_52_fu_981_p1 + zext_ln452_53_fu_992_p1);

assign grp_fu_2650_p0 = grp_fu_2650_p00;

assign grp_fu_2650_p00 = win12_3_reg_2833;

assign grp_fu_2650_p1 = 16'd65448;

assign grp_fu_2650_p2 = 16'd2905;

assign grp_fu_2659_p0 = zext_ln445_1_fu_769_p1;

assign grp_fu_2659_p1 = 15'd84;

assign grp_fu_2659_p2 = zext_ln452_17_fu_1024_p1;

assign grp_fu_2668_p0 = grp_fu_2668_p00;

assign grp_fu_2668_p00 = win11_reg_2852;

assign grp_fu_2668_p1 = 16'd65450;

assign grp_fu_2677_p0 = row_m2_cast150_fu_733_p1;

assign grp_fu_2677_p1 = 15'd32729;

assign grp_fu_2686_p0 = grp_fu_2686_p00;

assign grp_fu_2686_p00 = win01_fu_703_p3;

assign grp_fu_2686_p1 = 14'd16357;

assign grp_fu_2695_p2 = 31'd2261;

assign grp_fu_2705_p2 = 31'd2286;

assign grp_fu_2715_p2 = 31'd2922;

assign icmp227_fu_505_p2 = ((tmp_fu_495_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln361_fu_390_p2 = ((ap_sig_allocacmp_indvar_flatten10_load == 17'd66564) ? 1'b1 : 1'b0);

assign icmp_ln363_fu_405_p2 = ((ap_sig_allocacmp_px_load == 9'd258) ? 1'b1 : 1'b0);

assign icmp_ln373_fu_548_p2 = ((select_ln361_reg_2797 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln375_fu_553_p2 = ((select_ln361_reg_2797 < 9'd257) ? 1'b1 : 1'b0);

assign icmp_ln397_fu_591_p2 = ((select_ln361_reg_2797 == 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln424_fu_435_p2 = ((tmp_15_fu_425_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_2423_p2 = ((tmp_23_fu_2413_p4 == 2'd1) ? 1'b1 : 1'b0);

assign mul_ln446_fu_1624_p0 = mul_ln446_fu_1624_p00;

assign mul_ln446_fu_1624_p00 = win02_3_reg_2900_pp0_iter4_reg;

assign mul_ln446_fu_1624_p1 = 14'd46;

assign mul_ln447_fu_1210_p0 = win11_4_cast_fu_1207_p1;

assign mul_ln447_fu_1210_p1 = 15'd75;

assign mul_ln452_17_fu_1098_p0 = win12_3_cast142_reg_2980_pp0_iter3_reg;

assign mul_ln452_17_fu_1098_p1 = 16'd65451;

assign mul_ln452_19_fu_1103_p0 = win02_3_cast_reg_2961_pp0_iter3_reg;

assign mul_ln452_19_fu_1103_p1 = 15'd103;

assign mul_ln452_1_fu_824_p0 = mul_ln452_1_fu_824_p00;

assign mul_ln452_1_fu_824_p00 = win21_2_reg_2918_pp0_iter3_reg;

assign mul_ln452_1_fu_824_p1 = 16'd65433;

assign mul_ln452_23_fu_1161_p0 = win01_4_cast139_reg_2942_pp0_iter3_reg;

assign mul_ln452_23_fu_1161_p1 = 14'd16365;

assign mul_ln452_6_fu_868_p0 = win22_3_cast126_fu_805_p1;

assign mul_ln452_6_fu_868_p1 = 15'd119;

assign or_ln83_fu_2447_p2 = (tmp_22_fu_2405_p3 | icmp_ln87_fu_2423_p2);

assign p_shl10_fu_1082_p3 = {{win22_3_reg_2891_pp0_iter3_reg}, {7'd0}};

assign p_shl11_fu_1112_p3 = {{win22_3_reg_2891_pp0_iter3_reg}, {3'd0}};

assign p_shl4_fu_808_p3 = {{win01_reg_2928_pp0_iter3_reg}, {7'd0}};

assign p_shl5_fu_1256_p3 = {{win21_reg_2908_pp0_iter4_reg}, {6'd0}};

assign p_shl6_fu_1363_p3 = {{win12_3_reg_2833_pp0_iter4_reg}, {7'd0}};

assign p_shl7_fu_1444_p3 = {{win11_2_reg_2861_pp0_iter4_reg}, {7'd0}};

assign p_shl8_fu_1011_p3 = {{win21_reg_2908_pp0_iter3_reg}, {7'd0}};

assign p_shl9_fu_1039_p3 = {{win21_2_reg_2918_pp0_iter3_reg}, {4'd0}};

assign packed_fu_2461_p9 = {{{{{{{{q8_6_reg_3209_pp0_iter8_reg}, {q8_5_reg_3249}}, {q8_4_reg_3244}}, {q8_3_reg_3239}}, {q8_2_reg_3234}}, {8'd0}}, {q8_1_reg_3229}}, {q8_fu_2453_p3}};

assign q8_1_fu_2080_p3 = ((tmp_30_fu_2068_p3[0:0] == 1'b1) ? 8'd0 : trunc_ln91_1_fu_2076_p1);

assign q8_2_fu_2156_p3 = ((tmp_37_fu_2144_p3[0:0] == 1'b1) ? 8'd0 : trunc_ln91_2_fu_2152_p1);

assign q8_3_fu_2232_p3 = ((tmp_43_fu_2220_p3[0:0] == 1'b1) ? 8'd0 : trunc_ln91_3_fu_2228_p1);

assign q8_4_fu_2308_p3 = ((tmp_48_fu_2296_p3[0:0] == 1'b1) ? 8'd0 : trunc_ln91_4_fu_2304_p1);

assign q8_5_fu_2386_p3 = ((tmp_52_fu_2374_p3[0:0] == 1'b1) ? 8'd0 : trunc_ln91_5_fu_2382_p1);

assign q8_6_fu_1958_p3 = ((tmp_55_fu_1946_p3[0:0] == 1'b1) ? 8'd0 : trunc_ln91_6_fu_1954_p1);

assign q8_fu_2453_p3 = ((or_ln83_fu_2447_p2[0:0] == 1'b1) ? select_ln83_fu_2439_p3 : trunc_ln91_fu_2429_p1);

assign q_1_fu_2060_p3 = ((tmp_29_fu_2014_p3[0:0] == 1'b1) ? sub_ln43_1_fu_2054_p2 : trunc_ln40_1_fu_2028_p4);

assign q_2_fu_2136_p3 = ((tmp_36_fu_2091_p3[0:0] == 1'b1) ? sub_ln43_2_fu_2130_p2 : trunc_ln40_2_fu_2104_p4);

assign q_3_fu_2212_p3 = ((tmp_42_fu_2167_p3[0:0] == 1'b1) ? sub_ln43_3_fu_2206_p2 : trunc_ln40_3_fu_2180_p4);

assign q_4_fu_2288_p3 = ((tmp_47_fu_2243_p3[0:0] == 1'b1) ? sub_ln43_4_fu_2282_p2 : trunc_ln40_4_fu_2256_p4);

assign q_5_fu_2366_p3 = ((tmp_51_fu_2320_p3[0:0] == 1'b1) ? sub_ln43_5_fu_2360_p2 : trunc_ln40_5_fu_2334_p4);

assign q_6_fu_1938_p3 = ((tmp_54_fu_1892_p3[0:0] == 1'b1) ? sub_ln43_6_fu_1932_p2 : trunc_ln40_6_fu_1906_p4);

assign q_fu_2399_p3 = ((tmp_21_reg_3214[0:0] == 1'b1) ? sub_ln43_fu_2394_p2 : trunc_ln5_reg_3219);

assign row_m1_cast153_fu_621_p1 = conv1_line1_q0;

assign row_m2_cast150_fu_733_p1 = conv1_line0_q0;

assign select_ln361_1_fu_472_p3 = ((icmp_ln363_reg_2792[0:0] == 1'b1) ? add_ln361_fu_466_p2 : py_fu_274);

assign select_ln361_fu_411_p3 = ((icmp_ln363_fu_405_p2[0:0] == 1'b1) ? 9'd0 : ap_sig_allocacmp_px_load);

assign select_ln83_fu_2439_p3 = ((xor_ln83_fu_2433_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign sext_ln378_fu_576_p1 = $signed(add_ln381_fu_570_p2);

assign sext_ln452_11_fu_929_p1 = $signed(sub_ln452_6_fu_923_p2);

assign sext_ln452_12_fu_949_p1 = $signed(sub_ln452_7_fu_944_p2);

assign sext_ln452_14_fu_1461_p1 = $signed(add_ln452_18_reg_3073);

assign sext_ln452_15_fu_1464_p0 = grp_fu_2569_p3;

assign sext_ln452_15_fu_1464_p1 = $signed(sext_ln452_15_fu_1464_p0);

assign sext_ln452_17_fu_1479_p1 = grp_fu_2560_p3;

assign sext_ln452_1_fu_1292_p1 = $signed(add_ln452_2_fu_1287_p2);

assign sext_ln452_20_fu_1510_p1 = $signed(sub_ln452_13_fu_1504_p2);

assign sext_ln452_21_fu_1542_p1 = $signed(sub_ln452_14_fu_1536_p2);

assign sext_ln452_22_fu_1573_p1 = $signed(sub_ln452_16_fu_1567_p2);

assign sext_ln452_23_fu_1589_p1 = $signed(add_ln452_29_fu_1583_p2);

assign sext_ln452_25_fu_1614_p1 = $signed(add_ln452_33_fu_1608_p2);

assign sext_ln452_29_fu_1685_p1 = grp_fu_2623_p3;

assign sext_ln452_2_fu_1302_p1 = $signed(add_ln452_3_fu_1296_p2);

assign sext_ln452_30_fu_1693_p1 = $signed(add_ln452_38_fu_1688_p2);

assign sext_ln452_32_fu_1703_p1 = grp_fu_2605_p3;

assign sext_ln452_33_fu_1718_p1 = $signed(add_ln452_42_fu_1712_p2);

assign sext_ln452_35_fu_1771_p1 = $signed(add_ln452_49_reg_3124);

assign sext_ln452_36_fu_1779_p1 = $signed(add_ln452_51_fu_1774_p2);

assign sext_ln452_37_fu_1789_p1 = $signed(add_ln452_52_fu_1783_p2);

assign sext_ln452_41_fu_1799_p1 = grp_fu_2686_p3;

assign sext_ln452_42_fu_1802_p1 = grp_fu_2668_p3;

assign sext_ln452_43_fu_1811_p1 = $signed(add_ln452_56_fu_1805_p2);

assign sext_ln452_44_fu_1818_p1 = grp_fu_2677_p3;

assign sext_ln452_4_fu_1359_p1 = $signed(sub_ln452_4_fu_1353_p2);

assign sext_ln452_5_fu_1387_p1 = grp_fu_2524_p3;

assign sext_ln452_6_fu_1390_p0 = grp_fu_2542_p3;

assign sext_ln452_6_fu_1390_p1 = $signed(sext_ln452_6_fu_1390_p0);

assign sext_ln452_7_fu_1399_p1 = $signed(add_ln452_11_fu_1393_p2);

assign sext_ln452_8_fu_1424_p1 = $signed(add_ln452_15_fu_1418_p2);

assign sext_ln452_9_fu_1434_p1 = $signed(add_ln452_16_fu_1428_p2);

assign sext_ln452_fu_858_p1 = $signed(sub_ln452_1_fu_852_p2);

assign shl_ln_fu_1028_p3 = {{win01_2_reg_2935_pp0_iter3_reg}, {2'd0}};

assign sub_ln43_1_fu_2054_p2 = (9'd0 - trunc_ln46_1_fu_2044_p4);

assign sub_ln43_2_fu_2130_p2 = (9'd0 - trunc_ln46_2_fu_2120_p4);

assign sub_ln43_3_fu_2206_p2 = (9'd0 - trunc_ln46_3_fu_2196_p4);

assign sub_ln43_4_fu_2282_p2 = (9'd0 - trunc_ln46_4_fu_2272_p4);

assign sub_ln43_5_fu_2360_p2 = (9'd0 - trunc_ln46_5_fu_2350_p4);

assign sub_ln43_6_fu_1932_p2 = (9'd0 - trunc_ln46_6_fu_1922_p4);

assign sub_ln43_fu_2394_p2 = (10'd0 - trunc_ln6_reg_3224);

assign sub_ln445_fu_815_p2 = (p_shl4_fu_808_p3 - win02_3_cast_reg_2961_pp0_iter3_reg);

assign sub_ln451_fu_1018_p2 = (p_shl8_fu_1011_p3 - win22_3_cast126_fu_805_p1);

assign sub_ln452_10_fu_1451_p2 = (p_shl7_fu_1444_p3 - win11_4_cast_fu_1207_p1);

assign sub_ln452_11_fu_1046_p2 = (p_shl9_fu_1039_p3 - win21_4_cast136_fu_796_p1);

assign sub_ln452_12_fu_1487_p2 = (15'd0 - zext_ln452_48_fu_1377_p1);

assign sub_ln452_13_fu_1504_p2 = (sub_ln452_12_fu_1487_p2 - zext_ln452_54_fu_1500_p1);

assign sub_ln452_14_fu_1536_p2 = (zext_ln452_56_fu_1532_p1 - zext_ln452_55_fu_1521_p1);

assign sub_ln452_15_fu_1557_p2 = (14'd0 - zext_ln452_57_fu_1553_p1);

assign sub_ln452_16_fu_1567_p2 = (sub_ln452_15_fu_1557_p2 - zext_ln452_58_fu_1563_p1);

assign sub_ln452_17_fu_1067_p2 = (14'd0 - zext_ln452_59_fu_1063_p1);

assign sub_ln452_18_fu_1073_p2 = (sub_ln452_17_fu_1067_p2 - win01_4_cast139_reg_2942_pp0_iter3_reg);

assign sub_ln452_19_fu_1089_p2 = (p_shl10_fu_1082_p3 - zext_ln445_1_reg_3024_pp0_iter3_reg);

assign sub_ln452_1_fu_852_p2 = (zext_ln452_43_fu_848_p1 - zext_ln452_42_fu_837_p1);

assign sub_ln452_20_fu_1649_p2 = (15'd0 - zext_ln452_60_fu_1645_p1);

assign sub_ln452_21_fu_1658_p2 = (sub_ln452_20_fu_1649_p2 - zext_ln452_61_fu_1655_p1);

assign sub_ln452_22_fu_1130_p2 = (p_shl11_fu_1112_p3 - zext_ln452_63_fu_1126_p1);

assign sub_ln452_23_fu_1144_p2 = (win22_3_cast140_reg_3013_pp0_iter3_reg - zext_ln452_64_fu_1140_p1);

assign sub_ln452_24_fu_1174_p2 = (14'd0 - zext_ln452_67_fu_1170_p1);

assign sub_ln452_25_fu_1191_p2 = (sub_ln452_24_fu_1174_p2 - zext_ln452_68_fu_1187_p1);

assign sub_ln452_2_fu_889_p2 = (16'd0 - zext_ln452_44_fu_885_p1);

assign sub_ln452_4_fu_1353_p2 = (zext_ln452_47_fu_1349_p1 - zext_ln452_46_fu_1338_p1);

assign sub_ln452_5_fu_1381_p2 = (p_shl6_fu_1363_p3 - zext_ln452_48_fu_1377_p1);

assign sub_ln452_6_fu_923_p2 = (win02_3_cast131_fu_793_p1 - zext_ln452_49_fu_919_p1);

assign sub_ln452_7_fu_944_p2 = (win01_4_cast_reg_2949_pp0_iter3_reg - zext_ln452_50_fu_940_p1);

assign sub_ln452_8_fu_964_p2 = (win22_3_cast132_fu_802_p1 - zext_ln452_51_fu_960_p1);

assign sub_ln452_fu_1274_p2 = (p_shl5_fu_1256_p3 - zext_ln452_41_fu_1270_p1);

assign sub_ln45_1_fu_2038_p2 = (29'd524288 - trunc_ln462_1_fu_2010_p1);

assign sub_ln45_2_fu_2114_p2 = (29'd524288 - trunc_ln462_2_fu_2088_p1);

assign sub_ln45_3_fu_2190_p2 = (29'd524288 - trunc_ln462_3_fu_2164_p1);

assign sub_ln45_4_fu_2266_p2 = (29'd524288 - trunc_ln462_4_fu_2240_p1);

assign sub_ln45_5_fu_2344_p2 = (29'd524288 - trunc_ln462_5_fu_2316_p1);

assign sub_ln45_6_fu_1916_p2 = (29'd524288 - trunc_ln462_6_fu_1888_p1);

assign sub_ln45_fu_1994_p2 = (30'd524288 - trunc_ln462_fu_1966_p1);

assign tmp3_fu_629_p2 = (win11_4_cast152_fu_617_p1 - row_m1_cast153_fu_621_p1);

assign tmp_15_fu_425_p4 = {{select_ln361_fu_411_p3[8:1]}};

assign tmp_16_fu_1224_p3 = {{win22_3_reg_2891_pp0_iter4_reg}, {6'd0}};

assign tmp_17_fu_1235_p3 = {{win22_3_reg_2891_pp0_iter4_reg}, {4'd0}};

assign tmp_18_fu_1263_p3 = {{win21_reg_2908_pp0_iter4_reg}, {2'd0}};

assign tmp_19_fu_830_p3 = {{win12_3_reg_2833_pp0_iter3_reg}, {3'd0}};

assign tmp_20_fu_841_p3 = {{win12_3_reg_2833_pp0_iter3_reg}, {1'd0}};

assign tmp_22_fu_2405_p3 = q_fu_2399_p3[32'd9];

assign tmp_23_fu_2413_p4 = {{q_fu_2399_p3[9:8]}};

assign tmp_24_fu_878_p3 = {{win21_2_reg_2918_pp0_iter3_reg}, {6'd0}};

assign tmp_25_fu_895_p3 = {{win21_2_reg_2918_pp0_iter3_reg}, {3'd0}};

assign tmp_26_fu_1331_p3 = {{win02_3_reg_2900_pp0_iter4_reg}, {3'd0}};

assign tmp_27_fu_1342_p3 = {{win02_3_reg_2900_pp0_iter4_reg}, {1'd0}};

assign tmp_28_fu_1370_p3 = {{win12_3_reg_2833_pp0_iter4_reg}, {5'd0}};

assign tmp_29_fu_2014_p3 = grp_fu_1855_p2[32'd28];

assign tmp_30_fu_2068_p3 = q_1_fu_2060_p3[32'd8];

assign tmp_31_fu_912_p3 = {{win01_reg_2928_pp0_iter3_reg}, {2'd0}};

assign tmp_32_fu_933_p3 = {{win01_2_reg_2935_pp0_iter3_reg}, {6'd0}};

assign tmp_33_fu_953_p3 = {{win21_reg_2908_pp0_iter3_reg}, {4'd0}};

assign tmp_34_fu_974_p3 = {{win11_reg_2852_pp0_iter3_reg}, {6'd0}};

assign tmp_35_fu_985_p3 = {{win11_reg_2852_pp0_iter3_reg}, {1'd0}};

assign tmp_36_fu_2091_p3 = grp_fu_2695_p3[32'd28];

assign tmp_37_fu_2144_p3 = q_2_fu_2136_p3[32'd8];

assign tmp_38_fu_1493_p3 = {{win12_3_reg_2833_pp0_iter4_reg}, {2'd0}};

assign tmp_39_fu_1514_p3 = {{win11_2_reg_2861_pp0_iter4_reg}, {6'd0}};

assign tmp_40_fu_1525_p3 = {{win11_2_reg_2861_pp0_iter4_reg}, {3'd0}};

assign tmp_41_fu_1546_p3 = {{win02_3_reg_2900_pp0_iter4_reg}, {4'd0}};

assign tmp_42_fu_2167_p3 = grp_fu_2705_p3[32'd28];

assign tmp_43_fu_2220_p3 = q_3_fu_2212_p3[32'd8];

assign tmp_44_fu_1056_p3 = {{win01_2_reg_2935_pp0_iter3_reg}, {4'd0}};

assign tmp_45_fu_1638_p3 = {{win12_3_reg_2833_pp0_iter4_reg}, {6'd0}};

assign tmp_46_fu_1664_p3 = {{win11_2_reg_2861_pp0_iter4_reg}, {5'd0}};

assign tmp_47_fu_2243_p3 = grp_fu_2715_p3[32'd28];

assign tmp_48_fu_2296_p3 = q_4_fu_2288_p3[32'd8];

assign tmp_49_fu_1119_p3 = {{win22_3_reg_2891_pp0_iter3_reg}, {1'd0}};

assign tmp_50_fu_1732_p3 = {{win11_2_reg_2861_pp0_iter4_reg}, {1'd0}};

assign tmp_51_fu_2320_p3 = grp_fu_1882_p2[32'd28];

assign tmp_52_fu_2374_p3 = q_5_fu_2366_p3[32'd8];

assign tmp_53_fu_1180_p3 = {{win21_2_reg_2918_pp0_iter3_reg}, {2'd0}};

assign tmp_54_fu_1892_p3 = grp_fu_1837_p2[32'd28];

assign tmp_55_fu_1946_p3 = q_6_fu_1938_p3[32'd8];

assign tmp_8_fu_517_p3 = {{empty_fu_511_p2}, {8'd0}};

assign tmp_9_fu_531_p3 = {{empty_59_fu_525_p2}, {8'd0}};

assign tmp_fu_495_p4 = {{select_ln361_1_fu_472_p3[8:1]}};

assign trunc_ln361_fu_479_p1 = select_ln361_1_fu_472_p3[7:0];

assign trunc_ln40_1_fu_2028_p4 = {{add_ln39_1_fu_2022_p2[28:20]}};

assign trunc_ln40_2_fu_2104_p4 = {{add_ln39_2_fu_2098_p2[28:20]}};

assign trunc_ln40_3_fu_2180_p4 = {{add_ln39_3_fu_2174_p2[28:20]}};

assign trunc_ln40_4_fu_2256_p4 = {{add_ln39_4_fu_2250_p2[28:20]}};

assign trunc_ln40_5_fu_2334_p4 = {{add_ln39_5_fu_2328_p2[28:20]}};

assign trunc_ln40_6_fu_1906_p4 = {{add_ln39_6_fu_1900_p2[28:20]}};

assign trunc_ln462_1_fu_2010_p1 = grp_fu_1855_p2[28:0];

assign trunc_ln462_2_fu_2088_p1 = grp_fu_2695_p3[28:0];

assign trunc_ln462_3_fu_2164_p1 = grp_fu_2705_p3[28:0];

assign trunc_ln462_4_fu_2240_p1 = grp_fu_2715_p3[28:0];

assign trunc_ln462_5_fu_2316_p1 = grp_fu_1882_p2[28:0];

assign trunc_ln462_6_fu_1888_p1 = grp_fu_1837_p2[28:0];

assign trunc_ln462_fu_1966_p1 = grp_fu_1846_p2[29:0];

assign trunc_ln46_1_fu_2044_p4 = {{sub_ln45_1_fu_2038_p2[28:20]}};

assign trunc_ln46_2_fu_2120_p4 = {{sub_ln45_2_fu_2114_p2[28:20]}};

assign trunc_ln46_3_fu_2196_p4 = {{sub_ln45_3_fu_2190_p2[28:20]}};

assign trunc_ln46_4_fu_2272_p4 = {{sub_ln45_4_fu_2266_p2[28:20]}};

assign trunc_ln46_5_fu_2350_p4 = {{sub_ln45_5_fu_2344_p2[28:20]}};

assign trunc_ln46_6_fu_1922_p4 = {{sub_ln45_6_fu_1916_p2[28:20]}};

assign trunc_ln91_1_fu_2076_p1 = q_1_fu_2060_p3[7:0];

assign trunc_ln91_2_fu_2152_p1 = q_2_fu_2136_p3[7:0];

assign trunc_ln91_3_fu_2228_p1 = q_3_fu_2212_p3[7:0];

assign trunc_ln91_4_fu_2304_p1 = q_4_fu_2288_p3[7:0];

assign trunc_ln91_5_fu_2382_p1 = q_5_fu_2366_p3[7:0];

assign trunc_ln91_6_fu_1954_p1 = q_6_fu_1938_p3[7:0];

assign trunc_ln91_fu_2429_p1 = q_fu_2399_p3[7:0];

assign win01_2_fu_710_p3 = ((icmp_ln397_reg_2844[0:0] == 1'b1) ? 8'd0 : win01_1_fu_266);

assign win01_4_cast139_fu_717_p1 = win01_2_fu_710_p3;

assign win01_4_cast_fu_721_p1 = win01_2_fu_710_p3;

assign win01_fu_703_p3 = ((icmp_ln397_reg_2844[0:0] == 1'b1) ? 8'd0 : win02_fu_262);

assign win02_3_cast131_fu_793_p1 = win01_reg_2928_pp0_iter3_reg;

assign win02_3_cast_fu_729_p1 = win01_fu_703_p3;

assign win11_2_fu_604_p3 = ((icmp_ln397_fu_591_p2[0:0] == 1'b1) ? 8'd0 : win11_1_fu_258);

assign win11_4_cast143_fu_1204_p1 = win11_2_reg_2861_pp0_iter4_reg;

assign win11_4_cast152_fu_617_p1 = win11_2_fu_604_p3;

assign win11_4_cast_fu_1207_p1 = win11_2_reg_2861_pp0_iter4_reg;

assign win11_fu_596_p3 = ((icmp_ln397_fu_591_p2[0:0] == 1'b1) ? 8'd0 : win12_fu_254);

assign win12_3_cast142_fu_741_p1 = win11_reg_2852;

assign win12_3_cast_fu_747_p1 = win11_reg_2852;

assign win21_2_fu_696_p3 = ((icmp_ln397_reg_2844[0:0] == 1'b1) ? 8'd0 : win21_1_fu_250);

assign win21_4_cast133_fu_757_p1 = win21_2_fu_696_p3;

assign win21_4_cast136_fu_796_p1 = win21_2_reg_2918_pp0_iter3_reg;

assign win21_fu_689_p3 = ((icmp_ln397_reg_2844[0:0] == 1'b1) ? 8'd0 : win22_fu_246);

assign win22_3_cast126_fu_805_p1 = win21_reg_2908_pp0_iter3_reg;

assign win22_3_cast132_fu_802_p1 = win21_reg_2908_pp0_iter3_reg;

assign win22_3_cast140_fu_761_p1 = win21_fu_689_p3;

assign win22_3_fu_681_p3 = ((and_ln370_1_reg_2823[0:0] == 1'b1) ? branch_input_q0 : 8'd0);

assign xor_ln83_fu_2433_p2 = (tmp_22_fu_2405_p3 ^ 1'd1);

assign zext_ln363_1_fu_545_p1 = select_ln361_reg_2797;

assign zext_ln363_fu_419_p1 = select_ln361_fu_411_p3;

assign zext_ln378_fu_586_p1 = add_ln378_fu_580_p2;

assign zext_ln445_1_fu_769_p1 = win22_3_fu_681_p3;

assign zext_ln447_fu_820_p1 = sub_ln445_fu_815_p2;

assign zext_ln452_12_fu_1409_p1 = grp_fu_2533_p3;

assign zext_ln452_16_fu_1457_p1 = sub_ln452_10_fu_1451_p2;

assign zext_ln452_17_fu_1024_p1 = sub_ln451_fu_1018_p2;

assign zext_ln452_1_fu_1220_p1 = mul_ln447_fu_1210_p2;

assign zext_ln452_22_fu_1577_p1 = grp_fu_2596_p3;

assign zext_ln452_23_fu_1580_p1 = grp_fu_2587_p3;

assign zext_ln452_24_fu_1599_p1 = grp_fu_2578_p3;

assign zext_ln452_25_fu_1630_p1 = mul_ln446_fu_1624_p2;

assign zext_ln452_26_fu_1634_p1 = mul_ln446_fu_1624_p2;

assign zext_ln452_28_fu_1681_p1 = add_ln452_53_fu_1675_p2;

assign zext_ln452_32_fu_1136_p1 = sub_ln452_22_fu_1130_p2;

assign zext_ln452_34_fu_1749_p1 = add_ln452_63_fu_1743_p2;

assign zext_ln452_35_fu_1758_p1 = add_ln452_47_fu_1753_p2;

assign zext_ln452_36_fu_1767_p1 = add_ln452_48_fu_1762_p2;

assign zext_ln452_38_fu_1815_p1 = grp_fu_2659_p3;

assign zext_ln452_39_fu_1231_p1 = tmp_16_fu_1224_p3;

assign zext_ln452_3_fu_1252_p1 = add_ln452_8_fu_1246_p2;

assign zext_ln452_40_fu_1242_p1 = tmp_17_fu_1235_p3;

assign zext_ln452_41_fu_1270_p1 = tmp_18_fu_1263_p3;

assign zext_ln452_42_fu_837_p1 = tmp_19_fu_830_p3;

assign zext_ln452_43_fu_848_p1 = tmp_20_fu_841_p3;

assign zext_ln452_44_fu_885_p1 = tmp_24_fu_878_p3;

assign zext_ln452_45_fu_902_p1 = tmp_25_fu_895_p3;

assign zext_ln452_46_fu_1338_p1 = tmp_26_fu_1331_p3;

assign zext_ln452_47_fu_1349_p1 = tmp_27_fu_1342_p3;

assign zext_ln452_48_fu_1377_p1 = tmp_28_fu_1370_p3;

assign zext_ln452_49_fu_919_p1 = tmp_31_fu_912_p3;

assign zext_ln452_4_fu_1280_p1 = sub_ln452_fu_1274_p2;

assign zext_ln452_50_fu_940_p1 = tmp_32_fu_933_p3;

assign zext_ln452_51_fu_960_p1 = tmp_33_fu_953_p3;

assign zext_ln452_52_fu_981_p1 = tmp_34_fu_974_p3;

assign zext_ln452_53_fu_992_p1 = tmp_35_fu_985_p3;

assign zext_ln452_54_fu_1500_p1 = tmp_38_fu_1493_p3;

assign zext_ln452_55_fu_1521_p1 = tmp_39_fu_1514_p3;

assign zext_ln452_56_fu_1532_p1 = tmp_40_fu_1525_p3;

assign zext_ln452_57_fu_1553_p1 = tmp_41_fu_1546_p3;

assign zext_ln452_58_fu_1563_p1 = tmp_27_fu_1342_p3;

assign zext_ln452_59_fu_1063_p1 = tmp_44_fu_1056_p3;

assign zext_ln452_60_fu_1645_p1 = tmp_45_fu_1638_p3;

assign zext_ln452_61_fu_1655_p1 = tmp_20_reg_3043;

assign zext_ln452_62_fu_1671_p1 = tmp_46_fu_1664_p3;

assign zext_ln452_63_fu_1126_p1 = tmp_49_fu_1119_p3;

assign zext_ln452_64_fu_1140_p1 = p_shl8_fu_1011_p3;

assign zext_ln452_65_fu_1728_p1 = tmp_40_fu_1525_p3;

assign zext_ln452_66_fu_1739_p1 = tmp_50_fu_1732_p3;

assign zext_ln452_67_fu_1170_p1 = p_shl9_fu_1039_p3;

assign zext_ln452_68_fu_1187_p1 = tmp_53_fu_1180_p3;

assign zext_ln452_6_fu_1284_p1 = grp_fu_2497_p3;

assign zext_ln452_7_fu_1312_p0 = grp_fu_2515_p3;

assign zext_ln452_7_fu_1312_p1 = $unsigned(zext_ln452_7_fu_1312_p0);

assign zext_ln452_8_fu_1321_p1 = add_ln452_7_fu_1315_p2;

assign zext_ln452_fu_1216_p1 = mul_ln447_fu_1210_p2;

assign zext_ln479_1_fu_2476_p1 = add_ln479_reg_2886_pp0_iter8_reg;

assign zext_ln479_fu_644_p1 = add_ln482_fu_639_p2;

always @ (posedge ap_clk) begin
    win01_4_cast139_reg_2942[13:8] <= 6'b000000;
    win01_4_cast139_reg_2942_pp0_iter3_reg[13:8] <= 6'b000000;
    win01_4_cast_reg_2949[14:8] <= 7'b0000000;
    win01_4_cast_reg_2949_pp0_iter3_reg[14:8] <= 7'b0000000;
    win02_3_cast_reg_2961[14:8] <= 7'b0000000;
    win02_3_cast_reg_2961_pp0_iter3_reg[14:8] <= 7'b0000000;
    win12_3_cast142_reg_2980[15:8] <= 8'b00000000;
    win12_3_cast142_reg_2980_pp0_iter3_reg[15:8] <= 8'b00000000;
    win22_3_cast140_reg_3013[15:8] <= 8'b00000000;
    win22_3_cast140_reg_3013_pp0_iter3_reg[15:8] <= 8'b00000000;
    zext_ln445_1_reg_3024[14:8] <= 7'b0000000;
    zext_ln445_1_reg_3024_pp0_iter3_reg[14:8] <= 7'b0000000;
    tmp_20_reg_3043[0] <= 1'b0;
end

endmodule //reconstruction_accel_reconstruction_accel_Pipeline_CONV1_Y_PAD_CONV1_X_PAD
