// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module reconstruction_accel_reconstruction_accel_Pipeline_BILINEAR_Y_BILINEAR_X (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER,
        input_r,
        baseline_ticks_address0,
        baseline_ticks_ce0,
        baseline_ticks_we0,
        baseline_ticks_d0,
        branch_input_address0,
        branch_input_ce0,
        branch_input_we0,
        branch_input_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_0_AWVALID;
input   m_axi_gmem0_0_AWREADY;
output  [63:0] m_axi_gmem0_0_AWADDR;
output  [0:0] m_axi_gmem0_0_AWID;
output  [31:0] m_axi_gmem0_0_AWLEN;
output  [2:0] m_axi_gmem0_0_AWSIZE;
output  [1:0] m_axi_gmem0_0_AWBURST;
output  [1:0] m_axi_gmem0_0_AWLOCK;
output  [3:0] m_axi_gmem0_0_AWCACHE;
output  [2:0] m_axi_gmem0_0_AWPROT;
output  [3:0] m_axi_gmem0_0_AWQOS;
output  [3:0] m_axi_gmem0_0_AWREGION;
output  [0:0] m_axi_gmem0_0_AWUSER;
output   m_axi_gmem0_0_WVALID;
input   m_axi_gmem0_0_WREADY;
output  [7:0] m_axi_gmem0_0_WDATA;
output  [0:0] m_axi_gmem0_0_WSTRB;
output   m_axi_gmem0_0_WLAST;
output  [0:0] m_axi_gmem0_0_WID;
output  [0:0] m_axi_gmem0_0_WUSER;
output   m_axi_gmem0_0_ARVALID;
input   m_axi_gmem0_0_ARREADY;
output  [63:0] m_axi_gmem0_0_ARADDR;
output  [0:0] m_axi_gmem0_0_ARID;
output  [31:0] m_axi_gmem0_0_ARLEN;
output  [2:0] m_axi_gmem0_0_ARSIZE;
output  [1:0] m_axi_gmem0_0_ARBURST;
output  [1:0] m_axi_gmem0_0_ARLOCK;
output  [3:0] m_axi_gmem0_0_ARCACHE;
output  [2:0] m_axi_gmem0_0_ARPROT;
output  [3:0] m_axi_gmem0_0_ARQOS;
output  [3:0] m_axi_gmem0_0_ARREGION;
output  [0:0] m_axi_gmem0_0_ARUSER;
input   m_axi_gmem0_0_RVALID;
output   m_axi_gmem0_0_RREADY;
input  [7:0] m_axi_gmem0_0_RDATA;
input   m_axi_gmem0_0_RLAST;
input  [0:0] m_axi_gmem0_0_RID;
input  [10:0] m_axi_gmem0_0_RFIFONUM;
input  [0:0] m_axi_gmem0_0_RUSER;
input  [1:0] m_axi_gmem0_0_RRESP;
input   m_axi_gmem0_0_BVALID;
output   m_axi_gmem0_0_BREADY;
input  [1:0] m_axi_gmem0_0_BRESP;
input  [0:0] m_axi_gmem0_0_BID;
input  [0:0] m_axi_gmem0_0_BUSER;
input  [63:0] input_r;
output  [15:0] baseline_ticks_address0;
output   baseline_ticks_ce0;
output   baseline_ticks_we0;
output  [13:0] baseline_ticks_d0;
output  [15:0] branch_input_address0;
output   branch_input_ce0;
output   branch_input_we0;
output  [7:0] branch_input_d0;

reg ap_idle;
reg m_axi_gmem0_0_ARVALID;
reg[63:0] m_axi_gmem0_0_ARADDR;
reg m_axi_gmem0_0_RREADY;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
reg   [0:0] icmp_ln248_reg_916;
reg    ap_block_state4_io_grp1;
reg    ap_block_pp0_stage3_subdone_grp1_done_reg;
reg    ap_block_pp0_stage3_subdone_grp1;
reg    ap_block_pp0_stage3_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage3_subdone_grp5_done_reg;
reg    ap_block_pp0_stage3_subdone_grp5;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_AR;
wire    ap_block_pp0_stage3_grp1;
reg    gmem0_blk_n_R;
wire    ap_block_pp0_stage3_grp5;
wire    ap_block_pp0_stage0_grp2;
reg    ap_block_pp0_stage0_subdone_grp2_done_reg;
reg    ap_block_pp0_stage0_subdone_grp2;
reg    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage0_grp6;
reg    ap_block_pp0_stage0_subdone_grp6_done_reg;
reg    ap_block_pp0_stage0_subdone_grp6;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp3;
reg    ap_block_pp0_stage1_subdone_grp3_done_reg;
reg    ap_block_pp0_stage1_subdone_grp3;
reg    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage1_grp7;
reg    ap_block_pp0_stage1_subdone_grp7_done_reg;
reg    ap_block_pp0_stage1_subdone_grp7;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_grp4;
reg   [7:0] reg_264;
reg    ap_block_pp0_stage3_11001_grp5;
reg    ap_block_pp0_stage0_11001_grp6;
reg    ap_block_pp0_stage1_11001_grp7;
reg    ap_block_pp0_stage2_11001_grp4;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
wire   [0:0] icmp_ln248_fu_286_p2;
reg    ap_block_pp0_stage1_11001;
reg   [0:0] icmp_ln248_reg_916_pp0_iter1_reg;
reg   [0:0] icmp_ln248_reg_916_pp0_iter2_reg;
reg   [0:0] icmp_ln248_reg_916_pp0_iter3_reg;
wire   [8:0] select_ln247_fu_316_p3;
reg   [8:0] select_ln247_reg_920;
wire   [7:0] trunc_ln332_fu_332_p1;
reg   [7:0] trunc_ln332_reg_926;
reg   [6:0] i_2_reg_933;
wire   [0:0] and_ln125_1_fu_374_p2;
reg   [0:0] and_ln125_1_reg_938;
reg   [0:0] and_ln125_1_reg_938_pp0_iter1_reg;
reg   [0:0] and_ln125_1_reg_938_pp0_iter2_reg;
reg   [0:0] and_ln125_1_reg_938_pp0_iter3_reg;
wire   [7:0] trunc_ln281_fu_380_p1;
reg   [7:0] trunc_ln281_reg_944;
wire   [0:0] trunc_ln115_1_fu_384_p1;
reg   [0:0] trunc_ln115_1_reg_948;
wire   [0:0] or_ln125_fu_506_p2;
reg   [0:0] or_ln125_reg_952;
reg   [0:0] or_ln125_reg_952_pp0_iter1_reg;
reg   [0:0] or_ln125_reg_952_pp0_iter2_reg;
reg   [0:0] or_ln125_reg_952_pp0_iter3_reg;
wire   [15:0] add_ln332_fu_539_p2;
reg   [15:0] add_ln332_reg_957;
wire    ap_block_pp0_stage2_11001_grp0;
reg    ap_block_pp0_stage2_subdone_grp0_done_reg;
wire    ap_block_pp0_stage2_subdone_grp0;
reg    ap_block_pp0_stage2_subdone;
reg   [15:0] add_ln332_reg_957_pp0_iter1_reg;
reg   [15:0] add_ln332_reg_957_pp0_iter2_reg;
reg   [15:0] add_ln332_reg_957_pp0_iter3_reg;
reg   [63:0] gmem0_addr_reg_962;
reg   [63:0] gmem0_addr_1_reg_968;
reg   [63:0] gmem0_addr_2_reg_974;
reg   [63:0] gmem0_addr_3_reg_980;
wire   [10:0] zext_ln275_1_fu_670_p1;
reg   [10:0] zext_ln275_1_reg_986;
wire   [10:0] mul_ln314_fu_678_p2;
reg   [10:0] mul_ln314_reg_991;
wire   [9:0] zext_ln275_fu_684_p1;
reg   [9:0] zext_ln275_reg_996;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
wire   [10:0] mul_ln320_fu_696_p2;
reg   [10:0] mul_ln320_reg_1007;
wire   [1:0] sel_tmp2_fu_701_p3;
reg   [1:0] sel_tmp2_reg_1012;
wire    ap_block_pp0_stage3_11001_grp0;
reg    ap_block_pp0_stage3_subdone_grp0_done_reg;
wire    ap_block_pp0_stage3_subdone_grp0;
wire   [10:0] grp_fu_867_p3;
reg   [10:0] h0_reg_1022;
wire   [13:0] mul_ln327_fu_770_p2;
reg   [7:0] ap_phi_mux_x0_2_phi_fu_195_p8;
wire   [7:0] x0_fu_560_p2;
reg   [7:0] ap_phi_reg_pp0_iter0_x0_2_reg_190;
wire   [7:0] zext_ln159_1_fu_554_p1;
reg   [7:0] ap_phi_mux_x1_phi_fu_212_p8;
reg   [7:0] ap_phi_reg_pp0_iter0_x1_reg_207;
wire   [7:0] add_ln162_1_fu_567_p2;
reg   [2:0] ap_phi_reg_pp0_iter0_wx0_reg_224;
reg   [2:0] ap_phi_reg_pp0_iter1_wx0_reg_224;
reg   [2:0] ap_phi_reg_pp0_iter2_wx0_reg_224;
reg   [2:0] ap_phi_reg_pp0_iter3_wx0_reg_224;
reg   [1:0] ap_phi_reg_pp0_iter0_wx1_reg_244;
reg   [1:0] ap_phi_reg_pp0_iter1_wx1_reg_244;
reg   [1:0] ap_phi_reg_pp0_iter2_wx1_reg_244;
reg   [1:0] ap_phi_reg_pp0_iter3_wx1_reg_244;
wire   [63:0] zext_ln332_1_fu_776_p1;
wire    ap_block_pp0_stage2_grp0;
wire   [63:0] add_ln292_fu_596_p2;
wire   [63:0] add_ln297_fu_617_p2;
wire   [63:0] add_ln302_fu_638_p2;
wire   [63:0] add_ln307_fu_659_p2;
reg    ap_block_pp0_stage3_11001_grp1;
reg    ap_block_state5_io_grp2;
reg    ap_block_pp0_stage0_11001_grp2;
reg    ap_block_pp0_stage1_11001_grp3;
reg   [8:0] x_fu_134;
wire   [8:0] add_ln272_fu_396_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage1;
reg   [8:0] y_fu_138;
wire   [8:0] select_ln248_fu_324_p3;
reg   [16:0] indvar_flatten_fu_142;
wire   [16:0] add_ln248_fu_292_p2;
reg    baseline_ticks_we0_local;
wire   [13:0] grp_fu_874_p4;
reg    baseline_ticks_ce0_local;
reg    branch_input_we0_local;
wire   [7:0] select_ln76_fu_858_p3;
reg    branch_input_ce0_local;
wire   [0:0] icmp_ln271_fu_310_p2;
wire   [8:0] add_ln249_fu_304_p2;
wire   [0:0] trunc_ln115_fu_336_p1;
wire   [0:0] icmp_ln125_2_fu_356_p2;
wire   [0:0] icmp_ln125_3_fu_362_p2;
wire   [0:0] and_ln125_fu_368_p2;
wire   [0:0] xor_ln144_fu_340_p2;
wire   [7:0] zext_ln159_fu_424_p1;
wire   [0:0] icmp_ln125_fu_439_p2;
wire   [0:0] icmp_ln125_1_fu_444_p2;
wire   [7:0] y0_2_fu_458_p6;
wire   [7:0] y0_2_fu_458_p9;
wire   [2:0] sel_tmp1_fu_449_p4;
wire   [7:0] y1_fu_482_p8;
wire   [7:0] y1_fu_482_p9;
wire   [7:0] y0_2_fu_458_p11;
wire   [14:0] mul_fu_512_p3;
wire   [7:0] y1_fu_482_p11;
wire   [14:0] mul9_fu_524_p3;
wire   [15:0] tmp_fu_417_p3;
wire   [15:0] zext_ln332_fu_536_p1;
wire   [6:0] i_fu_545_p4;
wire  signed [15:0] sext_ln275_fu_582_p1;
wire  signed [15:0] mul_cast_fu_520_p1;
wire   [15:0] add_ln293_fu_586_p2;
wire  signed [63:0] sext_ln292_fu_592_p1;
wire   [15:0] zext_ln275_3_fu_578_p1;
wire   [15:0] add_ln298_fu_607_p2;
wire  signed [63:0] sext_ln297_fu_613_p1;
wire   [15:0] zext_ln269_fu_532_p1;
wire   [15:0] add_ln303_fu_628_p2;
wire  signed [63:0] sext_ln302_fu_634_p1;
wire   [14:0] zext_ln275_2_fu_574_p1;
wire   [14:0] add_ln308_fu_649_p2;
wire   [63:0] zext_ln307_fu_655_p1;
wire    ap_block_pp0_stage0_grp0;
wire   [2:0] mul_ln314_fu_678_p0;
wire   [7:0] mul_ln314_fu_678_p1;
wire    ap_block_pp0_stage1_grp0;
wire   [2:0] mul_ln320_fu_696_p0;
wire   [7:0] mul_ln320_fu_696_p1;
wire    ap_block_pp0_stage3_grp0;
wire   [1:0] zext_ln252_cast_fu_707_p7;
wire   [1:0] zext_ln252_cast_fu_707_p8;
wire   [1:0] zext_ln252_cast_fu_707_p9;
wire   [1:0] mul_ln320_1_fu_735_p0;
wire   [7:0] mul_ln320_1_fu_735_p1;
wire   [9:0] mul_ln320_1_fu_735_p2;
wire   [2:0] storemerge5_i_cast_cast_cast_fu_744_p7;
wire   [2:0] storemerge5_i_cast_cast_cast_fu_744_p9;
wire   [10:0] mul_ln327_fu_770_p0;
wire   [2:0] mul_ln327_fu_770_p1;
wire   [3:0] remainder_fu_781_p1;
wire   [0:0] icmp_ln64_fu_806_p2;
wire   [0:0] tmp_56_fu_793_p3;
wire   [9:0] trunc_ln2_fu_784_p4;
wire   [0:0] icmp_ln61_fu_800_p2;
wire   [0:0] and_ln65_fu_812_p2;
wire   [0:0] or_ln65_fu_824_p2;
wire   [9:0] quotient_fu_818_p2;
wire   [9:0] quotient_1_fu_830_p3;
wire   [1:0] tmp_57_fu_838_p4;
wire   [0:0] icmp_ln72_fu_848_p2;
wire   [7:0] trunc_ln76_fu_854_p1;
wire   [7:0] grp_fu_867_p0;
wire   [1:0] grp_fu_867_p1;
wire   [9:0] grp_fu_874_p0;
wire   [1:0] grp_fu_874_p2;
reg    grp_fu_867_ce;
reg    ap_block_pp0_stage2_11001;
reg    ap_block_pp0_stage3_11001;
reg    ap_block_pp0_stage0_11001;
reg    grp_fu_874_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter3_stage2;
reg    ap_idle_pp0_0to2;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0_1to4;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [9:0] grp_fu_867_p00;
wire   [9:0] grp_fu_867_p10;
wire   [10:0] grp_fu_874_p00;
wire   [12:0] grp_fu_874_p20;
wire   [10:0] mul_ln314_fu_678_p00;
wire   [10:0] mul_ln314_fu_678_p10;
wire   [9:0] mul_ln320_1_fu_735_p10;
wire   [10:0] mul_ln320_fu_696_p10;
wire   [13:0] mul_ln327_fu_770_p00;
wire   [13:0] mul_ln327_fu_770_p10;
reg    ap_condition_441;
reg    ap_condition_544;
wire  signed [2:0] y0_2_fu_458_p1;
wire   [2:0] y0_2_fu_458_p3;
wire   [2:0] y0_2_fu_458_p5;
wire   [2:0] y0_2_fu_458_p7;
wire  signed [2:0] y1_fu_482_p1;
wire   [2:0] y1_fu_482_p3;
wire   [2:0] y1_fu_482_p5;
wire   [2:0] y1_fu_482_p7;
wire  signed [1:0] zext_ln252_cast_fu_707_p1;
wire   [1:0] zext_ln252_cast_fu_707_p3;
wire   [1:0] zext_ln252_cast_fu_707_p5;
wire  signed [1:0] storemerge5_i_cast_cast_cast_fu_744_p1;
wire   [1:0] storemerge5_i_cast_cast_cast_fu_744_p3;
wire   [1:0] storemerge5_i_cast_cast_cast_fu_744_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp1_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp5_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp2_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp6_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp3_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp7_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp0_done_reg = 1'b0;
#0 x_fu_134 = 9'd0;
#0 y_fu_138 = 9'd0;
#0 indvar_flatten_fu_142 = 17'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) reconstruction_accel_sparsemux_9_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_9_3_8_1_1_U1(
    .din0(8'd0),
    .din1(8'd127),
    .din2(y0_2_fu_458_p6),
    .din3(zext_ln159_fu_424_p1),
    .def(y0_2_fu_458_p9),
    .sel(sel_tmp1_fu_449_p4),
    .dout(y0_2_fu_458_p11)
);

(* dissolve_hierarchy = "yes" *) reconstruction_accel_sparsemux_9_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_9_3_8_1_1_U2(
    .din0(8'd0),
    .din1(8'd127),
    .din2(zext_ln159_fu_424_p1),
    .din3(y1_fu_482_p8),
    .def(y1_fu_482_p9),
    .sel(sel_tmp1_fu_449_p4),
    .dout(y1_fu_482_p11)
);

reconstruction_accel_mul_3ns_8ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_3ns_8ns_11_1_1_U3(
    .din0(mul_ln314_fu_678_p0),
    .din1(mul_ln314_fu_678_p1),
    .dout(mul_ln314_fu_678_p2)
);

reconstruction_accel_mul_3ns_8ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_3ns_8ns_11_1_1_U4(
    .din0(mul_ln320_fu_696_p0),
    .din1(mul_ln320_fu_696_p1),
    .dout(mul_ln320_fu_696_p2)
);

(* dissolve_hierarchy = "yes" *) reconstruction_accel_sparsemux_7_2_2_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 2 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 2 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 2 ),
    .def_WIDTH( 2 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 2 ))
sparsemux_7_2_2_1_1_U5(
    .din0(2'd0),
    .din1(2'd3),
    .din2(2'd1),
    .def(zext_ln252_cast_fu_707_p7),
    .sel(zext_ln252_cast_fu_707_p8),
    .dout(zext_ln252_cast_fu_707_p9)
);

reconstruction_accel_mul_2ns_8ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
mul_2ns_8ns_10_1_1_U6(
    .din0(mul_ln320_1_fu_735_p0),
    .din1(mul_ln320_1_fu_735_p1),
    .dout(mul_ln320_1_fu_735_p2)
);

(* dissolve_hierarchy = "yes" *) reconstruction_accel_sparsemux_7_2_3_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 3 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 3 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 3 ),
    .def_WIDTH( 3 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 3 ))
sparsemux_7_2_3_1_1_U7(
    .din0(3'd4),
    .din1(3'd1),
    .din2(3'd3),
    .def(storemerge5_i_cast_cast_cast_fu_744_p7),
    .sel(sel_tmp2_reg_1012),
    .dout(storemerge5_i_cast_cast_cast_fu_744_p9)
);

reconstruction_accel_mul_11ns_3ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 14 ))
mul_11ns_3ns_14_1_1_U8(
    .din0(mul_ln327_fu_770_p0),
    .din1(mul_ln327_fu_770_p1),
    .dout(mul_ln327_fu_770_p2)
);

reconstruction_accel_mac_muladd_8ns_2ns_11ns_11_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 11 ))
mac_muladd_8ns_2ns_11ns_11_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_867_p0),
    .din1(grp_fu_867_p1),
    .din2(mul_ln314_reg_991),
    .ce(grp_fu_867_ce),
    .dout(grp_fu_867_p3)
);

reconstruction_accel_ama_addmuladd_10ns_11ns_2ns_14ns_14_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 2 ),
    .din3_WIDTH( 14 ),
    .dout_WIDTH( 14 ))
ama_addmuladd_10ns_11ns_2ns_14ns_14_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_874_p0),
    .din1(mul_ln320_reg_1007),
    .din2(grp_fu_874_p2),
    .din3(mul_ln327_fu_770_p2),
    .ce(grp_fu_874_ce),
    .dout(grp_fu_874_p4)
);

reconstruction_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp2)) begin
                ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp6_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp6_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp6)) begin
                ap_block_pp0_stage0_subdone_grp6_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp3_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp3_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp3)) begin
                ap_block_pp0_stage1_subdone_grp3_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp7_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp7_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp7)) begin
                ap_block_pp0_stage1_subdone_grp7_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp0)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp0)) begin
                ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp1_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp1)) begin
                ap_block_pp0_stage3_subdone_grp1_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp5_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp5_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp5)) begin
                ap_block_pp0_stage3_subdone_grp5_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage3)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage2))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage2))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((((trunc_ln281_fu_380_p1 == 8'd255) & (icmp_ln248_fu_286_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((trunc_ln281_fu_380_p1 == 8'd0) & (icmp_ln248_fu_286_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        ap_phi_reg_pp0_iter0_wx0_reg_224 <= 3'd4;
    end else if ((~(trunc_ln281_fu_380_p1 == 8'd255) & ~(trunc_ln281_fu_380_p1 == 8'd0) & (trunc_ln115_1_fu_384_p1 == 1'd1) & (icmp_ln248_fu_286_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_phi_reg_pp0_iter0_wx0_reg_224 <= 3'd3;
    end else if ((~(trunc_ln281_fu_380_p1 == 8'd255) & ~(trunc_ln281_fu_380_p1 == 8'd0) & (trunc_ln115_1_fu_384_p1 == 1'd0) & (icmp_ln248_fu_286_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_phi_reg_pp0_iter0_wx0_reg_224 <= 3'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((((trunc_ln281_fu_380_p1 == 8'd255) & (icmp_ln248_fu_286_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((trunc_ln281_fu_380_p1 == 8'd0) & (icmp_ln248_fu_286_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        ap_phi_reg_pp0_iter0_wx1_reg_244 <= 2'd0;
    end else if ((~(trunc_ln281_fu_380_p1 == 8'd255) & ~(trunc_ln281_fu_380_p1 == 8'd0) & (trunc_ln115_1_fu_384_p1 == 1'd1) & (icmp_ln248_fu_286_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_phi_reg_pp0_iter0_wx1_reg_244 <= 2'd1;
    end else if ((~(trunc_ln281_fu_380_p1 == 8'd255) & ~(trunc_ln281_fu_380_p1 == 8'd0) & (trunc_ln115_1_fu_384_p1 == 1'd0) & (icmp_ln248_fu_286_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_phi_reg_pp0_iter0_wx1_reg_244 <= 2'd3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_544)) begin
        if ((trunc_ln281_fu_380_p1 == 8'd255)) begin
                        ap_phi_reg_pp0_iter0_x0_2_reg_190[0] <= 1'b1;
            ap_phi_reg_pp0_iter0_x0_2_reg_190[1] <= 1'b1;
            ap_phi_reg_pp0_iter0_x0_2_reg_190[2] <= 1'b1;
            ap_phi_reg_pp0_iter0_x0_2_reg_190[3] <= 1'b1;
            ap_phi_reg_pp0_iter0_x0_2_reg_190[4] <= 1'b1;
            ap_phi_reg_pp0_iter0_x0_2_reg_190[5] <= 1'b1;
            ap_phi_reg_pp0_iter0_x0_2_reg_190[6] <= 1'b1;
        end else if ((trunc_ln281_fu_380_p1 == 8'd0)) begin
                        ap_phi_reg_pp0_iter0_x0_2_reg_190[0] <= 1'b0;
            ap_phi_reg_pp0_iter0_x0_2_reg_190[1] <= 1'b0;
            ap_phi_reg_pp0_iter0_x0_2_reg_190[2] <= 1'b0;
            ap_phi_reg_pp0_iter0_x0_2_reg_190[3] <= 1'b0;
            ap_phi_reg_pp0_iter0_x0_2_reg_190[4] <= 1'b0;
            ap_phi_reg_pp0_iter0_x0_2_reg_190[5] <= 1'b0;
            ap_phi_reg_pp0_iter0_x0_2_reg_190[6] <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_544)) begin
        if ((trunc_ln281_fu_380_p1 == 8'd255)) begin
                        ap_phi_reg_pp0_iter0_x1_reg_207[0] <= 1'b1;
            ap_phi_reg_pp0_iter0_x1_reg_207[1] <= 1'b1;
            ap_phi_reg_pp0_iter0_x1_reg_207[2] <= 1'b1;
            ap_phi_reg_pp0_iter0_x1_reg_207[3] <= 1'b1;
            ap_phi_reg_pp0_iter0_x1_reg_207[4] <= 1'b1;
            ap_phi_reg_pp0_iter0_x1_reg_207[5] <= 1'b1;
            ap_phi_reg_pp0_iter0_x1_reg_207[6] <= 1'b1;
        end else if ((trunc_ln281_fu_380_p1 == 8'd0)) begin
                        ap_phi_reg_pp0_iter0_x1_reg_207[0] <= 1'b0;
            ap_phi_reg_pp0_iter0_x1_reg_207[1] <= 1'b0;
            ap_phi_reg_pp0_iter0_x1_reg_207[2] <= 1'b0;
            ap_phi_reg_pp0_iter0_x1_reg_207[3] <= 1'b0;
            ap_phi_reg_pp0_iter0_x1_reg_207[4] <= 1'b0;
            ap_phi_reg_pp0_iter0_x1_reg_207[5] <= 1'b0;
            ap_phi_reg_pp0_iter0_x1_reg_207[6] <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        indvar_flatten_fu_142 <= 17'd0;
    end else if (((icmp_ln248_fu_286_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        indvar_flatten_fu_142 <= add_ln248_fu_292_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        x_fu_134 <= 9'd0;
    end else if (((icmp_ln248_fu_286_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        x_fu_134 <= add_ln272_fu_396_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        y_fu_138 <= 9'd0;
    end else if (((icmp_ln248_fu_286_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        y_fu_138 <= select_ln248_fu_324_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        add_ln332_reg_957 <= add_ln332_fu_539_p2;
        add_ln332_reg_957_pp0_iter1_reg <= add_ln332_reg_957;
        add_ln332_reg_957_pp0_iter2_reg <= add_ln332_reg_957_pp0_iter1_reg;
        add_ln332_reg_957_pp0_iter3_reg <= add_ln332_reg_957_pp0_iter2_reg;
        mul_ln320_reg_1007 <= mul_ln320_fu_696_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        and_ln125_1_reg_938 <= and_ln125_1_fu_374_p2;
        and_ln125_1_reg_938_pp0_iter1_reg <= and_ln125_1_reg_938;
        and_ln125_1_reg_938_pp0_iter2_reg <= and_ln125_1_reg_938_pp0_iter1_reg;
        and_ln125_1_reg_938_pp0_iter3_reg <= and_ln125_1_reg_938_pp0_iter2_reg;
        i_2_reg_933 <= {{select_ln248_fu_324_p3[7:1]}};
        icmp_ln248_reg_916 <= icmp_ln248_fu_286_p2;
        icmp_ln248_reg_916_pp0_iter1_reg <= icmp_ln248_reg_916;
        icmp_ln248_reg_916_pp0_iter2_reg <= icmp_ln248_reg_916_pp0_iter1_reg;
        icmp_ln248_reg_916_pp0_iter3_reg <= icmp_ln248_reg_916_pp0_iter2_reg;
        select_ln247_reg_920 <= select_ln247_fu_316_p3;
        trunc_ln115_1_reg_948 <= trunc_ln115_1_fu_384_p1;
        trunc_ln281_reg_944 <= trunc_ln281_fu_380_p1;
        trunc_ln332_reg_926 <= trunc_ln332_fu_332_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0))) begin
        ap_phi_reg_pp0_iter1_wx0_reg_224 <= ap_phi_reg_pp0_iter0_wx0_reg_224;
        ap_phi_reg_pp0_iter1_wx1_reg_244 <= ap_phi_reg_pp0_iter0_wx1_reg_244;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0))) begin
        ap_phi_reg_pp0_iter2_wx0_reg_224 <= ap_phi_reg_pp0_iter1_wx0_reg_224;
        ap_phi_reg_pp0_iter2_wx1_reg_244 <= ap_phi_reg_pp0_iter1_wx1_reg_244;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0))) begin
        ap_phi_reg_pp0_iter3_wx0_reg_224 <= ap_phi_reg_pp0_iter2_wx0_reg_224;
        ap_phi_reg_pp0_iter3_wx1_reg_244 <= ap_phi_reg_pp0_iter2_wx1_reg_244;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp4))) begin
        gmem0_addr_1_reg_968 <= add_ln297_fu_617_p2;
        gmem0_addr_2_reg_974 <= add_ln302_fu_638_p2;
        gmem0_addr_3_reg_980 <= add_ln307_fu_659_p2;
        gmem0_addr_reg_962 <= add_ln292_fu_596_p2;
        or_ln125_reg_952 <= or_ln125_fu_506_p2;
        or_ln125_reg_952_pp0_iter1_reg <= or_ln125_reg_952;
        or_ln125_reg_952_pp0_iter2_reg <= or_ln125_reg_952_pp0_iter1_reg;
        or_ln125_reg_952_pp0_iter3_reg <= or_ln125_reg_952_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        h0_reg_1022 <= grp_fu_867_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        mul_ln314_reg_991 <= mul_ln314_fu_678_p2;
        zext_ln275_1_reg_986[2 : 0] <= zext_ln275_1_fu_670_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp4)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp7) & (1'b0 == ap_block_pp0_stage1_subdone_grp7_done_reg)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp6) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001_grp5) & (1'b0 == ap_block_pp0_stage3_subdone_grp5_done_reg)))) begin
        reg_264 <= m_axi_gmem0_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0))) begin
        sel_tmp2_reg_1012 <= sel_tmp2_fu_701_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        zext_ln275_reg_996[1 : 0] <= zext_ln275_fu_684_p1[1 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln248_reg_916 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln248_reg_916_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
        ap_condition_exit_pp0_iter3_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to4 = 1'b1;
    end else begin
        ap_idle_pp0_1to4 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_441)) begin
        if ((trunc_ln115_1_reg_948 == 1'd1)) begin
            ap_phi_mux_x0_2_phi_fu_195_p8 = zext_ln159_1_fu_554_p1;
        end else if ((trunc_ln115_1_reg_948 == 1'd0)) begin
            ap_phi_mux_x0_2_phi_fu_195_p8 = x0_fu_560_p2;
        end else begin
            ap_phi_mux_x0_2_phi_fu_195_p8 = ap_phi_reg_pp0_iter0_x0_2_reg_190;
        end
    end else begin
        ap_phi_mux_x0_2_phi_fu_195_p8 = ap_phi_reg_pp0_iter0_x0_2_reg_190;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_441)) begin
        if ((trunc_ln115_1_reg_948 == 1'd1)) begin
            ap_phi_mux_x1_phi_fu_212_p8 = add_ln162_1_fu_567_p2;
        end else if ((trunc_ln115_1_reg_948 == 1'd0)) begin
            ap_phi_mux_x1_phi_fu_212_p8 = zext_ln159_1_fu_554_p1;
        end else begin
            ap_phi_mux_x1_phi_fu_212_p8 = ap_phi_reg_pp0_iter0_x1_reg_207;
        end
    end else begin
        ap_phi_mux_x1_phi_fu_212_p8 = ap_phi_reg_pp0_iter0_x1_reg_207;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        baseline_ticks_ce0_local = 1'b1;
    end else begin
        baseline_ticks_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        baseline_ticks_we0_local = 1'b1;
    end else begin
        baseline_ticks_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        branch_input_ce0_local = 1'b1;
    end else begin
        branch_input_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        branch_input_we0_local = 1'b1;
    end else begin
        branch_input_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_grp4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp3_done_reg) & (1'b0 == ap_block_pp0_stage1_grp3)) | ((icmp_ln248_reg_916 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_grp1) & (1'b0 == ap_block_pp0_stage3_subdone_grp1_done_reg)) | ((icmp_ln248_reg_916 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_grp2)))) begin
        gmem0_blk_n_AR = m_axi_gmem0_0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_grp4)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp7_done_reg) & (1'b0 == ap_block_pp0_stage1_grp7)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg) & (1'b0 == ap_block_pp0_stage0_grp6)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_grp5) & (1'b0 == ap_block_pp0_stage3_subdone_grp5_done_reg)))) begin
        gmem0_blk_n_R = m_axi_gmem0_0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0)))) begin
        grp_fu_867_ce = 1'b1;
    end else begin
        grp_fu_867_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0)))) begin
        grp_fu_874_ce = 1'b1;
    end else begin
        grp_fu_874_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp4))) begin
        m_axi_gmem0_0_ARADDR = gmem0_addr_3_reg_980;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp3) & (1'b0 == ap_block_pp0_stage1_subdone_grp3_done_reg))) begin
        m_axi_gmem0_0_ARADDR = gmem0_addr_2_reg_974;
    end else if (((icmp_ln248_reg_916 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg))) begin
        m_axi_gmem0_0_ARADDR = gmem0_addr_1_reg_968;
    end else if (((icmp_ln248_reg_916 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp1) & (1'b0 == ap_block_pp0_stage3_subdone_grp1_done_reg))) begin
        m_axi_gmem0_0_ARADDR = gmem0_addr_reg_962;
    end else begin
        m_axi_gmem0_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp3) & (1'b0 == ap_block_pp0_stage1_subdone_grp3_done_reg)) | ((icmp_ln248_reg_916 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp1) & (1'b0 == ap_block_pp0_stage3_subdone_grp1_done_reg)) | ((icmp_ln248_reg_916 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg)))) begin
        m_axi_gmem0_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem0_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp4)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp7) & (1'b0 == ap_block_pp0_stage1_subdone_grp7_done_reg)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp6) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001_grp5) & (1'b0 == ap_block_pp0_stage3_subdone_grp5_done_reg)))) begin
        m_axi_gmem0_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_idle_pp0_1to4 == 1'b1) & (ap_start_int == 1'b0)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage2))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln162_1_fu_567_p2 = (zext_ln159_1_fu_554_p1 + 8'd1);

assign add_ln248_fu_292_p2 = (indvar_flatten_fu_142 + 17'd1);

assign add_ln249_fu_304_p2 = (y_fu_138 + 9'd1);

assign add_ln272_fu_396_p2 = (select_ln247_fu_316_p3 + 9'd1);

assign add_ln292_fu_596_p2 = ($signed(sext_ln292_fu_592_p1) + $signed(input_r));

assign add_ln293_fu_586_p2 = ($signed(sext_ln275_fu_582_p1) + $signed(mul_cast_fu_520_p1));

assign add_ln297_fu_617_p2 = ($signed(sext_ln297_fu_613_p1) + $signed(input_r));

assign add_ln298_fu_607_p2 = ($signed(zext_ln275_3_fu_578_p1) + $signed(mul_cast_fu_520_p1));

assign add_ln302_fu_638_p2 = ($signed(sext_ln302_fu_634_p1) + $signed(input_r));

assign add_ln303_fu_628_p2 = ($signed(sext_ln275_fu_582_p1) + $signed(zext_ln269_fu_532_p1));

assign add_ln307_fu_659_p2 = (zext_ln307_fu_655_p1 + input_r);

assign add_ln308_fu_649_p2 = (zext_ln275_2_fu_574_p1 + mul9_fu_524_p3);

assign add_ln332_fu_539_p2 = (tmp_fu_417_p3 + zext_ln332_fu_536_p1);

assign and_ln125_1_fu_374_p2 = (xor_ln144_fu_340_p2 & and_ln125_fu_368_p2);

assign and_ln125_fu_368_p2 = (icmp_ln125_3_fu_362_p2 & icmp_ln125_2_fu_356_p2);

assign and_ln65_fu_812_p2 = (tmp_56_fu_793_p3 & icmp_ln64_fu_806_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_io_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg)) | ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_io_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp6 = ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_io_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg)) | ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_io_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp6 = ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((m_axi_gmem0_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp3_done_reg)) | ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp7_done_reg)));
end

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp3 = ((m_axi_gmem0_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp3_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp7 = ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp7_done_reg));
end

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((m_axi_gmem0_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp3_done_reg)) | ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp7_done_reg)));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp3 = ((m_axi_gmem0_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp3_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp7 = ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp7_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage2_11001 = (((m_axi_gmem0_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)));
end

assign ap_block_pp0_stage2_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001_grp4 = (((m_axi_gmem0_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)));
end

assign ap_block_pp0_stage2_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = (((m_axi_gmem0_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)));
end

assign ap_block_pp0_stage2_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = (((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp5_done_reg)) | ((1'b1 == ap_block_state4_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp1_done_reg)));
end

assign ap_block_pp0_stage3_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001_grp1 = ((1'b1 == ap_block_state4_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage3_11001_grp5 = ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp5_done_reg));
end

assign ap_block_pp0_stage3_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_grp5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = (((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp5_done_reg)) | ((1'b1 == ap_block_state4_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp1_done_reg)));
end

assign ap_block_pp0_stage3_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone_grp1 = ((1'b1 == ap_block_state4_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone_grp5 = ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp5_done_reg));
end

always @ (*) begin
    ap_block_state4_io_grp1 = ((icmp_ln248_reg_916 == 1'd0) & (m_axi_gmem0_0_ARREADY == 1'b0));
end

always @ (*) begin
    ap_block_state5_io_grp2 = ((icmp_ln248_reg_916 == 1'd0) & (m_axi_gmem0_0_ARREADY == 1'b0));
end

always @ (*) begin
    ap_condition_441 = (~(trunc_ln281_reg_944 == 8'd255) & ~(trunc_ln281_reg_944 == 8'd0) & (icmp_ln248_reg_916 == 1'd0));
end

always @ (*) begin
    ap_condition_544 = ((icmp_ln248_fu_286_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

assign ap_ready = ap_ready_sig;

assign baseline_ticks_address0 = zext_ln332_1_fu_776_p1;

assign baseline_ticks_ce0 = baseline_ticks_ce0_local;

assign baseline_ticks_d0 = grp_fu_874_p4;

assign baseline_ticks_we0 = baseline_ticks_we0_local;

assign branch_input_address0 = zext_ln332_1_fu_776_p1;

assign branch_input_ce0 = branch_input_ce0_local;

assign branch_input_d0 = select_ln76_fu_858_p3;

assign branch_input_we0 = branch_input_we0_local;

assign grp_fu_867_p0 = grp_fu_867_p00;

assign grp_fu_867_p00 = reg_264;

assign grp_fu_867_p1 = grp_fu_867_p10;

assign grp_fu_867_p10 = ap_phi_reg_pp0_iter3_wx1_reg_244;

assign grp_fu_874_p0 = grp_fu_874_p00;

assign grp_fu_874_p00 = mul_ln320_1_fu_735_p2;

assign grp_fu_874_p2 = grp_fu_874_p20;

assign grp_fu_874_p20 = zext_ln252_cast_fu_707_p9;

assign i_fu_545_p4 = {{select_ln247_reg_920[7:1]}};

assign icmp_ln125_1_fu_444_p2 = ((trunc_ln332_reg_926 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln125_2_fu_356_p2 = ((trunc_ln332_fu_332_p1 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln125_3_fu_362_p2 = ((trunc_ln332_fu_332_p1 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln125_fu_439_p2 = ((trunc_ln332_reg_926 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln248_fu_286_p2 = ((indvar_flatten_fu_142 == 17'd65536) ? 1'b1 : 1'b0);

assign icmp_ln271_fu_310_p2 = ((x_fu_134 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_800_p2 = ((remainder_fu_781_p1 > 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln64_fu_806_p2 = ((remainder_fu_781_p1 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln72_fu_848_p2 = ((tmp_57_fu_838_p4 != 2'd0) ? 1'b1 : 1'b0);

assign m_axi_gmem0_0_ARBURST = 2'd0;

assign m_axi_gmem0_0_ARCACHE = 4'd0;

assign m_axi_gmem0_0_ARID = 1'd0;

assign m_axi_gmem0_0_ARLEN = 64'd1;

assign m_axi_gmem0_0_ARLOCK = 2'd0;

assign m_axi_gmem0_0_ARPROT = 3'd0;

assign m_axi_gmem0_0_ARQOS = 4'd0;

assign m_axi_gmem0_0_ARREGION = 4'd0;

assign m_axi_gmem0_0_ARSIZE = 3'd0;

assign m_axi_gmem0_0_ARUSER = 1'd0;

assign m_axi_gmem0_0_AWADDR = 64'd0;

assign m_axi_gmem0_0_AWBURST = 2'd0;

assign m_axi_gmem0_0_AWCACHE = 4'd0;

assign m_axi_gmem0_0_AWID = 1'd0;

assign m_axi_gmem0_0_AWLEN = 32'd0;

assign m_axi_gmem0_0_AWLOCK = 2'd0;

assign m_axi_gmem0_0_AWPROT = 3'd0;

assign m_axi_gmem0_0_AWQOS = 4'd0;

assign m_axi_gmem0_0_AWREGION = 4'd0;

assign m_axi_gmem0_0_AWSIZE = 3'd0;

assign m_axi_gmem0_0_AWUSER = 1'd0;

assign m_axi_gmem0_0_AWVALID = 1'b0;

assign m_axi_gmem0_0_BREADY = 1'b0;

assign m_axi_gmem0_0_WDATA = 8'd0;

assign m_axi_gmem0_0_WID = 1'd0;

assign m_axi_gmem0_0_WLAST = 1'b0;

assign m_axi_gmem0_0_WSTRB = 1'd0;

assign m_axi_gmem0_0_WUSER = 1'd0;

assign m_axi_gmem0_0_WVALID = 1'b0;

assign mul9_fu_524_p3 = {{y1_fu_482_p11}, {7'd0}};

assign mul_cast_fu_520_p1 = $signed(mul_fu_512_p3);

assign mul_fu_512_p3 = {{y0_2_fu_458_p11}, {7'd0}};

assign mul_ln314_fu_678_p0 = mul_ln314_fu_678_p00;

assign mul_ln314_fu_678_p00 = ap_phi_reg_pp0_iter3_wx0_reg_224;

assign mul_ln314_fu_678_p1 = mul_ln314_fu_678_p10;

assign mul_ln314_fu_678_p10 = reg_264;

assign mul_ln320_1_fu_735_p0 = zext_ln275_reg_996;

assign mul_ln320_1_fu_735_p1 = mul_ln320_1_fu_735_p10;

assign mul_ln320_1_fu_735_p10 = reg_264;

assign mul_ln320_fu_696_p0 = zext_ln275_1_reg_986;

assign mul_ln320_fu_696_p1 = mul_ln320_fu_696_p10;

assign mul_ln320_fu_696_p10 = reg_264;

assign mul_ln327_fu_770_p0 = mul_ln327_fu_770_p00;

assign mul_ln327_fu_770_p00 = h0_reg_1022;

assign mul_ln327_fu_770_p1 = mul_ln327_fu_770_p10;

assign mul_ln327_fu_770_p10 = storemerge5_i_cast_cast_cast_fu_744_p9;

assign or_ln125_fu_506_p2 = (icmp_ln125_fu_439_p2 | icmp_ln125_1_fu_444_p2);

assign or_ln65_fu_824_p2 = (icmp_ln61_fu_800_p2 | and_ln65_fu_812_p2);

assign quotient_1_fu_830_p3 = ((or_ln65_fu_824_p2[0:0] == 1'b1) ? quotient_fu_818_p2 : trunc_ln2_fu_784_p4);

assign quotient_fu_818_p2 = (trunc_ln2_fu_784_p4 + 10'd1);

assign remainder_fu_781_p1 = grp_fu_874_p4[3:0];

assign sel_tmp1_fu_449_p4 = {{{icmp_ln125_fu_439_p2}, {icmp_ln125_1_fu_444_p2}}, {and_ln125_1_reg_938}};

assign sel_tmp2_fu_701_p3 = {{or_ln125_reg_952_pp0_iter3_reg}, {and_ln125_1_reg_938_pp0_iter3_reg}};

assign select_ln247_fu_316_p3 = ((icmp_ln271_fu_310_p2[0:0] == 1'b1) ? 9'd0 : x_fu_134);

assign select_ln248_fu_324_p3 = ((icmp_ln271_fu_310_p2[0:0] == 1'b1) ? add_ln249_fu_304_p2 : y_fu_138);

assign select_ln76_fu_858_p3 = ((icmp_ln72_fu_848_p2[0:0] == 1'b1) ? 8'd255 : trunc_ln76_fu_854_p1);

assign sext_ln275_fu_582_p1 = $signed(ap_phi_mux_x0_2_phi_fu_195_p8);

assign sext_ln292_fu_592_p1 = $signed(add_ln293_fu_586_p2);

assign sext_ln297_fu_613_p1 = $signed(add_ln298_fu_607_p2);

assign sext_ln302_fu_634_p1 = $signed(add_ln303_fu_628_p2);

assign storemerge5_i_cast_cast_cast_fu_744_p7 = 'bx;

assign tmp_56_fu_793_p3 = grp_fu_874_p4[32'd4];

assign tmp_57_fu_838_p4 = {{quotient_1_fu_830_p3[9:8]}};

assign tmp_fu_417_p3 = {{trunc_ln332_reg_926}, {8'd0}};

assign trunc_ln115_1_fu_384_p1 = select_ln247_fu_316_p3[0:0];

assign trunc_ln115_fu_336_p1 = select_ln248_fu_324_p3[0:0];

assign trunc_ln281_fu_380_p1 = select_ln247_fu_316_p3[7:0];

assign trunc_ln2_fu_784_p4 = {{grp_fu_874_p4[13:4]}};

assign trunc_ln332_fu_332_p1 = select_ln248_fu_324_p3[7:0];

assign trunc_ln76_fu_854_p1 = quotient_1_fu_830_p3[7:0];

assign x0_fu_560_p2 = (zext_ln159_1_fu_554_p1 + 8'd255);

assign xor_ln144_fu_340_p2 = (trunc_ln115_fu_336_p1 ^ 1'd1);

assign y0_2_fu_458_p6 = (zext_ln159_fu_424_p1 + 8'd255);

assign y0_2_fu_458_p9 = 'bx;

assign y1_fu_482_p8 = (zext_ln159_fu_424_p1 + 8'd1);

assign y1_fu_482_p9 = 'bx;

assign zext_ln159_1_fu_554_p1 = i_fu_545_p4;

assign zext_ln159_fu_424_p1 = i_2_reg_933;

assign zext_ln252_cast_fu_707_p7 = 'bx;

assign zext_ln252_cast_fu_707_p8 = {{or_ln125_reg_952_pp0_iter3_reg}, {and_ln125_1_reg_938_pp0_iter3_reg}};

assign zext_ln269_fu_532_p1 = mul9_fu_524_p3;

assign zext_ln275_1_fu_670_p1 = ap_phi_reg_pp0_iter3_wx0_reg_224;

assign zext_ln275_2_fu_574_p1 = ap_phi_mux_x1_phi_fu_212_p8;

assign zext_ln275_3_fu_578_p1 = ap_phi_mux_x1_phi_fu_212_p8;

assign zext_ln275_fu_684_p1 = ap_phi_reg_pp0_iter3_wx1_reg_244;

assign zext_ln307_fu_655_p1 = add_ln308_fu_649_p2;

assign zext_ln332_1_fu_776_p1 = add_ln332_reg_957_pp0_iter3_reg;

assign zext_ln332_fu_536_p1 = select_ln247_reg_920;

always @ (posedge ap_clk) begin
    zext_ln275_1_reg_986[10:3] <= 8'b00000000;
    zext_ln275_reg_996[9:2] <= 8'b00000000;
    ap_phi_reg_pp0_iter0_x0_2_reg_190[7] <= 1'b0;
    ap_phi_reg_pp0_iter0_x1_reg_207[7] <= 1'b0;
end

endmodule //reconstruction_accel_reconstruction_accel_Pipeline_BILINEAR_Y_BILINEAR_X
