// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
module reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_WpcA (
    address0, ce0, q0, 
    reset, clk);

parameter DataWidth = 8;
parameter AddressWidth = 4;
parameter AddressRange = 9;
 
input[AddressWidth-1:0] address0;
input ce0;
output reg[DataWidth-1:0] q0;

input reset;
input clk;

 
reg [DataWidth-1:0] rom0[0:AddressRange-1];


initial begin
     
    $readmemh("./reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_WpcA.dat", rom0);
end

  
always @(posedge clk) 
begin 
    if (ce0) 
    begin
        q0 <= rom0[address0];
    end
end


endmodule

