// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem1_0_AWVALID,
        m_axi_gmem1_0_AWREADY,
        m_axi_gmem1_0_AWADDR,
        m_axi_gmem1_0_AWID,
        m_axi_gmem1_0_AWLEN,
        m_axi_gmem1_0_AWSIZE,
        m_axi_gmem1_0_AWBURST,
        m_axi_gmem1_0_AWLOCK,
        m_axi_gmem1_0_AWCACHE,
        m_axi_gmem1_0_AWPROT,
        m_axi_gmem1_0_AWQOS,
        m_axi_gmem1_0_AWREGION,
        m_axi_gmem1_0_AWUSER,
        m_axi_gmem1_0_WVALID,
        m_axi_gmem1_0_WREADY,
        m_axi_gmem1_0_WDATA,
        m_axi_gmem1_0_WSTRB,
        m_axi_gmem1_0_WLAST,
        m_axi_gmem1_0_WID,
        m_axi_gmem1_0_WUSER,
        m_axi_gmem1_0_ARVALID,
        m_axi_gmem1_0_ARREADY,
        m_axi_gmem1_0_ARADDR,
        m_axi_gmem1_0_ARID,
        m_axi_gmem1_0_ARLEN,
        m_axi_gmem1_0_ARSIZE,
        m_axi_gmem1_0_ARBURST,
        m_axi_gmem1_0_ARLOCK,
        m_axi_gmem1_0_ARCACHE,
        m_axi_gmem1_0_ARPROT,
        m_axi_gmem1_0_ARQOS,
        m_axi_gmem1_0_ARREGION,
        m_axi_gmem1_0_ARUSER,
        m_axi_gmem1_0_RVALID,
        m_axi_gmem1_0_RREADY,
        m_axi_gmem1_0_RDATA,
        m_axi_gmem1_0_RLAST,
        m_axi_gmem1_0_RID,
        m_axi_gmem1_0_RFIFONUM,
        m_axi_gmem1_0_RUSER,
        m_axi_gmem1_0_RRESP,
        m_axi_gmem1_0_BVALID,
        m_axi_gmem1_0_BREADY,
        m_axi_gmem1_0_BRESP,
        m_axi_gmem1_0_BID,
        m_axi_gmem1_0_BUSER,
        sext_ln801,
        conv2_out_address0,
        conv2_out_ce0,
        conv2_out_q0,
        baseline_ticks_address0,
        baseline_ticks_ce0,
        baseline_ticks_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem1_0_AWVALID;
input   m_axi_gmem1_0_AWREADY;
output  [63:0] m_axi_gmem1_0_AWADDR;
output  [0:0] m_axi_gmem1_0_AWID;
output  [31:0] m_axi_gmem1_0_AWLEN;
output  [2:0] m_axi_gmem1_0_AWSIZE;
output  [1:0] m_axi_gmem1_0_AWBURST;
output  [1:0] m_axi_gmem1_0_AWLOCK;
output  [3:0] m_axi_gmem1_0_AWCACHE;
output  [2:0] m_axi_gmem1_0_AWPROT;
output  [3:0] m_axi_gmem1_0_AWQOS;
output  [3:0] m_axi_gmem1_0_AWREGION;
output  [0:0] m_axi_gmem1_0_AWUSER;
output   m_axi_gmem1_0_WVALID;
input   m_axi_gmem1_0_WREADY;
output  [15:0] m_axi_gmem1_0_WDATA;
output  [1:0] m_axi_gmem1_0_WSTRB;
output   m_axi_gmem1_0_WLAST;
output  [0:0] m_axi_gmem1_0_WID;
output  [0:0] m_axi_gmem1_0_WUSER;
output   m_axi_gmem1_0_ARVALID;
input   m_axi_gmem1_0_ARREADY;
output  [63:0] m_axi_gmem1_0_ARADDR;
output  [0:0] m_axi_gmem1_0_ARID;
output  [31:0] m_axi_gmem1_0_ARLEN;
output  [2:0] m_axi_gmem1_0_ARSIZE;
output  [1:0] m_axi_gmem1_0_ARBURST;
output  [1:0] m_axi_gmem1_0_ARLOCK;
output  [3:0] m_axi_gmem1_0_ARCACHE;
output  [2:0] m_axi_gmem1_0_ARPROT;
output  [3:0] m_axi_gmem1_0_ARQOS;
output  [3:0] m_axi_gmem1_0_ARREGION;
output  [0:0] m_axi_gmem1_0_ARUSER;
input   m_axi_gmem1_0_RVALID;
output   m_axi_gmem1_0_RREADY;
input  [15:0] m_axi_gmem1_0_RDATA;
input   m_axi_gmem1_0_RLAST;
input  [0:0] m_axi_gmem1_0_RID;
input  [9:0] m_axi_gmem1_0_RFIFONUM;
input  [0:0] m_axi_gmem1_0_RUSER;
input  [1:0] m_axi_gmem1_0_RRESP;
input   m_axi_gmem1_0_BVALID;
output   m_axi_gmem1_0_BREADY;
input  [1:0] m_axi_gmem1_0_BRESP;
input  [0:0] m_axi_gmem1_0_BID;
input  [0:0] m_axi_gmem1_0_BUSER;
input  [62:0] sext_ln801;
output  [15:0] conv2_out_address0;
output   conv2_out_ce0;
input  [63:0] conv2_out_q0;
output  [15:0] baseline_ticks_address0;
output   baseline_ticks_ce0;
input  [13:0] baseline_ticks_q0;

reg ap_idle;
reg m_axi_gmem1_0_WVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln828_1_reg_1414;
reg   [0:0] icmp_ln828_1_reg_1414_pp0_iter10_reg;
reg   [0:0] icmp_ln821_1_reg_1473;
reg   [0:0] icmp_ln821_1_reg_1473_pp0_iter10_reg;
reg    ap_predicate_op259_write_state12;
reg    ap_block_state12_io_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln803_fu_417_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [3:0] p_ZL13CONV3_WEIGHTS_0_address0;
wire   [7:0] p_ZL13CONV3_WEIGHTS_0_q0;
wire   [3:0] p_ZL13CONV3_WEIGHTS_1_address0;
wire  signed [6:0] p_ZL13CONV3_WEIGHTS_1_q0;
wire   [3:0] p_ZL13CONV3_WEIGHTS_2_address0;
wire   [7:0] p_ZL13CONV3_WEIGHTS_2_q0;
wire   [3:0] p_ZL13CONV3_WEIGHTS_3_address0;
wire   [7:0] p_ZL13CONV3_WEIGHTS_3_q0;
wire   [3:0] p_ZL13CONV3_WEIGHTS_4_address0;
wire  signed [4:0] p_ZL13CONV3_WEIGHTS_4_q0;
wire   [3:0] p_ZL13CONV3_WEIGHTS_5_address0;
wire   [7:0] p_ZL13CONV3_WEIGHTS_5_q0;
wire   [3:0] p_ZL13CONV3_WEIGHTS_6_address0;
wire   [7:0] p_ZL13CONV3_WEIGHTS_6_q0;
wire   [3:0] p_ZL13CONV3_WEIGHTS_7_address0;
wire  signed [6:0] p_ZL13CONV3_WEIGHTS_7_q0;
reg    gmem1_blk_n_W;
wire    ap_block_pp0_stage0_grp1;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln810_fu_435_p2;
reg   [0:0] icmp_ln810_reg_1386;
wire   [0:0] empty_fu_479_p2;
reg   [0:0] empty_reg_1391;
reg   [0:0] empty_reg_1391_pp0_iter2_reg;
reg   [0:0] empty_reg_1391_pp0_iter3_reg;
reg   [0:0] empty_reg_1391_pp0_iter4_reg;
reg   [0:0] empty_reg_1391_pp0_iter5_reg;
wire   [0:0] icmp_ln828_mid2121_fu_503_p2;
reg   [0:0] icmp_ln828_mid2121_reg_1397;
wire   [8:0] select_ln810_fu_509_p3;
reg   [8:0] select_ln810_reg_1402;
wire   [1:0] kx_mid2_fu_529_p3;
reg   [1:0] kx_mid2_reg_1408;
wire   [0:0] icmp_ln828_1_fu_543_p2;
reg   [0:0] icmp_ln828_1_reg_1414_pp0_iter2_reg;
reg   [0:0] icmp_ln828_1_reg_1414_pp0_iter3_reg;
reg   [0:0] icmp_ln828_1_reg_1414_pp0_iter4_reg;
reg   [0:0] icmp_ln828_1_reg_1414_pp0_iter5_reg;
reg   [0:0] icmp_ln828_1_reg_1414_pp0_iter6_reg;
reg   [0:0] icmp_ln828_1_reg_1414_pp0_iter7_reg;
reg   [0:0] icmp_ln828_1_reg_1414_pp0_iter8_reg;
reg   [0:0] icmp_ln828_1_reg_1414_pp0_iter9_reg;
wire   [15:0] add_ln1051_fu_660_p2;
reg   [15:0] add_ln1051_reg_1418;
reg   [15:0] add_ln1051_reg_1418_pp0_iter3_reg;
reg   [15:0] add_ln1051_reg_1418_pp0_iter4_reg;
reg   [15:0] add_ln1051_reg_1418_pp0_iter5_reg;
reg   [15:0] add_ln1051_reg_1418_pp0_iter6_reg;
reg   [15:0] add_ln1051_reg_1418_pp0_iter7_reg;
reg   [15:0] add_ln1051_reg_1418_pp0_iter8_reg;
wire   [0:0] icmp_ln843_fu_764_p2;
reg   [0:0] icmp_ln843_reg_1428;
reg   [0:0] icmp_ln843_reg_1428_pp0_iter3_reg;
reg   [0:0] icmp_ln843_reg_1428_pp0_iter4_reg;
reg   [0:0] icmp_ln843_reg_1428_pp0_iter5_reg;
reg   [0:0] icmp_ln843_reg_1428_pp0_iter6_reg;
wire   [0:0] icmp_ln821_1_fu_788_p2;
reg   [0:0] icmp_ln821_1_reg_1473_pp0_iter3_reg;
reg   [0:0] icmp_ln821_1_reg_1473_pp0_iter4_reg;
reg   [0:0] icmp_ln821_1_reg_1473_pp0_iter5_reg;
reg   [0:0] icmp_ln821_1_reg_1473_pp0_iter6_reg;
reg   [0:0] icmp_ln821_1_reg_1473_pp0_iter7_reg;
reg   [0:0] icmp_ln821_1_reg_1473_pp0_iter8_reg;
reg   [0:0] icmp_ln821_1_reg_1473_pp0_iter9_reg;
wire   [7:0] a0_fu_804_p1;
reg   [7:0] a0_reg_1477;
reg   [7:0] a2_reg_1482;
reg   [7:0] a2_reg_1482_pp0_iter4_reg;
reg   [7:0] a3_reg_1487;
reg   [7:0] a3_reg_1487_pp0_iter4_reg;
reg   [7:0] a5_reg_1492;
reg   [7:0] a6_reg_1497;
reg   [7:0] a6_reg_1497_pp0_iter4_reg;
reg  signed [7:0] p_ZL13CONV3_WEIGHTS_0_load_reg_1502;
reg   [7:0] p_ZL13CONV3_WEIGHTS_2_load_reg_1517;
reg  signed [7:0] p_ZL13CONV3_WEIGHTS_2_load_reg_1517_pp0_iter4_reg;
reg   [7:0] p_ZL13CONV3_WEIGHTS_3_load_reg_1522;
reg  signed [7:0] p_ZL13CONV3_WEIGHTS_3_load_reg_1522_pp0_iter4_reg;
reg  signed [7:0] p_ZL13CONV3_WEIGHTS_5_load_reg_1537;
reg   [7:0] p_ZL13CONV3_WEIGHTS_6_load_reg_1542;
reg  signed [7:0] p_ZL13CONV3_WEIGHTS_6_load_reg_1542_pp0_iter4_reg;
wire  signed [15:0] mul_ln1003_4_fu_928_p2;
wire   [31:0] acc_11_mid2117_fu_947_p3;
reg   [31:0] acc_11_mid2117_reg_1592;
wire  signed [16:0] grp_fu_1287_p3;
reg  signed [16:0] add_ln1003_1_reg_1598;
wire  signed [15:0] grp_fu_1295_p3;
reg  signed [15:0] add_ln1003_3_reg_1603;
wire  signed [16:0] grp_fu_1279_p3;
wire   [31:0] acc_1_fu_984_p3;
reg   [31:0] acc_1_reg_1613;
wire   [43:0] sub_ln1010_fu_1010_p2;
reg   [43:0] sub_ln1010_reg_1619;
wire   [23:0] residual_q_raw_fu_1100_p3;
reg   [23:0] residual_q_raw_reg_1624;
wire   [0:0] icmp_ln98_fu_1108_p2;
reg   [0:0] icmp_ln98_reg_1629;
wire   [0:0] icmp_ln102_fu_1124_p2;
reg   [0:0] icmp_ln102_reg_1635;
wire   [31:0] mul_ln1032_fu_1160_p2;
reg   [31:0] mul_ln1032_reg_1645;
wire   [11:0] select_ln1078_fu_1261_p3;
reg   [11:0] select_ln1078_reg_1652;
wire   [63:0] zext_ln855_fu_743_p1;
wire   [63:0] zext_ln897_fu_776_p1;
wire   [63:0] zext_ln1051_1_fu_1130_p1;
wire    ap_block_pp0_stage0_01001_grp1;
reg   [31:0] acc_fu_188;
reg   [31:0] ap_sig_allocacmp_acc_load;
wire    ap_loop_init;
reg   [1:0] kx_fu_192;
wire   [1:0] add_ln829_fu_537_p2;
wire    ap_block_pp0_stage0;
reg   [1:0] ky_fu_196;
wire   [1:0] select_ln821_fu_638_p3;
reg   [3:0] indvar_flatten107_fu_200;
wire   [3:0] select_ln821_1_fu_555_p3;
reg   [8:0] x_fu_204;
reg   [12:0] indvar_flatten122_fu_208;
wire   [12:0] select_ln810_1_fu_569_p3;
reg   [8:0] y_fu_212;
wire   [8:0] select_ln803_fu_614_p3;
reg   [19:0] indvar_flatten147_fu_216;
wire   [19:0] add_ln803_fu_423_p2;
reg    conv2_out_ce0_local;
reg    p_ZL13CONV3_WEIGHTS_0_ce0_local;
reg    p_ZL13CONV3_WEIGHTS_1_ce0_local;
reg    p_ZL13CONV3_WEIGHTS_2_ce0_local;
reg    p_ZL13CONV3_WEIGHTS_3_ce0_local;
reg    p_ZL13CONV3_WEIGHTS_4_ce0_local;
reg    p_ZL13CONV3_WEIGHTS_5_ce0_local;
reg    p_ZL13CONV3_WEIGHTS_6_ce0_local;
reg    p_ZL13CONV3_WEIGHTS_7_ce0_local;
reg    baseline_ticks_ce0_local;
wire   [0:0] icmp_ln821_fu_461_p2;
wire   [0:0] xor_ln802_fu_449_p2;
wire   [8:0] select_ln802_fu_441_p3;
wire   [0:0] and_ln802_1_fu_467_p2;
wire   [0:0] exitcond_flatten109_not_fu_485_p2;
wire   [0:0] icmp_ln828_fu_455_p2;
wire   [0:0] and_ln802_fu_497_p2;
wire   [0:0] not_exitcond_flatten109_mid2146_fu_491_p2;
wire   [8:0] add_ln811_fu_473_p2;
wire   [0:0] empty_47_fu_517_p2;
wire   [0:0] empty_48_fu_523_p2;
wire   [3:0] add_ln821_fu_549_p2;
wire   [12:0] add_ln810_fu_563_p2;
wire   [8:0] add_ln804_fu_608_p2;
wire   [1:0] ky_mid2114_fu_625_p3;
wire   [1:0] add_ln822_fu_632_p2;
wire   [7:0] trunc_ln811_fu_621_p1;
wire   [15:0] tmp_s_fu_645_p3;
wire   [15:0] zext_ln1051_fu_657_p1;
wire   [1:0] tmp112_fu_673_p2;
wire  signed [9:0] tmp112_cast_fu_679_p1;
wire   [9:0] zext_ln803_fu_653_p1;
wire   [9:0] empty_49_fu_683_p2;
wire   [7:0] trunc_ln855_fu_689_p1;
wire   [3:0] p_shl1_fu_701_p3;
wire   [3:0] zext_ln821_fu_669_p1;
wire   [1:0] add_ln838_fu_718_p2;
wire  signed [9:0] sext_ln838_fu_723_p1;
wire   [9:0] zext_ln810_fu_666_p1;
wire  signed [9:0] add_ln838_1_fu_727_p2;
wire   [15:0] tmp_1_fu_693_p3;
wire  signed [15:0] sext_ln855_fu_733_p1;
wire   [15:0] add_ln855_fu_737_p2;
wire   [9:0] or_ln843_fu_748_p2;
wire   [1:0] tmp_fu_754_p4;
wire   [3:0] zext_ln828_fu_715_p1;
wire   [3:0] empty_50_fu_709_p2;
wire   [3:0] add_ln886_fu_770_p2;
wire   [7:0] a1_fu_808_p3;
wire   [7:0] a4_fu_832_p3;
wire   [7:0] a7_fu_856_p3;
wire   [7:0] mul_ln1003_3_fu_918_p1;
wire  signed [15:0] mul_ln1003_3_fu_918_p2;
wire   [7:0] mul_ln1003_4_fu_928_p1;
wire   [7:0] mul_ln1003_7_fu_934_p1;
wire  signed [15:0] mul_ln1003_7_fu_934_p2;
wire  signed [31:0] sext_ln1003_8_fu_954_p1;
wire  signed [31:0] grp_fu_1303_p3;
wire  signed [16:0] grp_fu_1312_p3;
wire  signed [17:0] sext_ln1003_10_fu_965_p1;
wire  signed [17:0] sext_ln1003_9_fu_962_p1;
wire   [17:0] add_ln1003_6_fu_968_p2;
wire  signed [31:0] sext_ln1003_11_fu_974_p1;
(* use_dsp48 = "no" *) wire   [31:0] add_ln1003_2_fu_957_p2;
wire   [31:0] acc_2_fu_978_p2;
wire   [40:0] tmp_2_fu_998_p3;
wire   [43:0] p_shl_fu_990_p3;
wire  signed [43:0] sext_ln1010_fu_1006_p1;
wire   [37:0] tmp_3_fu_1021_p3;
wire  signed [43:0] sext_ln1010_1_fu_1028_p1;
wire   [32:0] tmp_4_fu_1037_p3;
wire   [43:0] sub_ln1010_1_fu_1032_p2;
wire  signed [43:0] sext_ln1010_2_fu_1044_p1;
wire   [43:0] add_ln1010_fu_1048_p2;
wire   [43:0] add_ln39_fu_1062_p2;
wire   [43:0] sub_ln45_fu_1078_p2;
wire   [23:0] trunc_ln46_7_fu_1084_p4;
wire   [0:0] tmp_5_fu_1054_p3;
wire   [23:0] sub_ln43_fu_1094_p2;
wire   [23:0] trunc_ln40_7_fu_1068_p4;
wire   [16:0] tmp_6_fu_1114_p4;
wire   [0:0] or_ln98_fu_1144_p2;
wire   [7:0] select_ln98_fu_1137_p3;
wire   [7:0] trunc_ln106_fu_1134_p1;
wire  signed [7:0] residual_q_fu_1148_p3;
wire   [24:0] mul_ln1032_fu_1160_p1;
wire   [31:0] sub_ln45_1_fu_1178_p2;
wire   [31:0] add_ln39_1_fu_1173_p2;
wire   [11:0] trunc_ln_fu_1183_p4;
wire   [0:0] tmp_7_fu_1166_p3;
wire   [11:0] sub_ln37_fu_1203_p2;
wire   [11:0] trunc_ln1_fu_1193_p4;
wire   [11:0] select_ln37_fu_1209_p3;
wire  signed [14:0] sext_ln1051_fu_1217_p1;
wire   [14:0] zext_ln1053_fu_1221_p1;
wire   [14:0] final_value_fu_1225_p2;
wire   [0:0] tmp_8_fu_1235_p3;
wire   [13:0] trunc_ln1048_fu_1231_p1;
wire   [13:0] final_value_1_fu_1243_p3;
wire   [0:0] icmp_ln1068_fu_1251_p2;
wire   [11:0] trunc_ln1078_fu_1257_p1;
wire   [7:0] grp_fu_1279_p0;
wire   [7:0] grp_fu_1287_p0;
wire   [7:0] grp_fu_1295_p0;
wire   [7:0] grp_fu_1303_p1;
wire  signed [31:0] grp_fu_1303_p2;
wire   [7:0] grp_fu_1312_p1;
reg    grp_fu_1279_ce;
reg    grp_fu_1287_ce;
reg    grp_fu_1295_ce;
reg    grp_fu_1303_ce;
reg    grp_fu_1312_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [14:0] grp_fu_1279_p00;
wire   [14:0] grp_fu_1287_p00;
wire   [12:0] grp_fu_1295_p00;
wire   [15:0] grp_fu_1303_p10;
wire   [15:0] grp_fu_1312_p10;
wire   [15:0] mul_ln1003_3_fu_918_p10;
wire   [15:0] mul_ln1003_4_fu_928_p10;
wire   [15:0] mul_ln1003_7_fu_934_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 acc_fu_188 = 32'd0;
#0 kx_fu_192 = 2'd0;
#0 ky_fu_196 = 2'd0;
#0 indvar_flatten107_fu_200 = 4'd0;
#0 x_fu_204 = 9'd0;
#0 indvar_flatten122_fu_208 = 13'd0;
#0 y_fu_212 = 9'd0;
#0 indvar_flatten147_fu_216 = 20'd0;
#0 ap_done_reg = 1'b0;
end

reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_Wncg #(
    .DataWidth( 8 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
p_ZL13CONV3_WEIGHTS_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL13CONV3_WEIGHTS_0_address0),
    .ce0(p_ZL13CONV3_WEIGHTS_0_ce0_local),
    .q0(p_ZL13CONV3_WEIGHTS_0_q0)
);

reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_Wocq #(
    .DataWidth( 7 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
p_ZL13CONV3_WEIGHTS_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL13CONV3_WEIGHTS_1_address0),
    .ce0(p_ZL13CONV3_WEIGHTS_1_ce0_local),
    .q0(p_ZL13CONV3_WEIGHTS_1_q0)
);

reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_WpcA #(
    .DataWidth( 8 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
p_ZL13CONV3_WEIGHTS_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL13CONV3_WEIGHTS_2_address0),
    .ce0(p_ZL13CONV3_WEIGHTS_2_ce0_local),
    .q0(p_ZL13CONV3_WEIGHTS_2_q0)
);

reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_WqcK #(
    .DataWidth( 8 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
p_ZL13CONV3_WEIGHTS_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL13CONV3_WEIGHTS_3_address0),
    .ce0(p_ZL13CONV3_WEIGHTS_3_ce0_local),
    .q0(p_ZL13CONV3_WEIGHTS_3_q0)
);

reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_WrcU #(
    .DataWidth( 5 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
p_ZL13CONV3_WEIGHTS_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL13CONV3_WEIGHTS_4_address0),
    .ce0(p_ZL13CONV3_WEIGHTS_4_ce0_local),
    .q0(p_ZL13CONV3_WEIGHTS_4_q0)
);

reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_Wsc4 #(
    .DataWidth( 8 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
p_ZL13CONV3_WEIGHTS_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL13CONV3_WEIGHTS_5_address0),
    .ce0(p_ZL13CONV3_WEIGHTS_5_ce0_local),
    .q0(p_ZL13CONV3_WEIGHTS_5_q0)
);

reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_Wtde #(
    .DataWidth( 8 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
p_ZL13CONV3_WEIGHTS_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL13CONV3_WEIGHTS_6_address0),
    .ce0(p_ZL13CONV3_WEIGHTS_6_ce0_local),
    .q0(p_ZL13CONV3_WEIGHTS_6_q0)
);

reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX_p_ZL13CONV3_Wudo #(
    .DataWidth( 7 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
p_ZL13CONV3_WEIGHTS_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL13CONV3_WEIGHTS_7_address0),
    .ce0(p_ZL13CONV3_WEIGHTS_7_ce0_local),
    .q0(p_ZL13CONV3_WEIGHTS_7_q0)
);

reconstruction_accel_mul_8s_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8ns_16_1_1_U137(
    .din0(p_ZL13CONV3_WEIGHTS_2_load_reg_1517_pp0_iter4_reg),
    .din1(mul_ln1003_3_fu_918_p1),
    .dout(mul_ln1003_3_fu_918_p2)
);

reconstruction_accel_mul_8s_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8ns_16_1_1_U138(
    .din0(p_ZL13CONV3_WEIGHTS_3_load_reg_1522_pp0_iter4_reg),
    .din1(mul_ln1003_4_fu_928_p1),
    .dout(mul_ln1003_4_fu_928_p2)
);

reconstruction_accel_mul_8s_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8ns_16_1_1_U139(
    .din0(p_ZL13CONV3_WEIGHTS_6_load_reg_1542_pp0_iter4_reg),
    .din1(mul_ln1003_7_fu_934_p1),
    .dout(mul_ln1003_7_fu_934_p2)
);

reconstruction_accel_mul_8s_25ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 25 ),
    .dout_WIDTH( 32 ))
mul_8s_25ns_32_1_1_U140(
    .din0(residual_q_fu_1148_p3),
    .din1(mul_ln1032_fu_1160_p1),
    .dout(mul_ln1032_fu_1160_p2)
);

reconstruction_accel_mac_muladd_8ns_7s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_7s_16s_17_4_1_U141(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1279_p0),
    .din1(p_ZL13CONV3_WEIGHTS_7_q0),
    .din2(mul_ln1003_7_fu_934_p2),
    .ce(grp_fu_1279_ce),
    .dout(grp_fu_1279_p3)
);

reconstruction_accel_mac_muladd_8ns_7s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_7s_16s_17_4_1_U142(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1287_p0),
    .din1(p_ZL13CONV3_WEIGHTS_1_q0),
    .din2(mul_ln1003_3_fu_918_p2),
    .ce(grp_fu_1287_ce),
    .dout(grp_fu_1287_p3)
);

reconstruction_accel_mac_muladd_8ns_5s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_5s_16s_16_4_1_U143(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1295_p0),
    .din1(p_ZL13CONV3_WEIGHTS_4_q0),
    .din2(mul_ln1003_4_fu_928_p2),
    .ce(grp_fu_1295_ce),
    .dout(grp_fu_1295_p3)
);

reconstruction_accel_mac_muladd_8s_8ns_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_8s_8ns_32s_32_4_1_U144(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL13CONV3_WEIGHTS_0_load_reg_1502),
    .din1(grp_fu_1303_p1),
    .din2(grp_fu_1303_p2),
    .ce(grp_fu_1303_ce),
    .dout(grp_fu_1303_p3)
);

reconstruction_accel_mac_muladd_8s_8ns_17s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8ns_17s_17_4_1_U145(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL13CONV3_WEIGHTS_5_load_reg_1537),
    .din1(grp_fu_1312_p1),
    .din2(grp_fu_1279_p3),
    .ce(grp_fu_1312_ce),
    .dout(grp_fu_1312_p3)
);

reconstruction_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter10_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_fu_188 <= 32'd4294965885;
        end else if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
            acc_fu_188 <= acc_1_fu_984_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten107_fu_200 <= 4'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln803_fu_417_p2 == 1'd0))) begin
            indvar_flatten107_fu_200 <= select_ln821_1_fu_555_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten122_fu_208 <= 13'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln803_fu_417_p2 == 1'd0))) begin
            indvar_flatten122_fu_208 <= select_ln810_1_fu_569_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten147_fu_216 <= 20'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln803_fu_417_p2 == 1'd0))) begin
            indvar_flatten147_fu_216 <= add_ln803_fu_423_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            kx_fu_192 <= 2'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln803_fu_417_p2 == 1'd0))) begin
            kx_fu_192 <= add_ln829_fu_537_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ky_fu_196 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            ky_fu_196 <= select_ln821_fu_638_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_fu_204 <= 9'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln803_fu_417_p2 == 1'd0))) begin
            x_fu_204 <= select_ln810_fu_509_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            y_fu_212 <= 9'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            y_fu_212 <= select_ln803_fu_614_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        a0_reg_1477 <= a0_fu_804_p1;
        a2_reg_1482 <= {{conv2_out_q0[23:16]}};
        a2_reg_1482_pp0_iter4_reg <= a2_reg_1482;
        a3_reg_1487 <= {{conv2_out_q0[31:24]}};
        a3_reg_1487_pp0_iter4_reg <= a3_reg_1487;
        a5_reg_1492 <= {{conv2_out_q0[47:40]}};
        a6_reg_1497 <= {{conv2_out_q0[55:48]}};
        a6_reg_1497_pp0_iter4_reg <= a6_reg_1497;
        acc_11_mid2117_reg_1592 <= acc_11_mid2117_fu_947_p3;
        acc_1_reg_1613 <= acc_1_fu_984_p3;
        add_ln1051_reg_1418 <= add_ln1051_fu_660_p2;
        add_ln1051_reg_1418_pp0_iter3_reg <= add_ln1051_reg_1418;
        add_ln1051_reg_1418_pp0_iter4_reg <= add_ln1051_reg_1418_pp0_iter3_reg;
        add_ln1051_reg_1418_pp0_iter5_reg <= add_ln1051_reg_1418_pp0_iter4_reg;
        add_ln1051_reg_1418_pp0_iter6_reg <= add_ln1051_reg_1418_pp0_iter5_reg;
        add_ln1051_reg_1418_pp0_iter7_reg <= add_ln1051_reg_1418_pp0_iter6_reg;
        add_ln1051_reg_1418_pp0_iter8_reg <= add_ln1051_reg_1418_pp0_iter7_reg;
        icmp_ln102_reg_1635 <= icmp_ln102_fu_1124_p2;
        icmp_ln821_1_reg_1473 <= icmp_ln821_1_fu_788_p2;
        icmp_ln821_1_reg_1473_pp0_iter10_reg <= icmp_ln821_1_reg_1473_pp0_iter9_reg;
        icmp_ln821_1_reg_1473_pp0_iter3_reg <= icmp_ln821_1_reg_1473;
        icmp_ln821_1_reg_1473_pp0_iter4_reg <= icmp_ln821_1_reg_1473_pp0_iter3_reg;
        icmp_ln821_1_reg_1473_pp0_iter5_reg <= icmp_ln821_1_reg_1473_pp0_iter4_reg;
        icmp_ln821_1_reg_1473_pp0_iter6_reg <= icmp_ln821_1_reg_1473_pp0_iter5_reg;
        icmp_ln821_1_reg_1473_pp0_iter7_reg <= icmp_ln821_1_reg_1473_pp0_iter6_reg;
        icmp_ln821_1_reg_1473_pp0_iter8_reg <= icmp_ln821_1_reg_1473_pp0_iter7_reg;
        icmp_ln821_1_reg_1473_pp0_iter9_reg <= icmp_ln821_1_reg_1473_pp0_iter8_reg;
        icmp_ln843_reg_1428 <= icmp_ln843_fu_764_p2;
        icmp_ln843_reg_1428_pp0_iter3_reg <= icmp_ln843_reg_1428;
        icmp_ln843_reg_1428_pp0_iter4_reg <= icmp_ln843_reg_1428_pp0_iter3_reg;
        icmp_ln843_reg_1428_pp0_iter5_reg <= icmp_ln843_reg_1428_pp0_iter4_reg;
        icmp_ln843_reg_1428_pp0_iter6_reg <= icmp_ln843_reg_1428_pp0_iter5_reg;
        icmp_ln98_reg_1629 <= icmp_ln98_fu_1108_p2;
        mul_ln1032_reg_1645 <= mul_ln1032_fu_1160_p2;
        p_ZL13CONV3_WEIGHTS_0_load_reg_1502 <= p_ZL13CONV3_WEIGHTS_0_q0;
        p_ZL13CONV3_WEIGHTS_2_load_reg_1517 <= p_ZL13CONV3_WEIGHTS_2_q0;
        p_ZL13CONV3_WEIGHTS_2_load_reg_1517_pp0_iter4_reg <= p_ZL13CONV3_WEIGHTS_2_load_reg_1517;
        p_ZL13CONV3_WEIGHTS_3_load_reg_1522 <= p_ZL13CONV3_WEIGHTS_3_q0;
        p_ZL13CONV3_WEIGHTS_3_load_reg_1522_pp0_iter4_reg <= p_ZL13CONV3_WEIGHTS_3_load_reg_1522;
        p_ZL13CONV3_WEIGHTS_5_load_reg_1537 <= p_ZL13CONV3_WEIGHTS_5_q0;
        p_ZL13CONV3_WEIGHTS_6_load_reg_1542 <= p_ZL13CONV3_WEIGHTS_6_q0;
        p_ZL13CONV3_WEIGHTS_6_load_reg_1542_pp0_iter4_reg <= p_ZL13CONV3_WEIGHTS_6_load_reg_1542;
        residual_q_raw_reg_1624 <= residual_q_raw_fu_1100_p3;
        select_ln1078_reg_1652 <= select_ln1078_fu_1261_p3;
        sub_ln1010_reg_1619[43 : 9] <= sub_ln1010_fu_1010_p2[43 : 9];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        add_ln1003_1_reg_1598 <= grp_fu_1287_p3;
        add_ln1003_3_reg_1603 <= grp_fu_1295_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        empty_reg_1391_pp0_iter2_reg <= empty_reg_1391;
        empty_reg_1391_pp0_iter3_reg <= empty_reg_1391_pp0_iter2_reg;
        empty_reg_1391_pp0_iter4_reg <= empty_reg_1391_pp0_iter3_reg;
        empty_reg_1391_pp0_iter5_reg <= empty_reg_1391_pp0_iter4_reg;
        icmp_ln828_1_reg_1414_pp0_iter10_reg <= icmp_ln828_1_reg_1414_pp0_iter9_reg;
        icmp_ln828_1_reg_1414_pp0_iter2_reg <= icmp_ln828_1_reg_1414;
        icmp_ln828_1_reg_1414_pp0_iter3_reg <= icmp_ln828_1_reg_1414_pp0_iter2_reg;
        icmp_ln828_1_reg_1414_pp0_iter4_reg <= icmp_ln828_1_reg_1414_pp0_iter3_reg;
        icmp_ln828_1_reg_1414_pp0_iter5_reg <= icmp_ln828_1_reg_1414_pp0_iter4_reg;
        icmp_ln828_1_reg_1414_pp0_iter6_reg <= icmp_ln828_1_reg_1414_pp0_iter5_reg;
        icmp_ln828_1_reg_1414_pp0_iter7_reg <= icmp_ln828_1_reg_1414_pp0_iter6_reg;
        icmp_ln828_1_reg_1414_pp0_iter8_reg <= icmp_ln828_1_reg_1414_pp0_iter7_reg;
        icmp_ln828_1_reg_1414_pp0_iter9_reg <= icmp_ln828_1_reg_1414_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        empty_reg_1391 <= empty_fu_479_p2;
        icmp_ln810_reg_1386 <= icmp_ln810_fu_435_p2;
        icmp_ln828_1_reg_1414 <= icmp_ln828_1_fu_543_p2;
        icmp_ln828_mid2121_reg_1397 <= icmp_ln828_mid2121_fu_503_p2;
        kx_mid2_reg_1408 <= kx_mid2_fu_529_p3;
        select_ln810_reg_1402 <= select_ln810_fu_509_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln803_fu_417_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter10_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        ap_sig_allocacmp_acc_load = acc_1_fu_984_p3;
    end else begin
        ap_sig_allocacmp_acc_load = acc_fu_188;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        baseline_ticks_ce0_local = 1'b1;
    end else begin
        baseline_ticks_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        conv2_out_ce0_local = 1'b1;
    end else begin
        conv2_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (ap_predicate_op259_write_state12 == 1'b1))) begin
        gmem1_blk_n_W = m_axi_gmem1_0_WREADY;
    end else begin
        gmem1_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_1279_ce = 1'b1;
    end else begin
        grp_fu_1279_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_1287_ce = 1'b1;
    end else begin
        grp_fu_1287_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_1295_ce = 1'b1;
    end else begin
        grp_fu_1295_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_1303_ce = 1'b1;
    end else begin
        grp_fu_1303_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_1312_ce = 1'b1;
    end else begin
        grp_fu_1312_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_predicate_op259_write_state12 == 1'b1))) begin
        m_axi_gmem1_0_WVALID = 1'b1;
    end else begin
        m_axi_gmem1_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        p_ZL13CONV3_WEIGHTS_0_ce0_local = 1'b1;
    end else begin
        p_ZL13CONV3_WEIGHTS_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        p_ZL13CONV3_WEIGHTS_1_ce0_local = 1'b1;
    end else begin
        p_ZL13CONV3_WEIGHTS_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        p_ZL13CONV3_WEIGHTS_2_ce0_local = 1'b1;
    end else begin
        p_ZL13CONV3_WEIGHTS_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        p_ZL13CONV3_WEIGHTS_3_ce0_local = 1'b1;
    end else begin
        p_ZL13CONV3_WEIGHTS_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        p_ZL13CONV3_WEIGHTS_4_ce0_local = 1'b1;
    end else begin
        p_ZL13CONV3_WEIGHTS_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        p_ZL13CONV3_WEIGHTS_5_ce0_local = 1'b1;
    end else begin
        p_ZL13CONV3_WEIGHTS_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        p_ZL13CONV3_WEIGHTS_6_ce0_local = 1'b1;
    end else begin
        p_ZL13CONV3_WEIGHTS_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        p_ZL13CONV3_WEIGHTS_7_ce0_local = 1'b1;
    end else begin
        p_ZL13CONV3_WEIGHTS_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a0_fu_804_p1 = conv2_out_q0[7:0];

assign a1_fu_808_p3 = {{conv2_out_q0[15:8]}};

assign a4_fu_832_p3 = {{conv2_out_q0[39:32]}};

assign a7_fu_856_p3 = {{conv2_out_q0[63:56]}};

assign acc_11_mid2117_fu_947_p3 = ((empty_reg_1391_pp0_iter5_reg[0:0] == 1'b1) ? 32'd4294965885 : ap_sig_allocacmp_acc_load);

assign acc_1_fu_984_p3 = ((icmp_ln843_reg_1428_pp0_iter6_reg[0:0] == 1'b1) ? acc_2_fu_978_p2 : acc_11_mid2117_reg_1592);

assign acc_2_fu_978_p2 = ($signed(sext_ln1003_11_fu_974_p1) + $signed(add_ln1003_2_fu_957_p2));

assign add_ln1003_2_fu_957_p2 = ($signed(sext_ln1003_8_fu_954_p1) + $signed(grp_fu_1303_p3));

assign add_ln1003_6_fu_968_p2 = ($signed(sext_ln1003_10_fu_965_p1) + $signed(sext_ln1003_9_fu_962_p1));

assign add_ln1010_fu_1048_p2 = ($signed(sub_ln1010_1_fu_1032_p2) + $signed(sext_ln1010_2_fu_1044_p1));

assign add_ln1051_fu_660_p2 = (tmp_s_fu_645_p3 + zext_ln1051_fu_657_p1);

assign add_ln39_1_fu_1173_p2 = (mul_ln1032_reg_1645 + 32'd524288);

assign add_ln39_fu_1062_p2 = (add_ln1010_fu_1048_p2 + 44'd524288);

assign add_ln803_fu_423_p2 = (indvar_flatten147_fu_216 + 20'd1);

assign add_ln804_fu_608_p2 = (y_fu_212 + 9'd1);

assign add_ln810_fu_563_p2 = (indvar_flatten122_fu_208 + 13'd1);

assign add_ln811_fu_473_p2 = (select_ln802_fu_441_p3 + 9'd1);

assign add_ln821_fu_549_p2 = (indvar_flatten107_fu_200 + 4'd1);

assign add_ln822_fu_632_p2 = (ky_mid2114_fu_625_p3 + 2'd1);

assign add_ln829_fu_537_p2 = (kx_mid2_fu_529_p3 + 2'd1);

assign add_ln838_1_fu_727_p2 = ($signed(sext_ln838_fu_723_p1) + $signed(zext_ln810_fu_666_p1));

assign add_ln838_fu_718_p2 = ($signed(kx_mid2_reg_1408) + $signed(2'd3));

assign add_ln855_fu_737_p2 = ($signed(tmp_1_fu_693_p3) + $signed(sext_ln855_fu_733_p1));

assign add_ln886_fu_770_p2 = (zext_ln828_fu_715_p1 + empty_50_fu_709_p2);

assign and_ln802_1_fu_467_p2 = (xor_ln802_fu_449_p2 & icmp_ln821_fu_461_p2);

assign and_ln802_fu_497_p2 = (xor_ln802_fu_449_p2 & icmp_ln828_fu_455_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_io_grp1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_io_grp1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_io_grp1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state12_io_grp1 = ((m_axi_gmem1_0_WREADY == 1'b0) & (ap_predicate_op259_write_state12 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

always @ (*) begin
    ap_predicate_op259_write_state12 = ((icmp_ln821_1_reg_1473_pp0_iter10_reg == 1'd1) & (icmp_ln828_1_reg_1414_pp0_iter10_reg == 1'd1));
end

assign ap_ready = ap_ready_sig;

assign baseline_ticks_address0 = zext_ln1051_1_fu_1130_p1;

assign baseline_ticks_ce0 = baseline_ticks_ce0_local;

assign conv2_out_address0 = zext_ln855_fu_743_p1;

assign conv2_out_ce0 = conv2_out_ce0_local;

assign empty_47_fu_517_p2 = (icmp_ln828_mid2121_fu_503_p2 | and_ln802_1_fu_467_p2);

assign empty_48_fu_523_p2 = (icmp_ln810_fu_435_p2 | empty_47_fu_517_p2);

assign empty_49_fu_683_p2 = ($signed(tmp112_cast_fu_679_p1) + $signed(zext_ln803_fu_653_p1));

assign empty_50_fu_709_p2 = (p_shl1_fu_701_p3 - zext_ln821_fu_669_p1);

assign empty_fu_479_p2 = (icmp_ln810_fu_435_p2 | and_ln802_1_fu_467_p2);

assign exitcond_flatten109_not_fu_485_p2 = (icmp_ln821_fu_461_p2 ^ 1'd1);

assign final_value_1_fu_1243_p3 = ((tmp_8_fu_1235_p3[0:0] == 1'b1) ? 14'd0 : trunc_ln1048_fu_1231_p1);

assign final_value_fu_1225_p2 = ($signed(sext_ln1051_fu_1217_p1) + $signed(zext_ln1053_fu_1221_p1));

assign grp_fu_1279_p0 = grp_fu_1279_p00;

assign grp_fu_1279_p00 = a7_fu_856_p3;

assign grp_fu_1287_p0 = grp_fu_1287_p00;

assign grp_fu_1287_p00 = a1_fu_808_p3;

assign grp_fu_1295_p0 = grp_fu_1295_p00;

assign grp_fu_1295_p00 = a4_fu_832_p3;

assign grp_fu_1303_p1 = grp_fu_1303_p10;

assign grp_fu_1303_p10 = a0_reg_1477;

assign grp_fu_1303_p2 = ((empty_reg_1391_pp0_iter5_reg[0:0] == 1'b1) ? 32'd4294965885 : ap_sig_allocacmp_acc_load);

assign grp_fu_1312_p1 = grp_fu_1312_p10;

assign grp_fu_1312_p10 = a5_reg_1492;

assign icmp_ln102_fu_1124_p2 = (($signed(tmp_6_fu_1114_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1068_fu_1251_p2 = ((final_value_1_fu_1243_p3 > 14'd4080) ? 1'b1 : 1'b0);

assign icmp_ln803_fu_417_p2 = ((indvar_flatten147_fu_216 == 20'd589824) ? 1'b1 : 1'b0);

assign icmp_ln810_fu_435_p2 = ((indvar_flatten122_fu_208 == 13'd2304) ? 1'b1 : 1'b0);

assign icmp_ln821_1_fu_788_p2 = ((select_ln821_fu_638_p3 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln821_fu_461_p2 = ((indvar_flatten107_fu_200 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln828_1_fu_543_p2 = ((add_ln829_fu_537_p2 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln828_fu_455_p2 = ((kx_fu_192 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln828_mid2121_fu_503_p2 = (not_exitcond_flatten109_mid2146_fu_491_p2 & and_ln802_fu_497_p2);

assign icmp_ln843_fu_764_p2 = ((tmp_fu_754_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln98_fu_1108_p2 = (($signed(residual_q_raw_fu_1100_p3) < $signed(24'd16777089)) ? 1'b1 : 1'b0);

assign kx_mid2_fu_529_p3 = ((empty_48_fu_523_p2[0:0] == 1'b1) ? 2'd0 : kx_fu_192);

assign ky_mid2114_fu_625_p3 = ((empty_reg_1391[0:0] == 1'b1) ? 2'd0 : ky_fu_196);

assign m_axi_gmem1_0_ARADDR = 64'd0;

assign m_axi_gmem1_0_ARBURST = 2'd0;

assign m_axi_gmem1_0_ARCACHE = 4'd0;

assign m_axi_gmem1_0_ARID = 1'd0;

assign m_axi_gmem1_0_ARLEN = 32'd0;

assign m_axi_gmem1_0_ARLOCK = 2'd0;

assign m_axi_gmem1_0_ARPROT = 3'd0;

assign m_axi_gmem1_0_ARQOS = 4'd0;

assign m_axi_gmem1_0_ARREGION = 4'd0;

assign m_axi_gmem1_0_ARSIZE = 3'd0;

assign m_axi_gmem1_0_ARUSER = 1'd0;

assign m_axi_gmem1_0_ARVALID = 1'b0;

assign m_axi_gmem1_0_AWADDR = 64'd0;

assign m_axi_gmem1_0_AWBURST = 2'd0;

assign m_axi_gmem1_0_AWCACHE = 4'd0;

assign m_axi_gmem1_0_AWID = 1'd0;

assign m_axi_gmem1_0_AWLEN = 32'd0;

assign m_axi_gmem1_0_AWLOCK = 2'd0;

assign m_axi_gmem1_0_AWPROT = 3'd0;

assign m_axi_gmem1_0_AWQOS = 4'd0;

assign m_axi_gmem1_0_AWREGION = 4'd0;

assign m_axi_gmem1_0_AWSIZE = 3'd0;

assign m_axi_gmem1_0_AWUSER = 1'd0;

assign m_axi_gmem1_0_AWVALID = 1'b0;

assign m_axi_gmem1_0_BREADY = 1'b0;

assign m_axi_gmem1_0_RREADY = 1'b0;

assign m_axi_gmem1_0_WDATA = select_ln1078_reg_1652;

assign m_axi_gmem1_0_WID = 1'd0;

assign m_axi_gmem1_0_WLAST = 1'b0;

assign m_axi_gmem1_0_WSTRB = 2'd3;

assign m_axi_gmem1_0_WUSER = 1'd0;

assign mul_ln1003_3_fu_918_p1 = mul_ln1003_3_fu_918_p10;

assign mul_ln1003_3_fu_918_p10 = a2_reg_1482_pp0_iter4_reg;

assign mul_ln1003_4_fu_928_p1 = mul_ln1003_4_fu_928_p10;

assign mul_ln1003_4_fu_928_p10 = a3_reg_1487_pp0_iter4_reg;

assign mul_ln1003_7_fu_934_p1 = mul_ln1003_7_fu_934_p10;

assign mul_ln1003_7_fu_934_p10 = a6_reg_1497_pp0_iter4_reg;

assign mul_ln1032_fu_1160_p1 = 32'd9446373;

assign not_exitcond_flatten109_mid2146_fu_491_p2 = (icmp_ln810_fu_435_p2 | exitcond_flatten109_not_fu_485_p2);

assign or_ln843_fu_748_p2 = (empty_49_fu_683_p2 | add_ln838_1_fu_727_p2);

assign or_ln98_fu_1144_p2 = (icmp_ln98_reg_1629 | icmp_ln102_reg_1635);

assign p_ZL13CONV3_WEIGHTS_0_address0 = zext_ln897_fu_776_p1;

assign p_ZL13CONV3_WEIGHTS_1_address0 = zext_ln897_fu_776_p1;

assign p_ZL13CONV3_WEIGHTS_2_address0 = zext_ln897_fu_776_p1;

assign p_ZL13CONV3_WEIGHTS_3_address0 = zext_ln897_fu_776_p1;

assign p_ZL13CONV3_WEIGHTS_4_address0 = zext_ln897_fu_776_p1;

assign p_ZL13CONV3_WEIGHTS_5_address0 = zext_ln897_fu_776_p1;

assign p_ZL13CONV3_WEIGHTS_6_address0 = zext_ln897_fu_776_p1;

assign p_ZL13CONV3_WEIGHTS_7_address0 = zext_ln897_fu_776_p1;

assign p_shl1_fu_701_p3 = {{select_ln821_fu_638_p3}, {2'd0}};

assign p_shl_fu_990_p3 = {{acc_1_fu_984_p3}, {12'd0}};

assign residual_q_fu_1148_p3 = ((or_ln98_fu_1144_p2[0:0] == 1'b1) ? select_ln98_fu_1137_p3 : trunc_ln106_fu_1134_p1);

assign residual_q_raw_fu_1100_p3 = ((tmp_5_fu_1054_p3[0:0] == 1'b1) ? sub_ln43_fu_1094_p2 : trunc_ln40_7_fu_1068_p4);

assign select_ln1078_fu_1261_p3 = ((icmp_ln1068_fu_1251_p2[0:0] == 1'b1) ? 12'd4080 : trunc_ln1078_fu_1257_p1);

assign select_ln37_fu_1209_p3 = ((tmp_7_fu_1166_p3[0:0] == 1'b1) ? sub_ln37_fu_1203_p2 : trunc_ln1_fu_1193_p4);

assign select_ln802_fu_441_p3 = ((icmp_ln810_fu_435_p2[0:0] == 1'b1) ? 9'd0 : x_fu_204);

assign select_ln803_fu_614_p3 = ((icmp_ln810_reg_1386[0:0] == 1'b1) ? add_ln804_fu_608_p2 : y_fu_212);

assign select_ln810_1_fu_569_p3 = ((icmp_ln810_fu_435_p2[0:0] == 1'b1) ? 13'd1 : add_ln810_fu_563_p2);

assign select_ln810_fu_509_p3 = ((and_ln802_1_fu_467_p2[0:0] == 1'b1) ? add_ln811_fu_473_p2 : select_ln802_fu_441_p3);

assign select_ln821_1_fu_555_p3 = ((empty_fu_479_p2[0:0] == 1'b1) ? 4'd1 : add_ln821_fu_549_p2);

assign select_ln821_fu_638_p3 = ((icmp_ln828_mid2121_reg_1397[0:0] == 1'b1) ? add_ln822_fu_632_p2 : ky_mid2114_fu_625_p3);

assign select_ln98_fu_1137_p3 = ((icmp_ln98_reg_1629[0:0] == 1'b1) ? 8'd129 : 8'd127);

assign sext_ln1003_10_fu_965_p1 = grp_fu_1312_p3;

assign sext_ln1003_11_fu_974_p1 = $signed(add_ln1003_6_fu_968_p2);

assign sext_ln1003_8_fu_954_p1 = add_ln1003_1_reg_1598;

assign sext_ln1003_9_fu_962_p1 = add_ln1003_3_reg_1603;

assign sext_ln1010_1_fu_1028_p1 = $signed(tmp_3_fu_1021_p3);

assign sext_ln1010_2_fu_1044_p1 = $signed(tmp_4_fu_1037_p3);

assign sext_ln1010_fu_1006_p1 = $signed(tmp_2_fu_998_p3);

assign sext_ln1051_fu_1217_p1 = $signed(select_ln37_fu_1209_p3);

assign sext_ln838_fu_723_p1 = $signed(add_ln838_fu_718_p2);

assign sext_ln855_fu_733_p1 = add_ln838_1_fu_727_p2;

assign sub_ln1010_1_fu_1032_p2 = ($signed(sub_ln1010_reg_1619) - $signed(sext_ln1010_1_fu_1028_p1));

assign sub_ln1010_fu_1010_p2 = ($signed(p_shl_fu_990_p3) - $signed(sext_ln1010_fu_1006_p1));

assign sub_ln37_fu_1203_p2 = (12'd0 - trunc_ln_fu_1183_p4);

assign sub_ln43_fu_1094_p2 = (24'd0 - trunc_ln46_7_fu_1084_p4);

assign sub_ln45_1_fu_1178_p2 = (32'd524288 - mul_ln1032_reg_1645);

assign sub_ln45_fu_1078_p2 = (44'd524288 - add_ln1010_fu_1048_p2);

assign tmp112_cast_fu_679_p1 = $signed(tmp112_fu_673_p2);

assign tmp112_fu_673_p2 = ($signed(select_ln821_fu_638_p3) + $signed(2'd3));

assign tmp_1_fu_693_p3 = {{trunc_ln855_fu_689_p1}, {8'd0}};

assign tmp_2_fu_998_p3 = {{acc_1_fu_984_p3}, {9'd0}};

assign tmp_3_fu_1021_p3 = {{acc_1_reg_1613}, {6'd0}};

assign tmp_4_fu_1037_p3 = {{acc_1_reg_1613}, {1'd0}};

assign tmp_5_fu_1054_p3 = add_ln1010_fu_1048_p2[32'd43];

assign tmp_6_fu_1114_p4 = {{residual_q_raw_fu_1100_p3[23:7]}};

assign tmp_7_fu_1166_p3 = mul_ln1032_reg_1645[32'd31];

assign tmp_8_fu_1235_p3 = final_value_fu_1225_p2[32'd14];

assign tmp_fu_754_p4 = {{or_ln843_fu_748_p2[9:8]}};

assign tmp_s_fu_645_p3 = {{trunc_ln811_fu_621_p1}, {8'd0}};

assign trunc_ln1048_fu_1231_p1 = final_value_fu_1225_p2[13:0];

assign trunc_ln106_fu_1134_p1 = residual_q_raw_reg_1624[7:0];

assign trunc_ln1078_fu_1257_p1 = final_value_1_fu_1243_p3[11:0];

assign trunc_ln1_fu_1193_p4 = {{add_ln39_1_fu_1173_p2[31:20]}};

assign trunc_ln40_7_fu_1068_p4 = {{add_ln39_fu_1062_p2[43:20]}};

assign trunc_ln46_7_fu_1084_p4 = {{sub_ln45_fu_1078_p2[43:20]}};

assign trunc_ln811_fu_621_p1 = select_ln803_fu_614_p3[7:0];

assign trunc_ln855_fu_689_p1 = empty_49_fu_683_p2[7:0];

assign trunc_ln_fu_1183_p4 = {{sub_ln45_1_fu_1178_p2[31:20]}};

assign xor_ln802_fu_449_p2 = (icmp_ln810_fu_435_p2 ^ 1'd1);

assign zext_ln1051_1_fu_1130_p1 = add_ln1051_reg_1418_pp0_iter8_reg;

assign zext_ln1051_fu_657_p1 = select_ln810_reg_1402;

assign zext_ln1053_fu_1221_p1 = baseline_ticks_q0;

assign zext_ln803_fu_653_p1 = select_ln803_fu_614_p3;

assign zext_ln810_fu_666_p1 = select_ln810_reg_1402;

assign zext_ln821_fu_669_p1 = select_ln821_fu_638_p3;

assign zext_ln828_fu_715_p1 = kx_mid2_reg_1408;

assign zext_ln855_fu_743_p1 = add_ln855_fu_737_p2;

assign zext_ln897_fu_776_p1 = add_ln886_fu_770_p2;

always @ (posedge ap_clk) begin
    sub_ln1010_reg_1619[8:0] <= 9'b000000000;
end

endmodule //reconstruction_accel_reconstruction_accel_Pipeline_CONV3_Y_CONV3_X_CONV3_KY_CONV3_KX
